# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from v4_proto.dydxprotocol.perpetuals import tx_pb2 as dydxprotocol_dot_perpetuals_dot_tx__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dydxprotocol/perpetuals/tx_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MsgStub(object):
    """Msg defines the Msg service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddPremiumVotes = channel.unary_unary(
                '/dydxprotocol.perpetuals.Msg/AddPremiumVotes',
                request_serializer=dydxprotocol_dot_perpetuals_dot_tx__pb2.MsgAddPremiumVotes.SerializeToString,
                response_deserializer=dydxprotocol_dot_perpetuals_dot_tx__pb2.MsgAddPremiumVotesResponse.FromString,
                _registered_method=True)
        self.CreatePerpetual = channel.unary_unary(
                '/dydxprotocol.perpetuals.Msg/CreatePerpetual',
                request_serializer=dydxprotocol_dot_perpetuals_dot_tx__pb2.MsgCreatePerpetual.SerializeToString,
                response_deserializer=dydxprotocol_dot_perpetuals_dot_tx__pb2.MsgCreatePerpetualResponse.FromString,
                _registered_method=True)
        self.SetLiquidityTier = channel.unary_unary(
                '/dydxprotocol.perpetuals.Msg/SetLiquidityTier',
                request_serializer=dydxprotocol_dot_perpetuals_dot_tx__pb2.MsgSetLiquidityTier.SerializeToString,
                response_deserializer=dydxprotocol_dot_perpetuals_dot_tx__pb2.MsgSetLiquidityTierResponse.FromString,
                _registered_method=True)
        self.UpdatePerpetualParams = channel.unary_unary(
                '/dydxprotocol.perpetuals.Msg/UpdatePerpetualParams',
                request_serializer=dydxprotocol_dot_perpetuals_dot_tx__pb2.MsgUpdatePerpetualParams.SerializeToString,
                response_deserializer=dydxprotocol_dot_perpetuals_dot_tx__pb2.MsgUpdatePerpetualParamsResponse.FromString,
                _registered_method=True)
        self.UpdateParams = channel.unary_unary(
                '/dydxprotocol.perpetuals.Msg/UpdateParams',
                request_serializer=dydxprotocol_dot_perpetuals_dot_tx__pb2.MsgUpdateParams.SerializeToString,
                response_deserializer=dydxprotocol_dot_perpetuals_dot_tx__pb2.MsgUpdateParamsResponse.FromString,
                _registered_method=True)


class MsgServicer(object):
    """Msg defines the Msg service.
    """

    def AddPremiumVotes(self, request, context):
        """AddPremiumVotes add new samples of the funding premiums to the
        application.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePerpetual(self, request, context):
        """CreatePerpetual creates a new perpetual object.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetLiquidityTier(self, request, context):
        """SetLiquidityTier creates an liquidity tier if the ID doesn't exist, and
        updates the existing liquidity tier otherwise.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePerpetualParams(self, request, context):
        """UpdatePerpetualParams updates the parameters of a perpetual market.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateParams(self, request, context):
        """UpdateParams updates the parameters of perpetuals module.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MsgServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddPremiumVotes': grpc.unary_unary_rpc_method_handler(
                    servicer.AddPremiumVotes,
                    request_deserializer=dydxprotocol_dot_perpetuals_dot_tx__pb2.MsgAddPremiumVotes.FromString,
                    response_serializer=dydxprotocol_dot_perpetuals_dot_tx__pb2.MsgAddPremiumVotesResponse.SerializeToString,
            ),
            'CreatePerpetual': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePerpetual,
                    request_deserializer=dydxprotocol_dot_perpetuals_dot_tx__pb2.MsgCreatePerpetual.FromString,
                    response_serializer=dydxprotocol_dot_perpetuals_dot_tx__pb2.MsgCreatePerpetualResponse.SerializeToString,
            ),
            'SetLiquidityTier': grpc.unary_unary_rpc_method_handler(
                    servicer.SetLiquidityTier,
                    request_deserializer=dydxprotocol_dot_perpetuals_dot_tx__pb2.MsgSetLiquidityTier.FromString,
                    response_serializer=dydxprotocol_dot_perpetuals_dot_tx__pb2.MsgSetLiquidityTierResponse.SerializeToString,
            ),
            'UpdatePerpetualParams': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePerpetualParams,
                    request_deserializer=dydxprotocol_dot_perpetuals_dot_tx__pb2.MsgUpdatePerpetualParams.FromString,
                    response_serializer=dydxprotocol_dot_perpetuals_dot_tx__pb2.MsgUpdatePerpetualParamsResponse.SerializeToString,
            ),
            'UpdateParams': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateParams,
                    request_deserializer=dydxprotocol_dot_perpetuals_dot_tx__pb2.MsgUpdateParams.FromString,
                    response_serializer=dydxprotocol_dot_perpetuals_dot_tx__pb2.MsgUpdateParamsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dydxprotocol.perpetuals.Msg', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dydxprotocol.perpetuals.Msg', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Msg(object):
    """Msg defines the Msg service.
    """

    @staticmethod
    def AddPremiumVotes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dydxprotocol.perpetuals.Msg/AddPremiumVotes',
            dydxprotocol_dot_perpetuals_dot_tx__pb2.MsgAddPremiumVotes.SerializeToString,
            dydxprotocol_dot_perpetuals_dot_tx__pb2.MsgAddPremiumVotesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreatePerpetual(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dydxprotocol.perpetuals.Msg/CreatePerpetual',
            dydxprotocol_dot_perpetuals_dot_tx__pb2.MsgCreatePerpetual.SerializeToString,
            dydxprotocol_dot_perpetuals_dot_tx__pb2.MsgCreatePerpetualResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetLiquidityTier(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dydxprotocol.perpetuals.Msg/SetLiquidityTier',
            dydxprotocol_dot_perpetuals_dot_tx__pb2.MsgSetLiquidityTier.SerializeToString,
            dydxprotocol_dot_perpetuals_dot_tx__pb2.MsgSetLiquidityTierResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePerpetualParams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dydxprotocol.perpetuals.Msg/UpdatePerpetualParams',
            dydxprotocol_dot_perpetuals_dot_tx__pb2.MsgUpdatePerpetualParams.SerializeToString,
            dydxprotocol_dot_perpetuals_dot_tx__pb2.MsgUpdatePerpetualParamsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateParams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dydxprotocol.perpetuals.Msg/UpdateParams',
            dydxprotocol_dot_perpetuals_dot_tx__pb2.MsgUpdateParams.SerializeToString,
            dydxprotocol_dot_perpetuals_dot_tx__pb2.MsgUpdateParamsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
