geometri_encoding_kodeliste = {
    "ContainedItemsResult": {
        "Count": 4,
        "Offset": 0,
        "Limit": 0,
        "Total": 0,
    },
    "id": "geometri_encoding",
    "label": "Geometri encoding",
    "lang": "no",
    "owner": "DASK",
    "manager": "Kartverket",
    "containedItemClass": "CodelistValue",
    "containeditems": [
        {
            "id": "dataplattform/geometri_encoding/wkt",
            "label": "Well-Known-Text",
            "lang": "no",
            "itemclass": "CodelistValue",
            "status": "Gyldig",
            "description": "Well Known Text (WKT) er et tekstmarkeringsspråk for å representere vektorgeometriobjekter",
            "owner": "Dataplattform",
            "versionNumber": 1,
            "lastUpdated": "2022-04-08",
            "dateSubmitted": "2022-04-08",
            "codevalue": "WKT",
        },
        {
            "id": "dataplattform/geometri_encoding/wkb",
            "label": "Well-Known-Binary",
            "lang": "no",
            "itemclass": "CodelistValue",
            "status": "Gyldig",
            "description": "WKB står for Well Known Binary, et format for å representere geografiske og geometriske data. WKB bruker 1-byte usignerte heltall, 4-byte usignerte heltall og 8-byte dobbeltpresisjonstall.",
            "owner": "Dataplattform",
            "versionNumber": 1,
            "lastUpdated": "2022-04-08",
            "dateSubmitted": "2022-04-08",
            "codevalue": "WKB",
        },
        {
            "id": "dataplattform/geometri_encoding/geojson",
            "label": "GeoJson",
            "lang": "no",
            "itemclass": "CodelistValue",
            "status": "Gyldig",
            "description": "GeoJSON er et format for koding av en rekke geografiske datastrukturer, inkludert de syv geometritypene definert i OpenGIS Simple Features Implementation Specification for SQL [SFSQL]",
            "owner": "Dataplattform",
            "versionNumber": 1,
            "lastUpdated": "2022-04-08",
            "dateSubmitted": "2022-04-08",
            "codevalue": "geojson",
        },
        {
            "id": "dataplattform/geometri_encoding/s2",
            "label": "S2-cell",
            "lang": "no",
            "itemclass": "CodelistValue",
            "status": "Gyldig",
            "description": "S2-celler er unikt identifisert av en 64-bits S2CellId. S2-cellene er nummerert på en spesiell måte for å maksimere referanselokaliteten når de brukes til romlig indeksering",
            "owner": "Dataplattform",
            "versionNumber": 1,
            "lastUpdated": "2022-04-08",
            "dateSubmitted": "2022-04-08",
            "codevalue": "s2",
        },
    ],
    "containedSubRegisters": [],
    "lastUpdated": "2025-04-08T15:15:00.000",
}
