from typing import TYPE_CHECKING

from .audio import (
    AudioDetectorSensor,
    AudioFrameData,
    AudioProperty,
    AudioResult,
    AudioSensor,
    AudioSensorLike,
)
from .base import (
    PropertyChangedEvent,
    PropertyChangeListener,
    Sensor,
    SensorCategory,
    SensorJSON,
    SensorLike,
    SensorType,
)

if TYPE_CHECKING:
    from .base import SensorCapability, SensorPropertyType

from .battery import (
    BatteryCapability,
    BatteryInfo,
    BatteryInfoLike,
    BatteryProperty,
    ChargingState,
)
from .classifier import (
    ClassifierDetectorSensor,
    ClassifierProperty,
    ClassifierResult,
    ClassifierSensor,
    ClassifierSensorLike,
)
from .contact import (
    ContactProperty,
    ContactSensor,
    ContactSensorLike,
)
from .doorbell import (
    DoorbellProperty,
    DoorbellTrigger,
    DoorbellTriggerLike,
)
from .face import (
    FaceDetection,
    FaceDetectorSensor,
    FaceLandmarks,
    FaceProperty,
    FaceResult,
    FaceSensor,
    FaceSensorLike,
)
from .license_plate import (
    LicensePlateDetection,
    LicensePlateDetectorSensor,
    LicensePlateProperty,
    LicensePlateResult,
    LicensePlateSensor,
    LicensePlateSensorLike,
)
from .light import (
    LightCapability,
    LightControl,
    LightControlLike,
    LightProperty,
)
from .motion import (
    BASE_DETECTION_LABELS,
    BaseDetectionLabel,
    BoundingBox,
    Detection,
    DetectionLabel,
    MotionDetectorSensor,
    MotionProperty,
    MotionResult,
    MotionSensor,
    MotionSensorLike,
    VideoFrameData,
)
from .object import (
    ObjectDetectorSensor,
    ObjectProperty,
    ObjectResult,
    ObjectSensor,
    ObjectSensorLike,
)
from .ptz import (
    PTZCapability,
    PTZControl,
    PTZControlLike,
    PTZDirection,
    PTZPosition,
    PTZProperty,
)
from .security_system import (
    SecuritySystem,
    SecuritySystemLike,
    SecuritySystemProperty,
    SecuritySystemState,
)
from .siren import (
    SirenCapability,
    SirenControl,
    SirenControlLike,
    SirenProperty,
)
from .spec import (
    AudioInputSpec,
    AudioModelSpec,
    ModelSpec,
    ObjectModelSpec,
    VideoInputSpec,
)
from .switch import (
    SwitchControl,
    SwitchControlLike,
    SwitchProperty,
)

__all__ = [
    "Sensor",
    "SensorJSON",
    "SensorLike",
    "SensorType",
    "SensorCategory",
    "SensorPropertyType",
    "SensorCapability",
    "PropertyChangeListener",
    "PropertyChangedEvent",
    "VideoInputSpec",
    "ObjectModelSpec",
    "ModelSpec",
    "AudioInputSpec",
    "AudioModelSpec",
    "BASE_DETECTION_LABELS",
    "BaseDetectionLabel",
    "DetectionLabel",
    "BoundingBox",
    "Detection",
    "VideoFrameData",
    "MotionResult",
    "AudioFrameData",
    "AudioResult",
    "FaceLandmarks",
    "FaceDetection",
    "FaceResult",
    "LicensePlateDetection",
    "LicensePlateResult",
    "ClassifierResult",
    "ObjectResult",
    "ChargingState",
    "PTZPosition",
    "PTZDirection",
    "MotionProperty",
    "MotionSensorLike",
    "MotionSensor",
    "MotionDetectorSensor",
    "ObjectProperty",
    "ObjectSensorLike",
    "ObjectSensor",
    "ObjectDetectorSensor",
    "AudioProperty",
    "AudioSensorLike",
    "AudioSensor",
    "AudioDetectorSensor",
    "FaceProperty",
    "FaceSensorLike",
    "FaceSensor",
    "FaceDetectorSensor",
    "LicensePlateProperty",
    "LicensePlateSensorLike",
    "LicensePlateSensor",
    "LicensePlateDetectorSensor",
    "ClassifierProperty",
    "ClassifierSensorLike",
    "ClassifierSensor",
    "ClassifierDetectorSensor",
    "ContactProperty",
    "ContactSensorLike",
    "ContactSensor",
    "LightCapability",
    "LightProperty",
    "LightControlLike",
    "LightControl",
    "SirenCapability",
    "SirenProperty",
    "SirenControlLike",
    "SirenControl",
    "SwitchProperty",
    "SwitchControlLike",
    "SwitchControl",
    "PTZCapability",
    "PTZProperty",
    "PTZControlLike",
    "PTZControl",
    "SecuritySystem",
    "SecuritySystemLike",
    "SecuritySystemProperty",
    "SecuritySystemState",
    "DoorbellProperty",
    "DoorbellTriggerLike",
    "DoorbellTrigger",
    "BatteryCapability",
    "BatteryProperty",
    "BatteryInfoLike",
    "BatteryInfo",
]
