NAME_VALUE_DELIMITER = "¬"

TIMING_PREFIX = "@timing@"

ENVIRONMENT_PREFIX = "@environment@"

INSPECTION_PREFIX = "@inspection@"

SYSTEM_INFORMATION_SYSTEM = "System"
SYSTEM_INFORMATION_NODE_NAME = (
    "Node Name"
)
SYSTEM_INFORMATION_RELEASE = "Release"
SYSTEM_INFORMATION_VERSION = "Version"
SYSTEM_INFORMATION_MACHINE = "Machine"
SYSTEM_INFORMATION_PROCESSOR = (
    "Processor"
)

CPU_INFORMATION_PHYSICAL_CORES = (
    "Physical cores"
)
CPU_INFORMATION_TOTAL_CORES = (
    "Total cores"
)
CPU_INFORMATION_MAX_FREQUENCY = (
    "Max Frequency"
)
CPU_INFORMATION_MIN_FREQUENCY = (
    "Min Frequency"
)
CPU_INFORMATION_CURRENT_FREQUENCY = (
    "Current Frequency"
)
CPU_INFORMATION_TOTAL_CPU_USAGE = (
    "Total CPU Usage"
)
CPU_INFORMATION_CORE_PREFIX = "Core"

DISK_INFORMATION_TOTAL_READ = (
    "Total read"
)
DISK_INFORMATION_TOTAL_WRITE = (
    "Total write"
)
DISK_INFORMATION_TOTAL_SIZE = (
    "Total Size"
)
DISK_INFORMATION_USED = "Used"
DISK_INFORMATION_FREE = "Free"
DISK_INFORMATION_PERCENTAGE = (
    "Percentage"
)

ENVIRON_INFORMATION_USERNAME = (
    "USERNAME"
)
ENVIRON_INFORMATION_COMPUTERNAME = (
    "COMPUTERNAME"
)
ENVIRON_INFORMATION_NUMBER_OF_PROCESSORS = (
    "NUMBER_OF_PROCESSORS"
)
ENVIRON_INFORMATION_VIRTUAL_ENV = (
    "VIRTUAL_ENV"
)
ENVIRON_INFORMATION_PROCESSOR_ARCHITECTURE = (
    "PROCESSOR_ARCHITECTURE"
)
ENVIRON_INFORMATION_PROCESSOR_IDENTIFIER = (
    "PROCESSOR_IDENTIFIER"
)

MEMORY_INFORMATION_VIRTUAL_TOTAL = (
    "(virtual) Total"
)
MEMORY_INFORMATION_VIRTUAL_AVAILABLE = (
    "(virtual) Available"
)
MEMORY_INFORMATION_VIRTUAL_USED = (
    "(virtual) Used"
)
MEMORY_INFORMATION_VIRTUAL_PERCENTAGE = (
    "(virtual) Percentage"
)
MEMORY_INFORMATION_SWAP_TOTAL = (
    "(swap) Total"
)
MEMORY_INFORMATION_SWAP_FREE = (
    "(swap) Free"
)
MEMORY_INFORMATION_SWAP_USED = (
    "(swap) Used"
)
MEMORY_INFORMATION_SWAP_PERCENTAGE = (
    "(swap) Percentage"
)

NETWORK_INFORMATION_INTERFACE = (
    "Interface"
)
NETWORK_INFORMATION_IP_ADDRESS = (
    "IP Address"
)
NETWORK_INFORMATION_NETMASK = "Netmask"
NETWORK_INFORMATION_BROADCAST_IP = (
    "Broadcast IP"
)
NETWORK_INFORMATION_MAC_ADDRESS = (
    "MAC Address"
)
NETWORK_INFORMATION_BROADCAST_MAC = (
    "Broadcast MAC"
)
NETWORK_INFORMATION_TOTAL_BYTES_SENT = (
    "Total Bytes Sent"
)
NETWORK_INFORMATION_TOTAL_BYTES_RECEIVED = (
    "Total Bytes Received"
)

LOG_START = "start"
LOG_END = "end"

OVERALL_RUN = "run"
