#ifndef NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION "6.2.2601-1-g6c9797ff"
#define NETGEN_VERSION_MAJOR 6
#define NETGEN_VERSION_MINOR 2
#define NETGEN_VERSION_PATCH 2601
#define NETGEN_VERSION_TWEAK 1
#define NETGEN_VERSION_HASH "g6c9797ff"
#endif // NETGEN_VERSION_HPP_INCLUDED
