# flake8: noqa
from typing import Optional

from keplemon.elements import TLE, OrbitPlotData

class TLECatalog:
    count: int
    name: Optional[str]
    def __init__(self) -> None: ...
    @classmethod
    def from_tle_file(cls, filename: str) -> TLECatalog: ...
    def add(self, tle: TLE) -> None: ...
    def get(self, satellite_id: str) -> TLE: ...
    def remove(self, satellite_id: str) -> None: ...
    def keys(self) -> list[str]: ...
    def get_count(self) -> int: ...
    def clear(self) -> None: ...
    def __getitem__(self, satellite_id: str) -> TLE: ...
    def get_plot_data(self) -> OrbitPlotData: ...
