from synchronizer_rpc.data.EnumDefine import *
from libuseful.lib_logger import *
import grpc
from ..ProxyGRPC import ProxyGRPC, ServiceDesp
from synchronizer_rpc.proto import syncProc_pb2 as cApiMsg
from typing import Callable

__all__ = ['SVCstatus']

class SVCstatus(ServiceDesp):
    class ValueCB:
        result: bool
        error: EErrorDesp
        errMsg: str
        path: str
        def __init__(self, res: bool, err: cApiMsg.ErrorData, path: str = None) -> None: ...
    SVC_NAME: str
    @property
    def async_mode(self): ...
    def register(self, fp_subscribe: Callable[[str, EStatus, str, EError], None] = None): ...
    def ping_sync(self, chan: grpc.Channel): ...
    async def ping(self, chan: grpc.Channel): ...
    def request_DoneInit(self, func_cb: Callable[[str, bool], None], result: bool): ...
    def request_DoneStart(self, func_cb: Callable[[str, bool], None], result: bool): ...
    def request_DoneStop(self, func_cb: Callable[[str, bool], None], result: bool): ...
    def request_DonePPSon(self, func_cb: Callable[[str, bool], None], result: bool): ...
    def __init__(self, proxy: ProxyGRPC, user_id: str, async_mode: bool = False) -> None: ...
