import { DirectServiceIO } from '../../utils/directServiceIO';
import { DeepChat } from '../../../deepChat';
export declare class OpenAIRealtimeIO extends DirectServiceIO {
    insertKeyPlaceholderText: string;
    keyHelpUrl: string;
    private readonly _avatarConfig;
    private readonly _buttonsConfig;
    private readonly _errorConfig;
    private readonly _loadingConfig;
    private readonly _avatarEl;
    private readonly _containerEl;
    private readonly _deepChat;
    private _microphoneButton;
    private _toggleButton;
    private _errorElement;
    private _loadingElement;
    private _pc;
    private _mediaStream;
    private _isMuted;
    private _ephemeralKey?;
    private _retrievingEphemeralKey?;
    private _dc?;
    private readonly _events?;
    private readonly _functionHandlerI?;
    private static readonly BUTTON_DEFAULT;
    private static readonly BUTTON_LOADING;
    private static readonly MICROPHONE_ACTIVE;
    private static readonly UNAVAILABLE;
    constructor(deepChat: DeepChat);
    private static getKey;
    private setInputAudioTranscribe;
    setUpView(oldContainerElement: HTMLElement, parentElement: HTMLElement): void;
    private setup;
    private fetchEphemeralKey;
    private getEphemeralKey;
    private generateMethods;
    private static buildAvatarConfig;
    private static buildButtonsConfig;
    private createContainer;
    private createAvatarContainer;
    private static createAvatar;
    private createButtonsContainer;
    private static createButtonContainer;
    private createMicophoneButton;
    private toggleMicorphone;
    private createToggleButton;
    private init;
    private monitorFrequencies;
    private stopOnError;
    private stop;
    private changeToUnavailable;
    private static changeButtonToUnavailable;
    private changeToAvailable;
    private static changeButtonToAvailable;
    private removeUnavailable;
    private static removeButtonUnavailable;
    private createError;
    private displayFailedToRetrieveEphemeralKey;
    private displayError;
    private createLoading;
    private displayLoading;
    private hideLoading;
    private handleTool;
    sendMessage(item: object): void;
    isCustomView(): boolean;
}
//# sourceMappingURL=openAIRealtimeIO.d.ts.map