"""Atajos de importación para el paquete :mod:`fletplus`.

La intención es que las aplicaciones consumidoras puedan realizar importaciones
absolutas estables como ``from fletplus import ThemeManager`` sin depender de
la estructura interna de submódulos. Esto evita errores de importación cuando
se distribuye la librería y mejora la experiencia para los usuarios finales.
"""

from fletplus.animation import (
    AnimatedContainer,
    AnimationController,
    FadeIn,
    Scale,
    SlideTransition,
    animation_controller_context,
)
from fletplus.core import FletPlusApp, FloatingMenuOptions, ResponsiveNavigationConfig
from fletplus.context import (
    Context,
    ContextProvider,
    locale_context,
    theme_context,
    user_context,
)
from fletplus.router import Router, Route, LayoutInstance, layout_from_attribute
from fletplus.icons import (
    DEFAULT_ICON_SET,
    Icon,
    available_icon_sets,
    has_icon,
    icon,
    list_icons,
    register_icon,
    register_icon_set,
    resolve_icon_name,
)
from fletplus.themes import (
    ThemeManager,
    load_palette_from_file,
    load_theme_from_json,
    list_palettes,
    get_palette_tokens,
    has_palette,
    get_palette_definition,
    list_presets,
    has_preset,
    get_preset_definition,
)
from fletplus.components import (
    PrimaryButton,
    SecondaryButton,
    SuccessButton,
    WarningButton,
    DangerButton,
    InfoButton,
    IconButton,
    OutlinedButton,
    TextButton,
    FloatingActionButton,
    CommandPalette,
    AccessibilityPanel,
    AdaptiveDestination,
    AdaptiveNavigationLayout,
    FlexRow,
    FlexColumn,
    Grid,
    GridItem,
    ResponsiveContainer,
    ResponsiveGrid,
    Spacer,
    Stack,
    StackItem,
    SidebarAdmin,
    SmartTable,
    LineChart,
    Wrap,
)
from fletplus.utils import (
    ResponsiveStyle,
    ResponsiveTypography,
    responsive_text,
    responsive_spacing,
    ResponsiveManager,
    ShortcutManager,
    FileDropZone,
    ResponsiveVisibility,
    is_mobile,
    is_web,
    is_desktop,
)
from fletplus.desktop import WindowManager, SystemTray, show_notification
from fletplus.http import DiskCache, HttpClient, HttpInterceptor, RequestEvent, ResponseEvent
from fletplus.web import (
    generate_manifest,
    generate_service_worker,
    register_pwa,
)
from fletplus.state import DerivedSignal, Signal, Store, reactive, use_signal, use_state, watch
from fletplus.storage import StorageProvider
from fletplus.storage.files import FileStorageProvider
from fletplus.storage.local import LocalStorageProvider
from fletplus.storage.session import SessionStorageProvider

__all__ = [
    "FletPlusApp",
    "FloatingMenuOptions",
    "ResponsiveNavigationConfig",
    "AnimationController",
    "animation_controller_context",
    "FadeIn",
    "SlideTransition",
    "Scale",
    "AnimatedContainer",
    "ThemeManager",
    "load_palette_from_file",
    "load_theme_from_json",
    "list_palettes",
    "get_palette_tokens",
    "has_palette",
    "get_palette_definition",
    "list_presets",
    "has_preset",
    "get_preset_definition",
    "PrimaryButton",
    "SecondaryButton",
    "SuccessButton",
    "WarningButton",
    "DangerButton",
    "InfoButton",
    "IconButton",
    "OutlinedButton",
    "TextButton",
    "FloatingActionButton",
    "CommandPalette",
    "AccessibilityPanel",
    "AdaptiveDestination",
    "AdaptiveNavigationLayout",
    "FlexRow",
    "FlexColumn",
    "Grid",
    "GridItem",
    "ResponsiveContainer",
    "ResponsiveGrid",
    "Spacer",
    "Stack",
    "StackItem",
    "Wrap",
    "SidebarAdmin",
    "SmartTable",
    "LineChart",
    "ResponsiveStyle",
    "ResponsiveTypography",
    "responsive_text",
    "responsive_spacing",
    "ResponsiveManager",
    "ShortcutManager",
    "FileDropZone",
    "ResponsiveVisibility",
    "is_mobile",
    "is_web",
    "is_desktop",
    "WindowManager",
    "SystemTray",
    "show_notification",
    "HttpClient",
    "DiskCache",
    "HttpInterceptor",
    "RequestEvent",
    "ResponseEvent",
    "generate_manifest",
    "generate_service_worker",
    "register_pwa",
    "Router",
    "Route",
    "LayoutInstance",
    "layout_from_attribute",
    "DEFAULT_ICON_SET",
    "icon",
    "Icon",
    "available_icon_sets",
    "list_icons",
    "has_icon",
    "resolve_icon_name",
    "register_icon",
    "register_icon_set",
    "DerivedSignal",
    "Signal",
    "Store",
    "reactive",
    "use_state",
    "use_signal",
    "watch",
    "StorageProvider",
    "LocalStorageProvider",
    "SessionStorageProvider",
    "FileStorageProvider",
    "Context",
    "ContextProvider",
    "theme_context",
    "user_context",
    "locale_context",
]
