from typing import List


class __Board:
    def getBoardIds(self) -> List[str]: ...
    def getCount(self) -> int: ...
    def getId(self, boardIdx: int) -> str: ...
    def isPowered(self, boardId: str) -> bool: ...
    def powerOff(self, boardId: str) -> None: ...
    def powerOn(self, boardId: str) -> None: ...
