# interfaces/env_handler_interface.py
from typing import Protocol, Callable, Optional, Union, Any
from flask import Response

class IHttpResponseHandler(Protocol):
    def http_response(self, method, response) -> Response: ...
    def http_handler(self, request, endpoint: str, fn: Callable[..., dict], *, socketio: Optional[Any] = None)  -> Response: ...
    def get_http_request(self, request, query_list, url_key, endpoint, item_id: Optional[str] = None, accept_header: Optional[str] = None) -> Response: ...    
    def post_http_request(self, request, body, query_list, url_key, endpoint, item_id: Optional[str] = None, accept_header: Optional[str] = None) -> Response: ...
    def client_get_http_request(self, request, query_list, url_key, endpoint, item_id: Optional[str] = None, accept_header: Optional[str] = None) -> dict: ...
    def client_get_amqp_request(self, message, query_list, url_key, endpoint, item_id: Optional[str] = None, accept_header: Optional[str] = None) -> dict: ...
    def client_post_http_request(self, request, body: Optional[Union[dict, bytes]], query_list, url_key, endpoint, item_id: Optional[str] = None, accept_header: Optional[str] = None) -> dict: ...
    def client_post_amqp_request(self, body, message, query_list, url_key, endpoint, item_id: Optional[str] = None, content_type: Optional[str] = None, accept_header: Optional[str] = None) -> dict: ...
