# interfaces/logger_interface.py
from typing import Protocol
from atk_common.enums.log_level_enum import LogLevel

class ILogger(Protocol):
    def debug(self, msg: str) -> None: ...
    def info(self, msg: str) -> None: ...
    def warning(self, msg: str) -> None: ...
    def error(self, msg: str) -> None: ...
    def set_level(self, log_level: LogLevel) -> None: ...
    def get_level(self) -> LogLevel: ...