"""
    EMIL InsuranceService

    The EMIL InsuranceService API description  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: kontakt@emil.de
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import eis.insurance
from eis.insurance.model.create_account_request_dto import CreateAccountRequestDto
from eis.insurance.model.create_lead_policy_request_dto import CreateLeadPolicyRequestDto
from eis.insurance.model.lead_bank_account_class import LeadBankAccountClass
from eis.insurance.model.omit_type_class import OmitTypeClass
from eis.insurance.model.premium_override_request_class import PremiumOverrideRequestClass
from eis.insurance.model.shared_invoice_class import SharedInvoiceClass
from eis.insurance.model.shared_payment_method_response_class import SharedPaymentMethodResponseClass
from eis.insurance.model.uploaded_document_dto import UploadedDocumentDto
globals()['CreateAccountRequestDto'] = CreateAccountRequestDto
globals()['CreateLeadPolicyRequestDto'] = CreateLeadPolicyRequestDto
globals()['LeadBankAccountClass'] = LeadBankAccountClass
globals()['OmitTypeClass'] = OmitTypeClass
globals()['PremiumOverrideRequestClass'] = PremiumOverrideRequestClass
globals()['SharedInvoiceClass'] = SharedInvoiceClass
globals()['SharedPaymentMethodResponseClass'] = SharedPaymentMethodResponseClass
globals()['UploadedDocumentDto'] = UploadedDocumentDto
from eis.insurance.model.lead_class import LeadClass


class TestLeadClass(unittest.TestCase):
    """LeadClass unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLeadClass(self):
        """Test LeadClass"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LeadClass()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
