"""
    EMIL InsuranceService

    The EMIL InsuranceService API description  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: kontakt@emil.de
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import eis.insurance
from eis.insurance.model.billing_address_dto import BillingAddressDto
globals()['BillingAddressDto'] = BillingAddressDto
from eis.insurance.model.bank_transfer_dto import BankTransferDto


class TestBankTransferDto(unittest.TestCase):
    """BankTransferDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBankTransferDto(self):
        """Test BankTransferDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BankTransferDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
