from typing import Literal

FontFamily = Literal[
    "ADLaM Display",
    "Aboreto",
    "Abyssinica SIL",
    "Afacad",
    "Afacad Flux",
    "Agbalumo",
    "Agdasima",
    "Agu Display",
    "Akatab",
    "Akaya Kanadaka",
    "Akshar",
    "Alan Sans",
    "Albert Sans",
    "Alexandria",
    "Alkalami",
    "Alkatra",
    "Alumni Sans Collegiate One",
    "Alumni Sans Inline One",
    "Alumni Sans Pinstripe",
    "Alumni Sans SC",
    "Amiri Quran",
    "Ancizar Sans",
    "Ancizar Serif",
    "Anek Bangla",
    "Anek Devanagari",
    "Anek Gujarati",
    "Anek Gurmukhi",
    "Anek Kannada",
    "Anek Latin",
    "Anek Malayalam",
    "Anek Odia",
    "Anek Tamil",
    "Anek Telugu",
    "Angkor",
    "Annapurna SIL",
    "Anta",
    "Anton SC",
    "Antonio",
    "Anybody",
    "Aoboshi One",
    "AR One Sans",
    "Aref Ruqaa Ink",
    "Arima",
    "Arsenal SC",
    "Asimovian",
    "Asta Sans",
    "Atkinson Hyperlegible Mono",
    "Atkinson Hyperlegible Next",
    "BIZ UDGothic",
    "BIZ UDMincho",
    "BIZ UDPGothic",
    "BIZ UDPMincho",
    "Babylonica",
    "Bacasime Antique",
    "Badeen Display",
    "Bagel Fat One",
    "Ballet",
    "Baskervville SC",
    "Battambang",
    "Bayon",
    "Beau Rivage",
    "Beiruti",
    "Belanosima",
    "Benne",
    "BhuTuka Expanded One",
    "Big Shoulders",
    "Big Shoulders Inline",
    "Big Shoulders Stencil",
    "Bitcount",
    "Bitcount Grid Double",
    "Bitcount Grid Double Ink",
    "Bitcount Grid Single",
    "Bitcount Grid Single Ink",
    "Bitcount Ink",
    "Bitcount Prop Double",
    "Bitcount Prop Double Ink",
    "Bitcount Prop Single",
    "Bitcount Prop Single Ink",
    "Bitcount Single",
    "Bitcount Single Ink",
    "Blaka",
    "Blaka Hollow",
    "Blaka Ink",
    "Bodoni Moda",
    "Bodoni Moda SC",
    "Bokor",
    "Boldonse",
    "Bona Nova SC",
    "Borel",
    "Braah One",
    "Bricolage Grotesque",
    "Bruno Ace",
    "Bruno Ace SC",
    "Bungee Spice",
    "Bungee Tint",
    "Bytesized",
    "Cactus Classical Serif",
    "Cairo Play",
    "Cal Sans",
    "Caprasimo",
    "Carlito",
    "Cascadia Code",
    "Cascadia Mono",
    "Castoro Titling",
    "Charis SIL",
    "Chenla",
    "Cherry Bomb One",
    "Chiron GoRound TC",
    "Chiron Hei HK",
    "Chiron Sung HK",
    "Chivo Mono",
    "Chocolate Classical Sans",
    "Chokokutai",
    "Climate Crisis",
    "Comic Relief",
    "Comme",
    "Content",
    "Coral Pixels",
    "Cossette Texte",
    "Cossette Titre",
    "Dai Banna SIL",
    "Danfo",
    "Dangrek",
    "Darumadrop One",
    "Delicious Handrawn",
    "Diphylleia",
    "Doto",
    "DynaPuff",
    "Edu AU VIC WA NT Arrows",
    "Edu AU VIC WA NT Dots",
    "Edu AU VIC WA NT Guides",
    "Edu AU VIC WA NT Hand",
    "Edu AU VIC WA NT Pre",
    "Edu NSW ACT Cursive",
    "Edu NSW ACT Foundation",
    "Edu NSW ACT Hand Pre",
    "Edu QLD Beginner",
    "Edu QLD Hand",
    "Edu SA Beginner",
    "Edu SA Hand",
    "Edu TAS Beginner",
    "Edu VIC WA NT Beginner",
    "Edu VIC WA NT Hand",
    "Edu VIC WA NT Hand Pre",
    "Epunda Sans",
    "Epunda Slab",
    "Exile",
    "Faculty Glyphic",
    "Familjen Grotesk",
    "Fasthand",
    "Figtree",
    "Finlandica",
    "Foldit",
    "Fragment Mono",
    "Freehand",
    "Freeman",
    "Funnel Display",
    "Funnel Sans",
    "Fustat",
    "Ga Maamli",
    "Gabarito",
    "Gajraj One",
    "Gantari",
    "Gasoek One",
    "Geist",
    "Geist Mono",
    "Gentium Book Plus",
    "Gentium Plus",
    "Geologica",
    "Gidole",
    "Gloock",
    "Golos Text",
    "Google Sans Code",
    "Grandiflora One",
    "Grape Nuts",
    "Gulzar",
    "Handjet",
    "Hanken Grotesk",
    "Hanuman",
    "Hedvig Letters Sans",
    "Hedvig Letters Serif",
    "Hind Mysuru",
    "Honk",
    "Host Grotesk",
    "Hubballi",
    "Hubot Sans",
    "Huninn",
    "IBM Plex Sans JP",
    "Iansui",
    "Imbue",
    "Imperial Script",
    "Inclusive Sans",
    "Ingrid Darling",
    "Inspiration",
    "Instrument Sans",
    "Instrument Serif",
    "Intel One Mono",
    "Inter Tight",
    "Island Moments",
    "Jacquard 12",
    "Jacquard 12 Charted",
    "Jacquard 24",
    "Jacquard 24 Charted",
    "Jacquarda Bastarda 9",
    "Jacquarda Bastarda 9 Charted",
    "Jaini",
    "Jaini Purva",
    "Jaro",
    "Jersey 10",
    "Jersey 10 Charted",
    "Jersey 15",
    "Jersey 15 Charted",
    "Jersey 20",
    "Jersey 20 Charted",
    "Jersey 25",
    "Jersey 25 Charted",
    "Joan",
    "Kablammo",
    "Kalnia",
    "Kalnia Glaze",
    "Kanchenjunga",
    "Kantumruy Pro",
    "Kapakana",
    "Karantina",
    "Karla Tamil Inclined",
    "Karla Tamil Upright",
    "Kay Pho Du",
    "Kdam Thmor Pro",
    "Khmer",
    "Kiwi Maru",
    "Kode Mono",
    "Kolker Brush",
    "Konkhmer Sleokchher",
    "Koulen",
    "LXGW Marker Gothic",
    "LXGW WenKai Mono TC",
    "LXGW WenKai TC",
    "Labrada",
    "Lavishly Yours",
    "League Gothic",
    "League Spartan",
    "Libertinus Keyboard",
    "Libertinus Math",
    "Libertinus Mono",
    "Libertinus Sans",
    "Libertinus Serif",
    "Libertinus Serif Display",
    "Libre Barcode EAN13 Text",
    "Libre Bodoni",
    "Licorice",
    "Linefont",
    "Lisu Bosa",
    "Liter",
    "Love Light",
    "Lugrasimo",
    "Lumanosimo",
    "Lunasima",
    "Luxurious Roman",
    "Madimi One",
    "Maname",
    "Manufacturing Consent",
    "Marhey",
    "Martian Mono",
    "Matangi",
    "Matemasie",
    "Mea Culpa",
    "Menbere",
    "Metal",
    "Micro 5",
    "Micro 5 Charted",
    "Mingzat",
    "Moderustic",
    "Moirai One",
    "Mona Sans",
    "Monomakh",
    "Monomaniac One",
    "Montserrat Underline",
    "Moo Lah Lah",
    "Moon Dance",
    "Mooli",
    "Moul",
    "Moulpali",
    "Ms Madi",
    "My Soul",
    "Mynerve",
    "Nabla",
    "Namdhinggo",
    "Narnoor",
    "Nata Sans",
    "National Park",
    "Neonderthaw",
    "New Amsterdam",
    "Newsreader",
    "Nokora",
    "Noto Color Emoji",
    "Noto Emoji",
    "Noto Sans Chorasmian",
    "Noto Sans Cypro Minoan",
    "Noto Sans Ethiopic",
    "Noto Sans HK",
    "Noto Sans JP",
    "Noto Sans KR",
    "Noto Sans Kawi",
    "Noto Sans Lao Looped",
    "Noto Sans Mende Kikakui",
    "Noto Sans Nag Mundari",
    "Noto Sans Nandinagari",
    "Noto Sans NKo Unjoined",
    "Noto Sans SC",
    "Noto Sans SignWriting",
    "Noto Sans Sunuwar",
    "Noto Sans Syriac Eastern",
    "Noto Sans Tangsa",
    "Noto Sans TC",
    "Noto Sans Vithkuqi",
    "Noto Serif Dives Akuru",
    "Noto Serif HK",
    "Noto Serif Hentaigana",
    "Noto Serif JP",
    "Noto Serif KR",
    "Noto Serif Khojki",
    "Noto Serif Makasar",
    "Noto Serif NP Hmong",
    "Noto Serif Old Uyghur",
    "Noto Serif Oriya",
    "Noto Serif Ottoman Siyaq",
    "Noto Serif SC",
    "Noto Serif TC",
    "Noto Serif Todhri",
    "Noto Serif Toto",
    "Noto Serif Vithkuqi",
    "Noto Znamenny Musical Notation",
    "Nuosu SIL",
    "Ojuju",
    "Ole",
    "Onest",
    "Oooh Baby",
    "Orbit",
    "Orelega One",
    "Padyakke Expanded One",
    "Parastoo",
    "Parkinsans",
    "Pathway Extreme",
    "Phetsarath",
    "Phudu",
    "Pixelify Sans",
    "Platypi",
    "Playfair",
    "Playpen Sans",
    "Playpen Sans Arabic",
    "Playpen Sans Deva",
    "Playpen Sans Hebrew",
    "Playpen Sans Thai",
    "Playwrite AR",
    "Playwrite AR Guides",
    "Playwrite AT",
    "Playwrite AT Guides",
    "Playwrite AU NSW",
    "Playwrite AU NSW Guides",
    "Playwrite AU QLD",
    "Playwrite AU QLD Guides",
    "Playwrite AU SA",
    "Playwrite AU SA Guides",
    "Playwrite AU TAS",
    "Playwrite AU TAS Guides",
    "Playwrite AU VIC",
    "Playwrite AU VIC Guides",
    "Playwrite BE VLG",
    "Playwrite BE VLG Guides",
    "Playwrite BE WAL",
    "Playwrite BE WAL Guides",
    "Playwrite BR",
    "Playwrite BR Guides",
    "Playwrite CA",
    "Playwrite CA Guides",
    "Playwrite CL",
    "Playwrite CL Guides",
    "Playwrite CO",
    "Playwrite CO Guides",
    "Playwrite CU",
    "Playwrite CU Guides",
    "Playwrite CZ",
    "Playwrite CZ Guides",
    "Playwrite DE Grund",
    "Playwrite DE Grund Guides",
    "Playwrite DE LA",
    "Playwrite DE LA Guides",
    "Playwrite DE SAS",
    "Playwrite DE SAS Guides",
    "Playwrite DE VA",
    "Playwrite DE VA Guides",
    "Playwrite DK Loopet",
    "Playwrite DK Loopet Guides",
    "Playwrite DK Uloopet",
    "Playwrite DK Uloopet Guides",
    "Playwrite ES",
    "Playwrite ES Deco",
    "Playwrite ES Deco Guides",
    "Playwrite ES Guides",
    "Playwrite FR Moderne",
    "Playwrite FR Moderne Guides",
    "Playwrite FR Trad",
    "Playwrite FR Trad Guides",
    "Playwrite GB J",
    "Playwrite GB J Guides",
    "Playwrite GB S",
    "Playwrite GB S Guides",
    "Playwrite HR",
    "Playwrite HR Guides",
    "Playwrite HR Lijeva",
    "Playwrite HR Lijeva Guides",
    "Playwrite HU",
    "Playwrite HU Guides",
    "Playwrite ID",
    "Playwrite ID Guides",
    "Playwrite IE",
    "Playwrite IE Guides",
    "Playwrite IN",
    "Playwrite IN Guides",
    "Playwrite IS",
    "Playwrite IS Guides",
    "Playwrite IT Moderna",
    "Playwrite IT Moderna Guides",
    "Playwrite IT Trad",
    "Playwrite IT Trad Guides",
    "Playwrite MX",
    "Playwrite MX Guides",
    "Playwrite NG Modern",
    "Playwrite NG Modern Guides",
    "Playwrite NL",
    "Playwrite NL Guides",
    "Playwrite NO",
    "Playwrite NO Guides",
    "Playwrite NZ",
    "Playwrite NZ Guides",
    "Playwrite PE",
    "Playwrite PE Guides",
    "Playwrite PL",
    "Playwrite PL Guides",
    "Playwrite PT",
    "Playwrite PT Guides",
    "Playwrite RO",
    "Playwrite RO Guides",
    "Playwrite SK",
    "Playwrite SK Guides",
    "Playwrite TZ",
    "Playwrite TZ Guides",
    "Playwrite US Modern",
    "Playwrite US Modern Guides",
    "Playwrite US Trad",
    "Playwrite US Trad Guides",
    "Playwrite VN",
    "Playwrite VN Guides",
    "Playwrite ZA",
    "Playwrite ZA Guides",
    "Plus Jakarta Sans",
    "Pochaevsk",
    "Poetsen One",
    "Poltawski Nowy",
    "Ponnala",
    "Ponomar",
    "Preahvihear",
    "Protest Guerrilla",
    "Protest Revolution",
    "Protest Riot",
    "Protest Strike",
    "Qwitcher Grypen",
    "Radio Canada",
    "Radio Canada Big",
    "Reddit Mono",
    "Reddit Sans",
    "Reddit Sans Condensed",
    "Reem Kufi Fun",
    "Reem Kufi Ink",
    "REM",
    "Rethink Sans",
    "Roboto Flex",
    "Roboto Serif",
    "Rubik 80s Fade",
    "Rubik Broken Fax",
    "Rubik Bubbles",
    "Rubik Burned",
    "Rubik Dirt",
    "Rubik Distressed",
    "Rubik Doodle Shadow",
    "Rubik Doodle Triangles",
    "Rubik Gemstones",
    "Rubik Glitch",
    "Rubik Glitch Pop",
    "Rubik Iso",
    "Rubik Lines",
    "Rubik Maps",
    "Rubik Marker Hatch",
    "Rubik Maze",
    "Rubik Microbe",
    "Rubik Moonrocks",
    "Rubik Pixels",
    "Rubik Puddles",
    "Rubik Scribble",
    "Rubik Spray Paint",
    "Rubik Storm",
    "Rubik Vinyl",
    "Rubik Wet Paint",
    "Ruwudu",
    "SUSE",
    "SUSE Mono",
    "Sankofa Display",
    "Sansation",
    "Savate",
    "Schibsted Grotesk",
    "Sedan",
    "Sedan SC",
    "Send Flowers",
    "Shafarik",
    "Shantell Sans",
    "Siemreap",
    "Sigmar",
    "Silkscreen",
    "Sirivennela",
    "Sixtyfour",
    "Sixtyfour Convergence",
    "Slackside One",
    "Smooch Sans",
    "Sofia Sans",
    "Sofia Sans Condensed",
    "Sofia Sans Extra Condensed",
    "Sofia Sans Semi Condensed",
    "Solitreo",
    "Sometype Mono",
    "Sono",
    "Sour Gummy",
    "Source Serif 4",
    "Special Gothic",
    "Special Gothic Condensed One",
    "Special Gothic Expanded One",
    "Splash",
    "Spline Sans",
    "Spline Sans Mono",
    "Square Peg",
    "Story Script",
    "Suwannaphum",
    "TASA Explorer",
    "TASA Orbiter",
    "Tac One",
    "Tagesschrift",
    "Tai Heritage Pro",
    "Tapestry",
    "Taprom",
    "Teachers",
    "Tektur",
    "Texturina",
    "The Nautigal",
    "TikTok Sans",
    "Tilt Neon",
    "Tilt Prism",
    "Tilt Warp",
    "Tiny5",
    "Tiro Bangla",
    "Tiro Devanagari Hindi",
    "Tiro Devanagari Marathi",
    "Tiro Devanagari Sanskrit",
    "Tiro Gurmukhi",
    "Tiro Kannada",
    "Tiro Tamil",
    "Tiro Telugu",
    "Tirra",
    "Triodion",
    "Truculenta",
    "Tsukimi Rounded",
    "Tuffy",
    "Twinkle Star",
    "Ubuntu Sans",
    "Ubuntu Sans Mono",
    "Unbounded",
    "UoqMunThenKhung",
    "Updock",
    "Vazirmatn",
    "Vend Sans",
    "Victor Mono",
    "Vina Sans",
    "Vujahday Script",
    "WDXL Lubrifont JP N",
    "WDXL Lubrifont SC",
    "WDXL Lubrifont TC",
    "Water Brush",
    "Waterfall",
    "Wavefont",
    "Whisper",
    "Winky Rough",
    "Winky Sans",
    "Wittgenstein",
    "Wix Madefor Display",
    "Wix Madefor Text",
    "Workbench",
    "Yarndings 12",
    "Yarndings 12 Charted",
    "Yarndings 20",
    "Yarndings 20 Charted",
    "Young Serif",
    "Ysabeau",
    "Ysabeau Infant",
    "Ysabeau Office",
    "Ysabeau SC",
    "Zain",
    "Zalando Sans",
    "Zalando Sans Expanded",
    "Zalando Sans SemiExpanded",
    "Zen Dots",
]
