from ..DataModel import DataModel as DataModel
from dataclasses import dataclass
from strenum import StrEnum

class DepthFeatureKindEnum(StrEnum):
    Undefined = 'Undefined'
    Plug = 'Plug'
    Perforation = 'Perforation'

@dataclass
class DepthFeature(DataModel):
    stage_name: int = ...
    kind: DepthFeatureKindEnum = ...
    top_md: float = ...
    bottom_md: float = ...
    shot_density: int | None = ...
    shot_count: int | None = ...
    phasing: float | None = ...
    orientation: float | None = ...
