from ..DataModel import DataModel as DataModel
from dataclasses import dataclass

@dataclass
class Plug(DataModel):
    description: str | None = ...
    sequence_num: int = ...
    toe_md: float | None = ...
    heel_md: float = ...
