from ...datamodels.Helpers import DeprecatedFieldInfo as DeprecatedFieldInfo, MakeIsodateOptionalField as MakeIsodateOptionalField, deprecated_field as deprecated_field, with_field_deprecations as with_field_deprecations
from ...datamodels.completions.DepthFeature import DepthFeature as DepthFeature
from ...datamodels.completions.Plug import Plug as Plug
from ..DataModel import DataModel as DataModel
from .UserDefinedStageValue import UserDefinedStageValue as UserDefinedStageValue
from dataclasses import dataclass, field
from datetime import datetime

@dataclass
class Stage(DataModel):
    sequence_num: int = ...
    key: str | None = ...
    gap: bool = ...
    note: str | None = ...
    num_clusters: int | None = ...
    toe_plug: Plug | None = ...
    toe_md: float = ...
    heel_md: float = ...
    tvd_depth: float | None = ...
    user_param_values: list[float | None] = ...
    user_defined_stage_values: list[UserDefinedStageValue] | None = ...
    depth_features: list[DepthFeature] = field(default_factory=list[DepthFeature])
    proppant_weight: float | None = ...
    water_volume: float | None = ...
    slurry_rate: float | None = ...
    pressure: float | None = ...
    duration: float | None = ...
    start_date: datetime | None = ...
    bottom_pressure: float | None = ...
    breakdown_pressure: float | None = ...
    closure_pressure: float | None = ...
    avg_surface_pressure: float | None = ...
    max_surface_pressure: float | None = ...
    max_bottom_pressure: float | None = ...
    isip_pressure: float | None = ...
    closure_gradient: float | None = ...
    frac_gradient: float | None = ...
    slurry_volume: float | None = ...
    avg_proppant_conc: float | None = ...
    max_proppant_conc: float | None = ...
    acid: float | None = ...
    FR_fluid: float | None = ...
    FR_powder: float | None = ...
    biocide: float | None = ...
    clay_stabilizer: float | None = ...
    scale_inhibitor: float | None = ...
    water_salinity: float | None = ...
    time_to_max_injection_rate: float | None = ...
    plug_type: str | None = ...
    screened_out: bool = ...
    frac_hit: bool = ...
    frac_quality: float | None = ...
    frac_length_up: float | None = ...
    frac_length_down: float | None = ...
    frac_length_left: float | None = ...
    frac_length_right: float | None = ...
    frac_wing_angle: float | None = ...
    def copy_ids_from(self, source: DataModel): ...
