from dataclasses import dataclass
from dataclasses_json import DataClassJsonMixin

@dataclass
class UserDefinedStageValue(DataClassJsonMixin):
    dataclass_json_config = ...
    name: str = ...
    description: str = ...
    unit: str = ...
    value: float = ...
    string_value: str = ...
