from dataclasses import dataclass

@dataclass
class Conditioning:
    AmplClip: bool = ...
    AmplClipRangeMin: float | None = ...
    AmplClipRangeMax: float | None = ...
    AmplClipInclusiveNotExclusive: bool | None = ...
    MDClip: bool = ...
    MDClipRangeMin: float | None = ...
    MDClipRangeMax: float | None = ...
    MDClipInclusiveNotExclusive: bool | None = ...
    Despike: bool = ...
    VarianceThreshold: float | None = ...
    DespikeLen: int | None = ...
    Interpolate: bool = ...
    MaxGap: int | None = ...
    Smooth: bool = ...
    SmoothingLen: int | None = ...
    Normalize: bool = ...
    Bias: float | None = ...
    Scalar: float | None = ...
