from ..DataModel import DataModel as DataModel
from .Conditioning import Conditioning as Conditioning
from dataclasses import dataclass
from strenum import StrEnum

class CurveDefWellboreRoleEnum(StrEnum):
    TargetWellbore = 'TargetWellbore'
    TypeWellbore = 'TypeWellbore'

class CurveGroupRoleEnum(StrEnum):
    Image = 'Image'
    Litho = 'Litho'
    Splice = 'Splice'

@dataclass
class CurveDef(DataModel):
    well_name: str | None = ...
    well_id: int | None = ...
    wellbore_id: int | None = ...
    wellbore_role: CurveDefWellboreRoleEnum | None = ...
    well_log_id: int | None = ...
    curve_id: int | None = ...
    curve_group_id: int | None = ...
    role: CurveGroupRoleEnum | None = ...
    active: bool = ...
    conditioning: Conditioning | None = ...
