from ...datamodels.Helpers import DeprecatedFieldInfo as DeprecatedFieldInfo, MakeIsodateOptionalField as MakeIsodateOptionalField, deprecated_field as deprecated_field, with_field_deprecations as with_field_deprecations
from ...datamodels.geosteering.Blocks import Block as Block, Fault as Fault, Layer as Layer, Throw as Throw
from ..DataModel import DataModel as DataModel
from ..misc.permission import Editability as Editability, Visibility as Visibility
from .CurveDef import CurveDef as CurveDef
from .Horizon import GeosteerHorizonRole as GeosteerHorizonRole, Horizon as Horizon, TypewellHorizonDepth as TypewellHorizonDepth
from .Pick import Pick as Pick
from dataclasses import dataclass, field
from dataclasses_json import config
from datetime import datetime
from strenum import StrEnum
from typing import Callable

@dataclass
class Zone:
    top: Horizon
    bottom: Horizon | None

class AutoExtendMethod(StrEnum):
    LastStation = 'LastStation'
    HoleDepth = 'HoleDepth'

class InclinationType(StrEnum):
    MD = 'MD'
    VX = 'VX'
    THD = 'THD'

@dataclass
class Interpretation(DataModel):
    description: str | None = ...
    starred: bool = ...
    target_wellbore_id: int = ...
    target_wellbore_name: str | None = ...
    target_wellbore_number: str | None = ...
    target_formation_id: int = ...
    target_formation_name: str | None = ...
    target_formation_member_name: str | None = ...
    target_horizon_id: int | None = ...
    hang_horizon_id: int | None = ...
    target_top_horizon_id: int | None = ...
    target_base_horizon_id: int | None = ...
    zone_show_above_and_below: bool | None = ...
    zone_start_md: float | None = field(default=None, metadata=config(field_name='ZoneStartMD'))
    zone_end_md: float | None = field(default=None, metadata=config(field_name='ZoneEndMD'))
    owner_name: str | None = ...
    owner_id: int = ...
    owner_company_name: str = ...
    visibility: Visibility = ...
    editability: Editability = ...
    thickness: float | None = ...
    auto_extend_method: AutoExtendMethod | None = ...
    auto_extend_last_block_dist: float | None = ...
    auto_extend_dip: InclinationType | None = ...
    coordinate_system: str | None = ...
    picks: list[Pick] = field(default_factory=list[Pick])
    curve_defs: list[CurveDef] = field(default_factory=list[CurveDef])
    horizons: list[Horizon] = field(default_factory=list[Horizon])
    typewell_horizon_depths: list[TypewellHorizonDepth] | None = field(default_factory=list[TypewellHorizonDepth])
    def copy_ids_from(self, source: DataModel): ...
    @property
    def valid(self) -> bool: ...
    def get_zone(self) -> Zone | None: ...
    def make_contiguous_blocks(self) -> list[Block]: ...
    def make_blocks_and_faults(self, interval: float | None = None, *, keepHz: Callable[[Horizon], bool] | None = None) -> tuple[list[Block], list[Fault]]: ...
    def make_evenly_spaced_picks(self, interval: float, first_md: float | None = None, last_md: float | None = None) -> list[Pick]: ...

@dataclass
class InterpretationEntry(DataModel):
    description: str | None = ...
    starred: bool = ...
    owner_company_name: str = ...
    visibility: Visibility = ...
    editability: Editability = ...
    last_modified_by_name: str = ...
    last_modified_date: datetime | None = ...
    @property
    def interpretation(self) -> Interpretation: ...
