"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .matchtype import MatchType
from syllable_sdk.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class PronunciationOverrideTypedDict(TypedDict):
    r"""A single text replacement rule."""

    text: str
    replacement: str
    languages: NotRequired[List[str]]
    provider: NotRequired[str]
    voice: NotRequired[str]
    match_type: NotRequired[MatchType]
    r"""Matching strategy for override text."""
    match_options: NotRequired[List[str]]
    enabled: NotRequired[bool]
    notes: NotRequired[str]


class PronunciationOverride(BaseModel):
    r"""A single text replacement rule."""

    text: str

    replacement: str

    languages: Optional[List[str]] = None

    provider: Optional[str] = ""

    voice: Optional[str] = ""

    match_type: Optional[MatchType] = None
    r"""Matching strategy for override text."""

    match_options: Optional[List[str]] = None

    enabled: Optional[bool] = True

    notes: Optional[str] = ""
