who = ["man", "woman"]
skintones = ["Hex Color #f6ede4", "Hex Color #f3e7db", "Hex Color #f7ead0", "Hex Color #eadaba", "Hex Color #d7bd96",
    "Hex Color #a07e56", "Hex Color #825c43", "Hex Color #604134", "Hex Color #3a312a", "Hex Color #292420"]
hairstyles = [
    "short straight 1A", "medium straight 1A", "long straight 1A",
    "short straight 1B", "medium straight 1B", "long straight 1B",
    "short straight 1C", "medium straight 1C", "long straight 1C",
    "short wavy 2A", "medium wavy 2A", "long wavy 2A",
    "short wavy 2B", "medium wavy 2B", "long wavy 2B",
    "short wavy 2C", "medium wavy 2C", "long wavy 2C",
    "short curly 3A", "medium curly 3A", "long curly 3A",
    "short curly 3B", "medium curly 3B", "long curly 3B",
    "short curly 3C", "medium curly 3C", "long curly 3C",
    "short coily 4A", "medium coily 4A", "long coily 4A",
    "short coily 4B", "medium coily 4B", "long coily 4B",
    "short coily 4C", "medium coily 4C", "long coily 4C",
]
poses = [
    "Is standing with his left hand on his hip",
    "Is standing with his legs crossed and looking to the left",
    "Is standing with his left hand on his hip and pointing with his right hand",
    "Is standing and checking something on his phone in his right hand",
    "Is standing with his arms and legs crossed, looking to the right",
    "Is standing and talking on the phone in his right hand",
    "Is standing with his hands on his hips",
    "Is standing and talking on the phone in his right hand",
    "Is standing with his legs crossed, holding his hands behind his back, hips pose",
    "Is standing and holding his head with his right hand",
    "Is standing and holding his head with both hands, holding head pose",
    "Is standing, looking down and holding his head with both hands",
    "Is confused, standing and holding his head with his right hand",
    "Is running, athlete pose",
    "Is stretching, doing yoga, looking to the left",
    "Is standing and stretching his legs, looking slightly to the left",
    "Is standing and stretching, athlete pose",
    "Basketball player is standing, holding a ball in his right hand",
    "Is standing and holding a book in his right hand",
    "Is doing yoga, doing a half squat yoga pose",
    "Athletic handball player is running, holding a ball in his right hand",
    "Is standing with her arms crossed, low angle pose reference",
    "Is walking casually, low angle pose reference",
    "Is standing casually, his legs are crossed, his right hand is in his pocket",
    "Superhero flexing",
    "Is running fast, looking slightly to the left, low angle pose reference",
    "Bodybuilder pose, is standing, showing his muscles and looking down",
    "Is standing, looking up, her hands are on her hips",
    "Is surprised and walks backwards, looks forward, raises his hands slightly",
    "Is standing casually, his right hand is on his hip, looking slightly to the right",
    "Is surprised and holding his head with both hands",
    "Is standing, her arms and legs are crossed, female standing high angle pose reference",
    "Is surprised and almost falls back, looks to the left and raises his hands",
    "Is standing, his hands are on his hips, looking down",
    "Is surprised and steps back, holding her face with both hands",
    "Is walking casually, female high angle pose reference",
    "Is surprised, looks forward and raises her right hand to her mouth",
    "Is surprised, shocked, looking forward and stepping back",
    "Is standing and holding his head with both hands",
    "Is standing with his right hand on hip and showing peace sign with his left hand",
    "Is walking gracefully on tiptoe, ballerina dancing pose, dancing ballerina drawing reference",
    "Is dancing, gracefully spinning and raising her hands, dancing ballerina drawing reference",
    "Is dancing, jumping gracefully, looking to the right, ballerina dancing pose",
    "Is leaning forward and showing peace sign with her left hand",
    "Is dancing, gracefully leaning back, looking up, dancing ballerina drawing reference",
    "Happy person is jumping and showing peace sign with both hands",
    "Is standing on tiptoe, looking to the right, dancing with her hands",
    "Is running, looking to the left, running away from something",
    "Is standing, his right hand is on his hip, waving with his left hand",
    "Happy person is jumping and waving, saying 'hi' to someone who is far away",
    "Is standing and showing 'perfect' with her both hands",
    "Is greeting someone, putting her hands together and bowing slightly",
    "Is greeting someone, waving with her right hand and looking to the right",
    "Is standing and showing 'peace' sign with her both hands",
    "Is greeting someone, waving with his right hand and looking to the right",
    "Is standing with her palms together in front of her chest, showing respect",
    "Is standing, clenching her right hand into a fist, raising her left hand",
    "Stands on heels with her weight on her right leg",
    "Is standing, right hand on her hip, left hand pointing thumb down",
    "Excited person is jumping, raising her hands high, excited female pose",
    "Excited person is standing and folding her hands",
    "Excited person is standing and holding her head with both hands",
    "Is standing confidently, her arms are crossed, looking slightly to the left",
    "Excited person is standing, clenching his fists and looking down",
    "Excited person is standing, clenching his fists and raising his left hand",
    "Handball player is dribbling, running with the handball and looking ahead",
    "Is standing casually and holding a glass in her left hand",
    "Is walking elegantly, drawing female pose reference",
    "Is standing casually, her arms are crossed, she is looking to the right",
    "Is standing and blowing a kiss with her right hand, drawing female pose",
    "Is standing confidently and showing her arm muscles",
    "Is standing and showing thumbs up with both hands",
    "Is standing and waving with her right hand, drawing female pose",
    "Is standing and making a peace sign with her right hand",
    "Is standing and doing rock sign with both hands, rocker hand gesture pose",
    "Is standing and making a 'victory' sign with both hands",
    "Is standing and making a 'high five' sign with both hands",
    "Is imitating a phone with his left hand, saying 'call me', phone finger pose",
    "Is standing and making a heart with her hands",
    "Is angry, clenching her right hand into a fist and raising her left hand",
    "Is angry, clenching his right hand into a fist and pointing with his left hand",
    "Is holding his head in a sad pose",
    "Is standing with her legs crossed, her left hand is in her pocket and looking to the left pose",
    "Is standing with crossed legs and crossed arms, looking to the right",
    "Confident person is standing with his legs crossed and looking to the left",
    "Offended person is standing with his legs and arms crossed and looking forward",
    "Is standing with his legs crossed, looking to the right and waving, saying 'hi'",
    "Proud person is standing with his legs crossed, his hands are on hips",
    "Is standing and holding a wine glass in her left hand, holding wine glass reference",
    "Is standing casually and holding a wine glass in his right hand",
    "Is standing and blowing a kiss with both hands",
    "Is looking at the sky dramatic pose",
    "Is standing, curious about something, holding her chin",
    "Is standing and showing thumbs up with both hands",
    "Is standing, folding her hands, praying and looking up",
    "Injured person is walking, holding his stomach with his right hand and limping",
    "Is standing confidently and holding sunglasses in his right hand",
    "Is standing, holding a basketball and searching where to pass it",
    "Is ready to fight karate pose",
    "With her right leg in the air karate pose"
    ]


