from ..fodot.theory import Inferenceable
from ..fodot.structure import GlobModel, Structure, Model, ExtTypeElement
from ..fodot.vocabulary import ExtPfunc
from ..fodot.collections import Set
from typing import Self
from ._pure import *

class Z3GlobModelIterator:
    def __iter__(self) -> Self: ...
    def __next__(self) -> GlobModel: ...

class Z3ModelIterator:
    def __iter__(self) -> Self: ...
    def __next__(self) -> Model: ...
    def enable_skip_infinite(self) -> Self: ...
    def disable_skip_infinite(self) -> Self: ...
    def skip_infinite(self, skip: bool) -> Self: ...

class Z3Solver:
    def __init__(self, inferenceable: Inferenceable): ...
    def inferenceable(self) -> Inferenceable: ...
    def check(self) -> SatResult: ...
    def get_model(self) -> GlobModel | None: ...
    def next_model(self) -> None: ...
    def propagate(self) -> Structure | None: ...
    def propagate_diff(self) -> Structure | None: ...
    def iter_glob_models(self) -> Z3GlobModelIterator: ...
    def iter_models(self) -> Z3ModelIterator: ...
    def get_range(self, pfunc: ExtPfunc, args: tuple[ExtTypeElement]) -> None | Set: ...
