"""Definition of constants."""

DEFAULT_SCHEMA_VERSION = "0.4.0"

# SCHEMA_TYPES
FLOAT_SCHEMA = "float"
MRV_SCHEMA = "MRV"
PLATFORM_SCHEMA = "platform"
RBR_SCHEMA = "RBR"
SBE_SCHEMA = "SBE"
SENSOR_SCHEMA = "sensor"
TRIOS_SCHEMA = "TRIOS"
VENDORS_SCHEMA = "vendors"

SCHEMA_TYPES = [
    FLOAT_SCHEMA,
    MRV_SCHEMA,
    PLATFORM_SCHEMA,
    RBR_SCHEMA,
    SBE_SCHEMA,
    SENSOR_SCHEMA,
    TRIOS_SCHEMA,
    VENDORS_SCHEMA,
]
