
from enum import Flag


class DownloadMode(Flag):
    NULL = 0
    SAVE_PICTURES = 1
    SAVE_TO_FOLDER = 10
    SAVE_PSD = 100
    SAVE_TO_ARCHIVE = 1000
    MERGE_PICTURES = 10000
    SAVE_PDF = 100000

    STANDARD = SAVE_PICTURES | SAVE_TO_FOLDER
    SAVE_PSD_PICTURE_TO_ARCHIVE = SAVE_PSD | SAVE_PICTURES | SAVE_TO_ARCHIVE