"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .brandcolorvalidationerror import (
    BrandColorValidationError,
    BrandColorValidationErrorTypedDict,
)
from moovio_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ColorsValidationErrorTypedDict(TypedDict):
    light: NotRequired[BrandColorValidationErrorTypedDict]
    dark: NotRequired[BrandColorValidationErrorTypedDict]


class ColorsValidationError(BaseModel):
    light: Optional[BrandColorValidationError] = None

    dark: Optional[BrandColorValidationError] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["light", "dark"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
