"""
    EMIL GdvService

    The EMIL GdvService API description  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: kontakt@emil.de
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import eis.gdv
from eis.gdv.model.message_class import MessageClass
globals()['MessageClass'] = MessageClass
from eis.gdv.model.list_all_messages_response_class import ListAllMessagesResponseClass


class TestListAllMessagesResponseClass(unittest.TestCase):
    """ListAllMessagesResponseClass unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListAllMessagesResponseClass(self):
        """Test ListAllMessagesResponseClass"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListAllMessagesResponseClass()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
