from __future__ import annotations

RESERVED = {
    "check",
    "ui",
    "flow",
    "help",
    "format",
    "fmt",
    "lint",
    "actions",
    "studio",
    "persist",
    "data",
    "graph",
    "exports",
    "test",
    "pkg",
    "deps",
    "tools",
    "packs",
    "pack",
    "build",
    "ship",
    "promote",
    "where",
    "status",
    "proof",
    "memory",
    "verify",
    "release-check",
    "expr-check",
    "eval",
    "secrets",
    "observe",
    "explain",
    "why",
    "how",
    "with",
    "what",
    "when",
    "see",
    "fix",
    "exists",
    "kit",
    "editor",
    "run",
    "registry",
    "discover",
    "readability",
    "pattern",
    "migrate",
    "version",
}

ROOT_APP_COMMANDS = {"check", "ui", "actions", "studio", "fmt", "format", "lint", "graph", "exports", "data", "persist"}
