# coding: utf-8

"""
    LLM Cost Monitor API

    Open-source LLM cost observability platform API. Track, aggregate, and analyze LLM usage costs across your applications. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from llm_cost_monitor.api.metrics_api import MetricsApi


class TestMetricsApi(unittest.TestCase):
    """MetricsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MetricsApi()

    def tearDown(self) -> None:
        pass

    def test_get_metrics(self) -> None:
        """Test case for get_metrics

        Get aggregated metrics
        """
        pass

    def test_get_usage(self) -> None:
        """Test case for get_usage

        Get usage summary
        """
        pass


if __name__ == '__main__':
    unittest.main()
