"""LLM Council - Multi-persona AI deliberation and consensus tool."""

__version__ = "0.1.4"

from .models import (
    Persona,
    PersonaProviderConfig,
    Message,
    Vote,
    RoundResult,
    CouncilSession,
    ConsensusType,
    VoteChoice,
)
from .assertions import assert_council, CouncilAssertions, AssertionReport, ValidationResult
from .contracts import (
    INTERFACE_VERSION,
    ErrorCode,
    ErrorSeverity,
    InterfaceError,
    InterfaceContract,
    ContractRegistry,
    ErrorHandler,
    FailureRecovery,
    RecoveryAction,
    RecoveryResult,
    get_contract_registry,
    get_error_handler,
    get_interface_version,
)
from .templates import (
    PersonaTemplate,
    PersonaTemplateLibrary,
    TemplateLoader,
    get_template_library,
    create_persona_from_template,
    list_builtin_templates,
    get_builtin_template,
)
from .persistence import (
    RetentionPolicy,
    StoredSession,
    SessionStorage,
    SQLiteStorage,
    SessionExporter,
    SessionManager,
    get_session_manager,
    save_session,
    load_session,
)
from .metrics import (
    MetricType,
    MetricPoint,
    AggregatedMetric,
    MetricsCollector,
    MetricsAggregator,
    Timer,
    SessionMetrics,
    MetricsReporter,
    get_metrics_collector,
    get_metrics_reporter,
    time_operation,
    record_latency,
    record_tokens,
    record_session_metrics,
    get_metrics_summary,
)
from .testing import (
    TestStatus,
    TestCase,
    TestResult,
    VarianceMetric,
    TestSuite,
    TestExecutor,
    VarianceTracker,
    TestReporter,
    create_test_suite,
    create_provider as create_test_provider,
    create_test_case,
    get_standard_test_suite,
)
from .schemas import (
    DiscussionRequestSchema,
    PersonaTemplateSchema,
    SessionOutputSchema,
    SchemaValidationError,
    ValidationErrors,
    ValidationErrorCode,
    validate_discussion_request,
    validate_persona_template,
    validate_session_output,
    SchemaValidator,
)
from .providers import create_provider, LiteLLMProvider, ProviderConfig, ProviderRegistry
from .personas import PersonaManager
from .council import CouncilEngine
from .config import (
    ConfigManager,
    ConfigSchema,
    ProviderSettings,
    GenerationSettings,
    CouncilSettings,
    PersistenceSettings,
    ResolvedConfig,
    get_config_manager,
    load_config,
    save_config,
    get_default_config,
    get_user_config_path,
    get_project_config_path,
)

__all__ = [
    # Models
    "Persona",
    "PersonaProviderConfig",
    "Message",
    "Vote",
    "RoundResult",
    "CouncilSession",
    "ConsensusType",
    "VoteChoice",
    # Assertions (US-01)
    "assert_council",
    "CouncilAssertions",
    "AssertionReport",
    "ValidationResult",
    # Schemas (US-02)
    "DiscussionRequestSchema",
    "PersonaTemplateSchema",
    "SessionOutputSchema",
    "SchemaValidationError",
    "ValidationErrors",
    "ValidationErrorCode",
    "validate_discussion_request",
    "validate_persona_template",
    "validate_session_output",
    "SchemaValidator",
    # Contracts (US-03)
    "INTERFACE_VERSION",
    "ErrorCode",
    "ErrorSeverity",
    "InterfaceError",
    "InterfaceContract",
    "ContractRegistry",
    "ErrorHandler",
    "FailureRecovery",
    "RecoveryAction",
    "RecoveryResult",
    "get_contract_registry",
    "get_error_handler",
    "get_interface_version",
    # Templates (US-04)
    "PersonaTemplate",
    "PersonaTemplateLibrary",
    "TemplateLoader",
    "get_template_library",
    "create_persona_from_template",
    "list_builtin_templates",
    "get_builtin_template",
    # Persistence (US-05)
    "RetentionPolicy",
    "StoredSession",
    "SessionStorage",
    "SQLiteStorage",
    "SessionExporter",
    "SessionManager",
    "get_session_manager",
    "save_session",
    "load_session",
    # Metrics (US-06)
    "MetricType",
    "MetricPoint",
    "AggregatedMetric",
    "MetricsCollector",
    "MetricsAggregator",
    "Timer",
    "SessionMetrics",
    "MetricsReporter",
    "get_metrics_collector",
    "get_metrics_reporter",
    "time_operation",
    "record_latency",
    "record_tokens",
    "record_session_metrics",
    "get_metrics_summary",
    # Testing (US-07)
    "TestStatus",
    "TestCase",
    "TestResult",
    "VarianceMetric",
    "TestSuite",
    "TestExecutor",
    "VarianceTracker",
    "TestReporter",
    "create_test_suite",
    "create_test_provider",
    "create_test_case",
    "get_standard_test_suite",
    # Providers
    "create_provider",
    "LiteLLMProvider",
    "ProviderConfig",
    "ProviderRegistry",
    # Personas
    "PersonaManager",
    # Council
    "CouncilEngine",
    # Config (US-CONFIG)
    "ConfigManager",
    "ConfigSchema",
    "ProviderSettings",
    "GenerationSettings",
    "CouncilSettings",
    "PersistenceSettings",
    "ResolvedConfig",
    "get_config_manager",
    "load_config",
    "save_config",
    "get_default_config",
    "get_user_config_path",
    "get_project_config_path",
]
