# -*- coding: utf-8 -*-
"""pycdp 类型存根文件"""
from typing import Any, Dict, Optional


class CDP:
    """独立的 CDP 客户端"""
    
    def __init__(self, port: int = 9222) -> None: ...
    
    @property
    def port(self) -> int: ...
    
    def run(self, js: str, wait: bool = False) -> Any:
        """执行JS代码"""
        ...
    
    def request(self, url: str, method: str = 'GET', body: Optional[Dict] = None, headers: Optional[Dict] = None, token_key: Optional[str] = None, extra: Optional[Dict] = None) -> Dict[str, Any]:
        """发送请求（绕过反爬）"""
        ...
    
    def get(self, url: str, **kw) -> Dict[str, Any]: ...
    def post(self, url: str, body: Optional[Dict] = None, **kw) -> Dict[str, Any]: ...
    def put(self, url: str, body: Optional[Dict] = None, **kw) -> Dict[str, Any]: ...
    def delete(self, url: str, **kw) -> Dict[str, Any]: ...
    def storage(self, key: str, value: Optional[str] = None, storage: str = 'localStorage') -> Optional[str]: ...
    def cookies(self, name: Optional[str] = None) -> Optional[str]: ...
    def close(self) -> None: ...


class Chromium:
    """DrissionPage 增强版，集成 CDP 功能"""
    
    def __init__(self, addr_or_opts: Any = None, cdp: Optional[CDP] = None, **kwargs) -> None: ...
    
    @property
    def cdp(self) -> CDP:
        """获取 CDP 实例"""
        ...
    
    # Tab 代理方法
    def get(self, url: str, **kwargs) -> Any: ...
    
    @property
    def wait(self) -> Any: ...
    
    def ele(self, *args, **kwargs) -> Any: ...
    def eles(self, *args, **kwargs) -> Any: ...
    
    @property
    def url(self) -> str: ...
    
    @property
    def html(self) -> str: ...
    
    @property
    def latest_tab(self) -> Any: ...
    
    def new_tab(self, url: Optional[str] = None, **kwargs) -> Any: ...
    def get_tab(self, **kwargs) -> Any: ...