parent_dependent_type_dict = {
    ("cmd_sqrt",  ("symb", "[")):  "opn_degr",
    ("opn_degr",  ("symb", "]")):  "cls_degr",

    ("cmd_sbstk", ("symb", "{")):  "opn_stkln",
    ("opn_stkln", ("symb", "}")):  "cls_stkln",
    ("stk_lbrk",  ("symb", "}")):  "cls_stkln",

    ("opn_stkln", ("cmnd", "\\")): "stk_lbrk",
    ("stk_lbrk",  ("cmnd", "\\")): "stk_lbrk",
    ("opn_stkln", ("cmnd", "newline")): "stk_lbrk",
    ("stk_lbrk",  ("cmnd", "newline")): "stk_lbrk",

    ("cmd_bgin",  ("symb", "{")):  "opn_envn",
    ("cmd_end",   ("symb", "{")):  "opn_envn",
    ("opn_envn",  ("symb", "}")):  "cls_envn",

    ("cmd_text",  ("symb", "{")):  "opn_text",
    ("opn_text",  ("symb", "}")):  "cls_text",
    ("opn_text",  ("symb", " ")):  "txt_leaf",

    ("opn_dllr",  ("symb", "$")):  "cls_dllr",
    ("opn_ddlr",  ("symb", "$$")): "cls_ddlr",
    ("cmd_lbrk",  ("symb", "$")):  "cls_dllr",
    ("cmd_lbrk",  ("symb", "$$")): "cls_ddlr",
}

type_dependent_type_dict = {
    ("opn_envn", "symb"): "txt_info",
    ("opn_envn", "alph"): "txt_info",
    ("opn_envn", "numb"): "txt_info",
}

type_dict = {
    ("meta",     "start"): "opn_root", ("meta",     "end"): "cls_root",
    ("meta", "startline"): "opn_line", ("meta", "endline"): "cls_line",
    ("symb",         "^"): "sup_scrpt", ("symb",      "_"): "sub_scrpt",
    ("symb", "$"): "opn_dllr",  ("symb",  "$$"): "opn_ddlr",
    ("cmnd", "["): "opn_brak",  ("cmnd",  "]"): "cls_brak",
    ("cmnd", "("): "opn_pren",  ("cmnd",  ")"): "cls_pren",
    ("symb", "{"): "opn_brac",  ("symb",  "}"): "cls_brac",
    ("symb", " "): "txt_invs",

    ("cmnd",  "left"): "opn_dlim", ("cmnd", "right"): "cls_dlim",
    ("cmnd",  "bigl"): "big_dlim", ("cmnd",   "big"): "big_dlim",
    ("cmnd",  "bigr"): "big_dlim", ("cmnd",  "Bigl"): "big_dlim",
    ("cmnd",   "Big"): "big_dlim", ("cmnd",  "Bigr"): "big_dlim",
    ("cmnd", "biggl"): "big_dlim", ("cmnd",  "bigg"): "big_dlim",
    ("cmnd", "biggr"): "big_dlim", ("cmnd", "Biggl"): "big_dlim",
    ("cmnd",  "Bigg"): "big_dlim", ("cmnd", "Biggr"): "big_dlim",

    ("cmnd",  "sqrt"): "cmd_sqrt",

    ("cmnd",  "frac"): "cmd_frac", ("cmnd", "tfrac"): "cmd_frac",
    ("cmnd", "dfrac"): "cmd_frac", ("cmnd", "cfrac"): "cmd_frac",

    ("cmnd",   "sum"): "ctr_base", ("cmnd", "prod"): "ctr_base",
    ("cmnd",   "lim"): "ctr_base",

    ("cmnd", "binom"): "cmd_binom", ("cmnd", "dbinom"): "cmd_binom",

    ("cmnd",  "limits"): "cmd_lmts", ("cmnd",     "acute"): "cmd_acnt",
    ("cmnd",     "bar"): "cmd_acnt", ("cmnd",     "breve"): "cmd_acnt",
    ("cmnd",   "check"): "cmd_acnt", ("cmnd",      "ddot"): "cmd_acnt",
    ("cmnd",     "dot"): "cmd_acnt", ("cmnd",     "grave"): "cmd_acnt",
    ("cmnd",     "hat"): "cmd_acnt", ("cmnd",  "mathring"): "cmd_acnt",
    ("cmnd",   "tilde"): "cmd_acnt", ("cmnd",       "vec"): "cmd_acnt",
    ("cmnd", "widehat"): "cmd_acnt", ("cmnd", "widetilde"): "cmd_acnt",

    ("cmnd",  "mathrm"): "cmd_font", ("cmnd",     "mathbf"): "cmd_font",
    ("cmnd",  "mathsf"): "cmd_font", ("cmnd",     "mathtt"): "cmd_font",
    ("cmnd",  "mathit"): "cmd_font", ("cmnd", "mathnormal"): "cmd_font",
    ("cmnd", "mathcal"): "cmd_font", ("cmnd",   "mathfrak"): "cmd_font",
    ("cmnd",  "mathbb"): "cmd_font", ("cmnd",    "mathscr"): "cmd_font",

    ("cmnd", "text"): "cmd_text",

    ("cmnd", "substack"): "cmd_sbstk",
    ("cmnd",    "\\"): "cmd_lbrk", ("cmnd", "newline"): "cmd_lbrk",
    ("cmnd", "begin"): "cmd_bgin", ("cmnd",     "end"): "cmd_end",

    ("cmnd", "textstyle"): "cmd_styl",
    ("cmnd", "displaystyle"): "cmd_styl",
    ("cmnd", "scriptstyle"): "cmd_styl",
    ("cmnd", "scriptscriptstyle"): "cmd_styl",
}

self_dependent_type_dict = {
    "symb": "txt_leaf",
    "alph": "txt_leaf",
    "numb": "txt_leaf",
    "cmnd": "cmd_leaf",
}


# node_info( ("only/only_not", popable_by["node_type"])
#            (add_amount)
#            (can_add_to_nodes_tree, "err if/if_not", under[])
#            (can_be_children, can_break_parent, can_double_pop)
#            (token_depented_render, rendering_function)
# ) can double pop is a bit of a hack for cls_stkln and cmd_end
type_info_dict = {
    "opn_root":  ((True, ["cls_root",]),
                  (1,),
                  (True, True, []),
                  (False, False, False),
                  (False, "render_root")),
    "opn_brac":  ((True, ["cls_brac",]),
                  (1,),
                  (True, True, []),
                  (True, False, False),
                  (False, "render_concat")),
    "opn_degr":  ((True, ["cls_degr",]),
                  (1,),
                  (True, False, ["cmd_sqrt",]),
                  (True, False, False),
                  (False, "render_concat")),
    "opn_dlim":  ((True, ["cls_dlim",]),
                  (1,),
                  (True, True, []),
                  (True, False, False),
                  (False, "render_open_delimiter")),
    "cmd_sqrt":  ((False, ["opn_degr",]),
                  (1,),
                  (True, True, []),
                  (True, False, False),
                  (False, "render_square_root")),
    "cmd_frac":  ((False, []),
                  (2,),
                  (True, True, []),
                  (True, False, False),
                  (False, "render_fraction")),
    "cmd_binom": ((False, []),
                  (2,),
                  (True, True, []),
                  (True, False, False),
                  (False, "render_binomial")),
    "big_dlim":  ((False, []),
                  (1,),
                  (True, True, []),
                  (True, False, False),
                  (True, "render_big_delimiter")),
    "sup_scrpt": ((False, []),
                  (1,),
                  (True, True, []),
                  (True, False, False),
                  (False, "render_sup_script")),
    "sub_scrpt": ((False, []),
                  (1,),
                  (True, True, []),
                  (True, False, False),
                  (False, "render_sub_script")),
    "top_scrpt": ((False, []),
                  (1,),
                  (True, True, []),
                  (True, False, False),
                  (False, "render_top_script")),
    "btm_scrpt": ((False, []),
                  (1,),
                  (True, True, []),
                  (True, False, False),
                  (False, "render_bottom_script")),
    "cls_dlim":  ((False, []),
                  (1,),
                  (True, True, []),
                  (True, False, False),
                  (False, "render_close_delimiter")),
    "cmd_acnt":  ((False, []),
                  (1,),
                  (True, True, []),
                  (True, False, False),
                  (True, "render_accents")),
    "cmd_font":  ((False, []),
                  (1,),
                  (True, True, []),
                  (True, False, False),
                  (True, "render_font")),
    "cmd_lmts":  ((True, []),
                  (0,),
                  (True, True, []),
                  (True, False, False),
                  (False, )),
    "ctr_base":  ((True, []),
                  (0,),
                  (True, True, []),
                  (True, False, False),
                  (True, "render_leaf")),
    "txt_leaf":  ((True, []),
                  (0,),
                  (True, True, []),
                  (True, False, False),
                  (True, "render_leaf")),
    "txt_info":  ((True, []),
                  (0,),
                  (True, True, []),
                  (True, False, False),
                  (True, "render_text_info")),
    "txt_invs":  ((True, []),
                  (0,),
                  (False, True, []),
                  (False, False, False),
                  (False, )),
    "cmd_leaf":  ((True, []),
                  (0,),
                  (True, True, []),
                  (True, False, False),
                  (True, "render_leaf")),
    "cmd_styl":  ((True, []),
                  (0,),
                  (False, True, []),
                  (False, False, False),
                  (False, )),
    "cls_root":  ((True, []),
                  (0,),
                  (False, False, ["opn_root",]),
                  (False, False, False),
                  (False, )),
    "cls_brac":  ((True, []),
                  (0,),
                  (False, False, ["opn_brac",]),
                  (False, False, False),
                  (False, )),
    "cls_degr":  ((True, []),
                  (0,),
                  (False, False, ["opn_degr",]),
                  (False, False, False),
                  (False, )),
    "cls_line":  ((True, []),
                  (0,),
                  (False, False, ["opn_line", "cmd_lbrk",]),
                  (False, False, False),
                  (False, )),
    "cls_brak":  ((True, []),
                  (0,),
                  (False, False, ["opn_brak", "cmd_lbrk",]),
                  (False, False, False),
                  (False, )),
    "cls_pren":  ((True, []),
                  (0,),
                  (False, False, ["opn_pren", "cmd_lbrk",]),
                  (False, False, False),
                  (False, )),
    "cls_dllr":  ((True, []),
                  (0,),
                  (False, False, ["opn_dllr", "cmd_lbrk",]),
                  (False, False, False),
                  (False, )),
    "cls_ddlr":  ((True, []),
                  (0,),
                  (False, False, ["opn_ddlr", "cmd_lbrk",]),
                  (False, True, False),
                  (False, )),
    "cmd_end":   ((False, []),
                  (1,),
                  (True, False, ["cmd_bgin", "cmd_lbrk",]),
                  (False, True, False),
                  (False, "render_end")),
    "cls_stkln": ((True, []),
                  (0,),
                  (False, False, ["opn_stkln", "stk_lbrk",]),
                  (False, True, True),
                  (False, )),
    "cls_envn":  ((True, []),
                  (0,),
                  (False, False, ["opn_envn",]),
                  (False, False, False),
                  (False, )),
    "cls_text":  ((True, []),
                  (0,),
                  (False, False, ["opn_text",]),
                  (False, False, False),
                  (False, )),
    "opn_line":  ((True, ["cls_line", "cmd_lbrk",]),
                  (1,),
                  (True, False, ["opn_root",]),
                  (True, False, False),
                  (False, "render_concat_line_no_align_amp")),
    "opn_brak":  ((True, ["cls_brak", "cmd_lbrk",]),
                  (1,),
                  (True, False, ["opn_root",]),
                  (True, False, False),
                  (False, "render_concat_line_no_align_amp")),
    "opn_pren":  ((True, ["cls_pren", "cmd_lbrk",]),
                  (1,),
                  (True, False, ["opn_root",]),
                  (True, False, False),
                  (False, "render_concat_line_no_align_amp")),
    "opn_dllr":  ((True, ["cls_dllr", "cmd_lbrk",]),
                  (1,),
                  (True, False, ["opn_root",]),
                  (True, False, False),
                  (False, "render_concat_line_no_align_amp")),
    "opn_ddlr":  ((True, ["cls_ddlr", "cmd_lbrk",]),
                  (1,),
                  (True, False, ["opn_root",]),
                  (True, False, False),
                  (False, "render_concat_line_no_align_amp")),
    "cmd_bgin":  ((True, ["cmd_end", "cmd_lbrk",]),
                  (1,),
                  (True, False, ["opn_root",]),
                  (True, False, False),
                  (False, "render_begin")),
    "stk_lbrk":  ((True, ["cls_stkln", "stk_lbrk",]),
                  (1,),
                  (True, False, ["opn_stkln", "stk_lbrk",]),
                  (True, True, False),
                  (False, "render_concat_line_no_align_amp")),
    "opn_stkln": ((True, ["cls_stkln", "stk_lbrk",]),
                  (1,),
                  (True, False, ["cmd_sbstk",]),
                  (True, False, False),
                  (False, "render_concat_line_no_align_amp")),
    "opn_envn":  ((True, ["cls_envn",]),
                  (1,),
                  (True, False, ["cmd_bgin", "cmd_end",]),
                  (True, False, False),
                  (False, "render_concat")),
    "opn_text":  ((True, ["cls_text",]),
                  (1,),
                  (True, False, ["cmd_text",]),
                  (True, False, False),
                  (False, "render_concat")),
    "cmd_text":  ((False, []),
                  (1,),
                  (True, True, []),
                  (True, False, False),
                  (True, "render_font")),
    "cmd_sbstk": ((True, ["cls_stkln",]),
                  (1,),
                  (True, True, []),
                  (True, False, False),
                  (False, "render_substack")),
    "cmd_lbrk":  ((True, ["cmd_lbrk", "cls_line", "cls_brak", "cls_pren",
                          "cls_dllr", "cls_ddlr", "cmd_end",]),
                  (1,),
                  (True, False, ["cmd_lbrk", "opn_line", "opn_brak",
                                 "opn_pren", "opn_dllr", "opn_ddlr",
                                 "cmd_bgin",]),
                  (True, True, False),
                  (False, "render_concat_line_align_amp")),
}
