"""
EIA Band Plot Package
=====================

This package provides a convenient function for generating
`5‑year band` plots similar to those used by the U.S. Energy
Information Administration (EIA).  These plots visualize the
historical range, average, and current/prior year values for a
time series, making it easy to see how recent data compare with
the last five years of history.

The primary entry point is :func:`~analysis3054.five_year_plot`.

Example
-------
.. code-block:: python

    import pandas as pd
    from analysis3054 import five_year_plot

    # Suppose `df` has a ``date`` column and one or more value columns
    fig = five_year_plot(date=df['date'], df=df)
    fig.show()
"""

from .plot import five_year_plot
from .ml import ml_forecast, ForecastResult
from .predict import monthly_predictor, MonthlyPredictionResult
from .forecast_engine import ForecastEngine, EngineForecastResult, build_default_engine
from .auto_ml_forecasting import (
    FeatureEngineeringResult,
    MLForecastResult,
    auto_generate_features,
    bayesian_ridge_covariate_forecast,
    catboost_covariate_forecast,
    chronos2_auto_covariate_forecast,
    elastic_net_covariate_forecast,
    fourier_ridge_seasonal_forecast,
    gradient_boosting_covariate_forecast,
    hist_gradient_direct_forecast,
    huber_covariate_forecast,
    lightgbm_covariate_forecast,
    pls_covariate_forecast,
    random_forest_covariate_forecast,
    ridge_covariate_forecast,
    stacked_meta_ensemble_forecast,
    svr_high_frequency_forecast,
    xgboost_covariate_forecast,
)
from .utils import (
    conditional_column_merge,
    conditional_row_merge,
    nearest_key_merge,
    coalesce_merge,
    rolling_fill,
    add_time_features,
    resample_time_series,
    winsorize_columns,
    add_lag_features,
    scale_columns,
    rolling_window_features,
    data_quality_report,
    get_padd,
    ensure_env_variables,
    configure_snowflake_connector,
    EnvVariableRequest,
    # split data into historical and future
    df_split,
)
from .emailer import EmailContent, send_email
from .inbox_cleaner import (
    ArchiveConfig,
    ConnectionConfig,
    InboxCleanReport,
    InboxCleaner,
    KeywordRule,
    RetentionPolicy,
    clean_inbox,
)
from .api_fetcher import fetch_apis_to_dataframe
from .holiday_calendars import available_holiday_calendars, get_holidays, get_holidays_between
from .holiday_lookup import (
    get_market_code,
    is_financial_holiday,
    is_holiday,
    is_platts_holiday,
    resolve_iso_code,
)

from .estimators import (
    bayesian_linear_estimator,
    BayesianLinearResult,
    gaussian_process_estimator,
    GaussianProcessResult,
    load_based_forecast,
    LoadForecastResult,
)
from .finance import (
    liquidity_adjusted_volatility,
    LiquidityAdjustedVolatilityResult,
    rolling_beta,
    RollingBetaResult,
)
from .visualization import (
    cumulative_return_plot,
    DrawdownResult,
    max_drawdown,
    forecast_plot,
    acf_pacf_plot,
)
from .stats import (
    cross_correlation_plot,
    partial_autocorrelation_plot,
    PCAResult,
    pca_decomposition,
    granger_causality_matrix,
)
from .forecasting import (
    arima_forecast,
    ArimaForecastResult,
    ets_forecast,
    EtsForecastResult,
    var_forecast,
    VarForecastResult,
    auto_arima_forecast,
    AutoArimaForecastResult,
    prophet_forecast,
    ProphetForecastResult,
    markov_switching_forecast,
    MarkovSwitchingForecastResult,
    unobserved_components_forecast,
    UnobservedComponentsForecastResult,
    dynamic_factor_forecast,
    DynamicFactorForecastResult,
    # Newly added advanced forecasting functions
    sarimax_forecast,
    SarimaxForecastResult,
    lstm_forecast,
    LstmForecastResult,
    garch_forecast,
    GarchForecastResult,
    vecm_forecast,
    VecmForecastResult,
    xgboost_forecast,
    XGBoostForecastResult,
    lightgbm_forecast,
    LightGBMForecastResult,
    theta_forecast,
    ThetaForecastResult,
    # Additional advanced forecasting methods
    elastic_net_forecast,
    ElasticNetForecastResult,
    svr_forecast,
    SvrForecastResult,
    tcn_forecast,
    TcnForecastResult,
    bats_forecast,
    BatsForecastResult,
    neuralprophet_forecast,
    NeuralProphetForecastResult,
    catboost_forecast,
    CatBoostForecastResult,
    knn_forecast,
    KnnForecastResult,
    transformer_forecast,
    TransformerForecastResult,
    # Intraday forecasting utilities
    intraday_load_burn_forecast,
    IntradayLoadBurnForecastResult,
    forecast_distillate_burn,
    ForecastDistillateBurnResult,
    intraday_gp_forecast,
    IntradayGpForecastResult,
    autogluon_tabular_burn_forecast,
    AutoGluonTabularForecastResult,
    autogluon_tabular_burn_classifier,
    AutoGluonTabularBurnClassifierResult,
    autogluon_timeseries_forecast,
    AutoGluonTimeSeriesForecastResult,
    autogluon_chronos2_forecast,
    AutoGluonChronos2ForecastResult,
    autogluon_timeseries_forecast_general,
    intraday_sarimax_forecast,
    IntradaySarimaxForecastResult,
    intraday_quantile_regression_forecast,
    IntradayQuantileRegressionForecastResult,
    forecast_major_burn_days,
    MajorBurnForecastResult,
    hierarchical_reconciled_burn_forecast,
    load_weather_interaction_forecast,
    hist_gradient_burn_forecast,
    HistGradientBurnForecastResult,
    # Chronos and Hugging Face models
    chronos2_univariate_forecast,
    chronos2_multivariate_forecast,
    chronos2_covariate_forecast,
    chronos2_weekly_implied_demand,
    forecast_trade_demand_blend,
    chronos2_forecast,
    chronos2_feature_generator,
    Chronos2ForecastResult,
    Chronos2FeatureBundle,
    Chronos2WeeklyDemandResult,
    TradeDemandForecastResult,
    chronos_bolt_forecast,
    ChronosBoltForecastResult,
    timesfm_forecast,
    TimesFmForecastResult,
    chronos_bolt_backtest,
    ChronosBoltBacktestResult,
    chronos_bolt_hyperparam_search,
    ChronosBoltHyperparamSearchResult,
    chronos_bolt_multi_target_forecast,
    ChronosBoltMultiTargetForecastResult,
    # New Chronos‑Bolt utilities
    chronos_bolt_quantile_forecast,
    ChronosBoltQuantileForecastResult,
    chronos_bolt_anomaly_detection,
    ChronosBoltAnomalyResult,
    chronos_bolt_impute_missing,
    ChronosBoltImputeResult,
    # Chronos‑2 advanced utilities
    chronos2_quantile_forecast,
    Chronos2QuantileForecastResult,
    chronos2_anomaly_detection,
    Chronos2AnomalyResult,
    chronos2_impute_missing,
    Chronos2ImputeResult,
    # Hybrid analytical utilities
    stl_fourier_kalman_forecast,
    regime_switching_forecast,
    quantile_projection_forecast,
    wavelet_multiresolution_forecast,
    latent_factor_state_forecast,
    adaptive_forecast,
    AdaptiveForecastResult,
    dynamic_forecast_blend,
    ForecastBlendResult,
    auto_error_correcting_forecast,
    ErrorCorrectedForecastResult,
    forecasting_playbook_examples,
    ForecastingExample,
)
from .advanced import (
    harmonic_forecast,
    HarmonicForecastResult,
    ewma_volatility,
    EwmaVolatilityResult,
    monte_carlo_simulation,
    MonteCarloSimulationResult,
    value_at_risk,
    VaRResult,
    cointegration_test,
    CointegrationTestResult,
    spectral_density_plot,
    wavelet_spectrogram,
    kalman_smoother,
    resample_time_series,
    stl_decompose_plot,
)
from .physics_forecaster import (
    WaveletDecompositionResult,
    multi_resolution_wavelet_decompose,
    ODEFunc,
    NeuralODEBlock,
    SobolevLoss,
    DMDResult,
    KoopmanSpectralDecomposer,
    rolling_hurst_router,
    plot_scalogram,
    plot_phase_portrait,
    plot_forecast_trajectory,
)

# Statistical functions
from .statistics import (
    hurst_exponent,
    dfa_exponent,
    rolling_sharpe_ratio,
    sample_entropy,
    higuchi_fractal_dimension,
    RollingSharpeResult,
    rolling_zscore,
    RollingZScoreResult,
    mann_kendall_test,
    MannKendallResult,
    bollinger_bands,
    BollingerBandsResult,
    stationarity_tests,
    StationarityTestResult,
    trend_seasonality_strength,
    TrendSeasonalityStrengthResult,
    box_cox_transform,
    BoxCoxTransformResult,
    seasonal_adjust,
    SeasonalAdjustmentResult,
)

# Regression and correlation utilities
from .regression import (
    ols_regression,
    RegressionResult,
    rolling_correlation,
    RollingCorrelationResult,
    cusum_olsresid_test,
    CusumTestResult,
)
from .ensembles import model_leaderboard, simple_ensemble
from .refined_fuels_api import RefinedFuelsUSMDClient, request_access_token
from .la_refinery import (
    LA_refinery,
    ScraperError,
    fetch_la_refinery_data_seleniumbase,
    load_la_refinery_cache,
    update_la_refinery_cache,
)
from .tx_refineries import (
    TX_refineries,
    TX_refineries_gemini,
    TX_refineries_receipts_deliveries,
    TX_refineries_receipts_deliveries_gemini,
    TXRefineryError,
    TableParseError,
    build_tx_refineries_first_pages_pdf,
    build_tx_refineries_full_pages_pdf,
)
from .port_la import (
    fetch_port_la_teu_table,
    load_port_la_teu_cache,
    update_port_la_teu_cache,
)
from .port_long_beach import (
    fetch_port_long_beach_teu_table,
    load_port_long_beach_teu_cache,
    update_port_long_beach_teu_cache,
)
from .port_houston import (
    fetch_port_houston_pdf_url,
    fetch_port_houston_teu_table,
    load_port_houston_teu_cache,
    update_port_houston_teu_cache,
)
from .port_savannah import (
    fetch_port_savannah_pdf_url,
    fetch_port_savannah_teu_table,
    load_port_savannah_teu_cache,
    update_port_savannah_teu_cache,
)
from .port_ny import (
    fetch_port_ny_teu_table,
    load_port_ny_teu_cache,
    update_port_ny_teu_cache,
)
from .aar_rail_traffic import (
    AAR_RAILTRAFFIC_URL_TEMPLATE,
    AAR_TABLE_FILES,
    build_aar_railtraffic_url,
    extract_aar_railtraffic_pdf,
    load_aar_railtraffic_tables,
    update_aar_railtraffic_tables,
)
from .eia_electricity import (
    fetch_eia860_zip_url,
    resolve_eia860_year,
    update_eia860_raw_csvs,
    update_eia923_raw_csvs,
)
from .spain_content import (
    fetch_spain_content_tables,
    update_spain_content_cache,
    load_spain_content_csv,
)
from .uk_oil_products import (
    fetch_uk_oil_products_links,
    fetch_uk_oil_products_tables,
    update_uk_oil_products_cache,
    load_uk_oil_products_csv,
)
from .fred_diesel import (
    build_fred_tickers,
    fetch_fred_data,
    resample_fred_data,
    update_fred_diesel_cache,
)
from .refinery_forecast import (
    build_refinery_forecast,
    build_refinery_product_forecast,
    ForecastOutputs,
)
from .eia_distillate import (
    fetch_distillate_product_supplied,
    DistillateSeries,
    EIADataError,
)
from .eia_wpsr import (
    WPSR_TABLE_URLS,
    DEFAULT_WPSR_TABLES,
    WPSRDataError,
    WPSRSnapshotRow,
    WPSRSnapshotTable,
    fetch_wpsr_tables_async,
    fetch_wpsr_tables,
    build_wpsr_snapshot_tables,
    render_wpsr_snapshot,
    create_wpsr_snapshot,
)
from .kayross import (
    load_kayross_us,
    load_kayross_eu,
    load_dtn_data,
    load_dtn_padd_data,
    load_dtn_rack_data,
    process_consumption_data,
    process_dtn_metrics,
    prepare_seasonality_payload,
)
from .macro_dashboard import (
    MACRO_META,
    build_macro_focus_frames,
    build_macro_outputs,
    MacroOutputs,
)
from .plotly_assets import ensure_plotly_asset
from .cftc_disagg_dashboard import (
    resolve_latest_cftc_year,
    update_cftc_disagg_cache,
    build_cftc_disagg_dashboard_payload,
    build_cftc_disagg_dashboard,
    CFTC_DASHBOARD_HTML,
    CFTC_DASHBOARD_JSON,
    CFTC_FILTERED_CSV,
)

__all__ = [
    "five_year_plot",
    "ml_forecast",
    "ForecastResult",
    "ForecastEngine",
    "EngineForecastResult",
    "build_default_engine",
    "monthly_predictor",
    "MonthlyPredictionResult",
    "harmonic_forecast",
    "HarmonicForecastResult",
    "ewma_volatility",
    "EwmaVolatilityResult",
    "monte_carlo_simulation",
    "MonteCarloSimulationResult",
    "value_at_risk",
    "VaRResult",
    "cointegration_test",
    "CointegrationTestResult",
    "spectral_density_plot",
    "wavelet_spectrogram",
    "kalman_smoother",
    "resample_time_series",
    "stl_decompose_plot",
    "WaveletDecompositionResult",
    "multi_resolution_wavelet_decompose",
    "ODEFunc",
    "NeuralODEBlock",
    "SobolevLoss",
    "DMDResult",
    "KoopmanSpectralDecomposer",
    "rolling_hurst_router",
    "plot_scalogram",
    "plot_phase_portrait",
    "plot_forecast_trajectory",
    # data utilities
    "conditional_column_merge",
    "conditional_row_merge",
    "nearest_key_merge",
    "coalesce_merge",
    "rolling_fill",
    "send_email",
    "EmailContent",
    # advanced estimators
    "bayesian_linear_estimator",
    "BayesianLinearResult",
    "gaussian_process_estimator",
    "GaussianProcessResult",
    "load_based_forecast",
    "LoadForecastResult",
    # financial analytics
    "liquidity_adjusted_volatility",
    "LiquidityAdjustedVolatilityResult",
    "rolling_beta",
    "RollingBetaResult",
    # additional utilities and plotting
    "data_quality_report",
    "cumulative_return_plot",
    "DrawdownResult",
    "max_drawdown",
    "forecast_plot",
    "acf_pacf_plot",
    # statistical analysis
    "cross_correlation_plot",
    "partial_autocorrelation_plot",
    "PCAResult",
    "pca_decomposition",
    "granger_causality_matrix",
    # forecasting
    "arima_forecast",
    "ArimaForecastResult",
    "ets_forecast",
    "EtsForecastResult",
    "var_forecast",
    "VarForecastResult",
    "auto_arima_forecast",
    "AutoArimaForecastResult",
    "prophet_forecast",
    "ProphetForecastResult",
    "markov_switching_forecast",
    "MarkovSwitchingForecastResult",
    "unobserved_components_forecast",
    "UnobservedComponentsForecastResult",
    "dynamic_factor_forecast",
    "DynamicFactorForecastResult",
    "adaptive_forecast",
    "AdaptiveForecastResult",
    "dynamic_forecast_blend",
    "ForecastBlendResult",
    "auto_error_correcting_forecast",
    "ErrorCorrectedForecastResult",
    # Newly added advanced forecasting functions
    "sarimax_forecast",
    "SarimaxForecastResult",
    "lstm_forecast",
    "LstmForecastResult",
    "garch_forecast",
    "GarchForecastResult",
    "vecm_forecast",
    "VecmForecastResult",
    "xgboost_forecast",
    "XGBoostForecastResult",
    "lightgbm_forecast",
    "LightGBMForecastResult",
    # Auto ML covariate-aware helpers
    "MLForecastResult",
    "chronos2_auto_covariate_forecast",
    "gradient_boosting_covariate_forecast",
    "random_forest_covariate_forecast",
    "ridge_covariate_forecast",
    "elastic_net_covariate_forecast",
    "svr_high_frequency_forecast",
    "xgboost_covariate_forecast",
    "lightgbm_covariate_forecast",
    "catboost_covariate_forecast",
    "stacked_meta_ensemble_forecast",
    "theta_forecast",
    "ThetaForecastResult",
    # newly added advanced forecasting methods
    "elastic_net_forecast",
    "ElasticNetForecastResult",
    "svr_forecast",
    "SvrForecastResult",
    "tcn_forecast",
    "TcnForecastResult",
    "bats_forecast",
    "BatsForecastResult",
    "neuralprophet_forecast",
    "NeuralProphetForecastResult",
    "catboost_forecast",
    "CatBoostForecastResult",
    "knn_forecast",
    "KnnForecastResult",
    "transformer_forecast",
    "TransformerForecastResult",
    "wavelet_multiresolution_forecast",
    "latent_factor_state_forecast",
    "forecasting_playbook_examples",
    "ForecastingExample",
    # intraday forecasting
    "intraday_load_burn_forecast",
    "IntradayLoadBurnForecastResult",
    "forecast_distillate_burn",
    "ForecastDistillateBurnResult",
    "intraday_gp_forecast",
    "IntradayGpForecastResult",
    "autogluon_tabular_burn_forecast",
    "AutoGluonTabularForecastResult",
    "autogluon_timeseries_forecast",
    "AutoGluonTimeSeriesForecastResult",
    "autogluon_timeseries_forecast_general",
    "intraday_sarimax_forecast",
    "IntradaySarimaxForecastResult",
    "intraday_quantile_regression_forecast",
    "IntradayQuantileRegressionForecastResult",
    "autogluon_tabular_burn_classifier",
    "AutoGluonTabularBurnClassifierResult",
    "forecast_major_burn_days",
    "MajorBurnForecastResult",
    "hierarchical_reconciled_burn_forecast",
    "load_weather_interaction_forecast",
    "hist_gradient_burn_forecast",
    "HistGradientBurnForecastResult",
    # Chronos and Hugging Face models
    "chronos2_univariate_forecast",
    "chronos2_multivariate_forecast",
    "chronos2_covariate_forecast",
    "chronos2_weekly_implied_demand",
    "chronos2_forecast",
    "Chronos2ForecastResult",
    "Chronos2WeeklyDemandResult",
    "chronos_bolt_forecast",
    "ChronosBoltForecastResult",
    "chronos_bolt_backtest",
    "ChronosBoltBacktestResult",
    "chronos_bolt_hyperparam_search",
    "ChronosBoltHyperparamSearchResult",
    "chronos_bolt_multi_target_forecast",
    "ChronosBoltMultiTargetForecastResult",
    "timesfm_forecast",
    "TimesFmForecastResult",
    "hurst_exponent",
    "dfa_exponent",
    "rolling_sharpe_ratio",
    "RollingSharpeResult",
    "sample_entropy",
    "higuchi_fractal_dimension",
    "rolling_zscore",
    "RollingZScoreResult",
    "mann_kendall_test",
    "MannKendallResult",
    "bollinger_bands",
    "BollingerBandsResult",
    "stationarity_tests",
    "StationarityTestResult",
    "trend_seasonality_strength",
    "TrendSeasonalityStrengthResult",
    "box_cox_transform",
    "BoxCoxTransformResult",
    "seasonal_adjust",
    "SeasonalAdjustmentResult",
    # regression and correlation
    "ols_regression",
    "RegressionResult",
    "rolling_correlation",
    "RollingCorrelationResult",
    "cusum_olsresid_test",
    "CusumTestResult",
    "model_leaderboard",
    "simple_ensemble",
    "RefinedFuelsUSMDClient",
    "request_access_token",
    "LA_refinery",
    "ScraperError",
    "fetch_la_refinery_data_seleniumbase",
    "load_la_refinery_cache",
    "update_la_refinery_cache",
    "TX_refineries",
    "TX_refineries_gemini",
    "TX_refineries_receipts_deliveries",
    "TX_refineries_receipts_deliveries_gemini",
    "TXRefineryError",
    "TableParseError",
    "build_tx_refineries_first_pages_pdf",
    "build_tx_refineries_full_pages_pdf",
    "fetch_port_la_teu_table",
    "load_port_la_teu_cache",
    "update_port_la_teu_cache",
    "fetch_port_long_beach_teu_table",
    "load_port_long_beach_teu_cache",
    "update_port_long_beach_teu_cache",
    "fetch_port_houston_pdf_url",
    "fetch_port_houston_teu_table",
    "load_port_houston_teu_cache",
    "update_port_houston_teu_cache",
    "fetch_port_savannah_pdf_url",
    "fetch_port_savannah_teu_table",
    "load_port_savannah_teu_cache",
    "update_port_savannah_teu_cache",
    "fetch_port_ny_teu_table",
    "load_port_ny_teu_cache",
    "update_port_ny_teu_cache",
    "fetch_eia860_zip_url",
    "resolve_eia860_year",
    "update_eia860_raw_csvs",
    "update_eia923_raw_csvs",
    "fetch_spain_content_tables",
    "update_spain_content_cache",
    "load_spain_content_csv",
    "fetch_uk_oil_products_links",
    "fetch_uk_oil_products_tables",
    "update_uk_oil_products_cache",
    "load_uk_oil_products_csv",
    "build_fred_tickers",
    "fetch_fred_data",
    "resample_fred_data",
    "update_fred_diesel_cache",
    "resolve_latest_cftc_year",
    "update_cftc_disagg_cache",
    "build_cftc_disagg_dashboard_payload",
    "build_cftc_disagg_dashboard",
    "CFTC_DASHBOARD_HTML",
    "CFTC_DASHBOARD_JSON",
    "CFTC_FILTERED_CSV",
    "AAR_RAILTRAFFIC_URL_TEMPLATE",
    "AAR_TABLE_FILES",
    "build_aar_railtraffic_url",
    "extract_aar_railtraffic_pdf",
    "load_aar_railtraffic_tables",
    "update_aar_railtraffic_tables",
    "build_refinery_forecast",
    "build_refinery_product_forecast",
    "ForecastOutputs",
    "fetch_distillate_product_supplied",
    "DistillateSeries",
    "EIADataError",
    "WPSR_TABLE_URLS",
    "DEFAULT_WPSR_TABLES",
    "WPSRDataError",
    "WPSRSnapshotRow",
    "WPSRSnapshotTable",
    "fetch_wpsr_tables_async",
    "fetch_wpsr_tables",
    "build_wpsr_snapshot_tables",
    "render_wpsr_snapshot",
    "create_wpsr_snapshot",
    # Kayross
    "load_kayross_us",
    "load_kayross_eu",
    "load_dtn_data",
    "load_dtn_padd_data",
    "load_dtn_rack_data",
    "process_consumption_data",
    "process_dtn_metrics",
    "prepare_seasonality_payload",
    "MACRO_META",
    "build_macro_focus_frames",
    "build_macro_outputs",
    "MacroOutputs",
    "ensure_plotly_asset",
]
