class types:
    class set:
        USE_WHITELIST = "minecraft:serversettings/use_allowlist/set"
        WHITELIST_SET = "minecraft:allowlist/set"
        ADD_WHITELIST = "minecraft:allowlist/add"
        REMOVE_WHITELIST = "minecraft:allowlist/remove"
        WHITELIST_CLEAR = "minecraft:allowlist/clear"
        BANLIST_SET = "minecraft:bans/set"
        BAN_PLAYER = "minecraft:bans/add"
        UNBAN_PLAYER = "minecraft:bans/remove"
        BANLIST_CLEAR = "minecraft:bans/clear"
        IP_BANLIST_SET = "minecraft:ip_bans/set"
        IP_BAN_PLAYER = "minecraft:ip_bans/add"
        IP_UNBAN_PLAYER = "minecraft:ip_bans/remove"
        IP_BANLIST_CLEAR = "minecraft:ip_bans/clear"
        OPERATORS_CLEAR = "minecraft:operators/clear"
        OPERATORS_SET = "minecraft:operators/set"
        ADD_OPERATOR = "minecraft:operators/add"
        REMOVE_OPERATOR = "minecraft:operators/remove"
        SERVER_SAVE = "minecraft:server/save"
        SERVER_STOP = "minecraft:server/stop"
        AUTO_SAVE = "minecraft:serversettings/autosave/set"
        DIFFICULTY = "minecraft:serversettings/difficulty/set"
        PAUSE_WHEN_EMPTY_SECONDS = "minecraft:serversettings/pause_when_empty_seconds/set"
        MAX_PLAYERS = "minecraft:serversettings/max_players/set"
        PLAYER_IDLE_TIMEOUT = "minecraft:serversettings/player_idle_timeout/set"

        # neuro
        ALLOW_FLIGHT = "minecraft:serversettings/allow_flight/set"
        MOTD = "minecraft:serversettings/motd/set"
        SPAWN_PROTECTION_RADIUS = "minecraft:serversettings/spawn_protection_radius/set"
        FORCE_GAME_MODE = "minecraft:serversettings/force_game_mode/set"
        GAME_MODE = "minecraft:serversettings/game_mode/set"
        VIEW_DISTANCE = "minecraft:serversettings/view_distance/set"
        SIMULATION_DISTANCE = "minecraft:serversettings/simulation_distance/set"
        ACCEPT_TRANSFERS = "minecraft:serversettings/accept_transfers/set"
        STATUS_HEARTBEAT_INTERVAL = "minecraft:serversettings/status_heartbeat_interval/set"
        OPERATOR_PERMISSION_LEVEL = "minecraft:serversettings/operator_user_permission_level/set"
        HIDE_ONLINE_PLAYERS = "minecraft:serversettings/hide_online_players/set"
        STATUS_REPLIES = "minecraft:serversettings/status_replies/set"
        ENTITY_BROADCAST_RANGE = "minecraft:serversettings/entity_broadcast_range/set"

    class get:
        PLAYERS = "minecraft:players"
        PLAYER_IDLE_TIMEOUT = "minecraft:serversettings/player_idle_timeout"
        PAUSE_WHEN_EMPTY_SECONDS = "minecraft:serversettings/pause_when_empty_seconds"
        MAX_PLAYERS = "minecraft:serversettings/max_players"
        DIFFICULTY = "minecraft:serversettings/difficulty"
        AUTO_SAVE = "minecraft:serversettings/autosave"
        SERVER_STATUS = "minecraft:server/status"
        BANLIST = "minecraft:bans"
        IP_BANLIST = "minecraft:ip_bans"
        OPERATORS = "minecraft:operators"
        WHITELIST = "minecraft:allowlist"
        USE_WHITELIST = "minecraft:serversettings/use_allowlist"

        # neuro
        ALLOW_FLIGHT = "minecraft:serversettings/allow_flight"
        MOTD = "minecraft:serversettings/motd"
        SPAWN_PROTECTION_RADIUS = "minecraft:serversettings/spawn_protection_radius"
        FORCE_GAME_MODE = "minecraft:serversettings/force_game_mode"
        GAME_MODE = "minecraft:serversettings/game_mode"
        VIEW_DISTANCE = "minecraft:serversettings/view_distance"
        SIMULATION_DISTANCE = "minecraft:serversettings/simulation_distance"
        ACCEPT_TRANSFERS = "minecraft:serversettings/accept_transfers"
        STATUS_HEARTBEAT_INTERVAL = "minecraft:serversettings/status_heartbeat_interval"
        OPERATOR_PERMISSION_LEVEL = "minecraft:serversettings/operator_user_permission_level"
        HIDE_ONLINE_PLAYERS = "minecraft:serversettings/hide_online_players"
        STATUS_REPLIES = "minecraft:serversettings/status_replies"
        ENTITY_BROADCAST_RANGE = "minecraft:serversettings/entity_broadcast_range"

    class run:
        KICK_ALL = "minecraft:players/kick"
        SEND_SERVER_MESSAGE = "minecraft:server/system_message"