import dataclasses
from ...datamodels.DataModel import ChangeAgentEnum as ChangeAgentEnum, DataModel as DataModel, WellElevationUnitsEnum as WellElevationUnitsEnum
from ...datamodels.Document import Document as Document
from ...datamodels.Helpers import DeprecatedFieldInfo as DeprecatedFieldInfo, MakeIsodateOptionalField as MakeIsodateOptionalField, deprecated_field as deprecated_field, with_field_deprecations as with_field_deprecations
from ...datamodels.PrimaryDataObject import DataObjectTypeEnum as DataObjectTypeEnum, PrimaryDataObject as PrimaryDataObject
from ...datamodels.geospatial.Coordinate import Coordinate as Coordinate
from ...datamodels.geospatial.Crs import CrsSpec as CrsSpec
from ...datamodels.geospatial.Enums import DatumTypeEnum as DatumTypeEnum
from ...datamodels.geospatial.GeoLocation import GeoLocation as GeoLocation
from ...datamodels.strat.StratColumn import StratColumnEntry as StratColumnEntry
from ...datamodels.wells.Wellbore import Wellbore as Wellbore
from ..Company import Division as Division
from dataclasses import dataclass, field
from dataclasses_json import DataClassJsonMixin, config
from datetime import datetime
from strenum import PascalCaseStrEnum, StrEnum
from typing import ClassVar

class WellElevationTypeEnum(StrEnum):
    KB = 'KB'
    Wellhead = 'Wellhead'
    Ground = 'Ground'
    Water = 'Water'

@dataclass
class WellElevation(DataClassJsonMixin):
    dataclass_json_config = ...
    elevation: float
    elevation_type: WellElevationTypeEnum

class WellDirectionEnum(StrEnum):
    Unknown = 'Unknown'
    HuffNPuff = 'HuffNPuff'
    Injector = 'Injector'
    Producer = 'Producer'
    Uncertain = 'Uncertain'

class WellPurposeEnum(StrEnum):
    Unknown = 'Unknown'
    Appraisal = 'Appraisal'
    Appraisal_Confirmation = 'Appraisal_Confirmation'
    Appraisal_Exploratory = 'Appraisal_Exploratory'
    Exploration = 'Exploration'
    Exploration_DeeperPoolWildcat = 'Exploration_DeeperPoolWildcat'
    Exploration_NewFieldWildcat = 'Exploration_NewFieldWildcat'
    Exploration_NewPoolWildcat = 'Exploration_NewPoolWildcat'
    Exploration_OutpostWildcat = 'Exploration_OutpostWildcat'
    Exploration_ShallowerPoolWildcat = 'Exploration_ShallowerPoolWildcat'
    Development = 'Development'
    Development_InfillDevelopment = 'Development_InfillDevelopment'
    Development_Injector = 'Development_Injector'
    Development_Producer = 'Development_Producer'
    FluidStorage = 'FluidStorage'
    FluidStorage_Gas = 'FluidStorage_Gas'
    GeneralServices = 'GeneralServices'
    GeneralServices_BoreholeReacquisition = 'GeneralServices_BoreholeReacquisition'
    GeneralServices_Observation = 'GeneralServices_Observation'
    GeneralServices_Relief = 'GeneralServices_Relief'
    GeneralServices_Research = 'GeneralServices_Research'
    GeneralServices_Research_DrillTest = 'GeneralServices_Research_DrillTest'
    GeneralServices_Research_StratTest = 'GeneralServices_Research_StratTest'
    Mineral = 'Mineral'

class WellFluidEnum(StrEnum):
    Unknown = 'Unknown'
    Air = 'Air'
    Condensate = 'Condensate'
    Dry = 'Dry'
    Gas = 'Gas'
    Gas_Water = 'Gas_Water'
    Non_Hydrocarbon_Gas = 'Non_Hydrocarbon_Gas'
    Non_Hydrocarbon_Gas_CO2 = 'Non_Hydrocarbon_Gas_CO2'
    Oil = 'Oil'
    Oil_Gas = 'Oil_Gas'
    Oil_Water = 'Oil_Water'
    Steam = 'Steam'
    Water = 'Water'
    Water_Brine = 'Water_Brine'
    Water_FreshWater = 'Water_FreshWater'

class EnvironmentTypeEnum(StrEnum):
    Unknown = 'Unknown'
    Land = 'Land'
    Marine = 'Marine'
    Transition = 'Transition'

class WellStatusEnum(PascalCaseStrEnum):
    Unknown = ...
    Active = ...
    ActiveInjecting = ...
    ActiveProducing = ...
    Completed = ...
    Drilling = ...
    PartiallyPlugged = ...
    Permitted = ...
    PluggedAndAbandoned = ...
    Proposed = ...
    Sold = ...
    Suspended = ...
    TemporarilyAbandoned = ...
    Testing = ...
    Tight = ...
    WorkingOver = ...

class WellInterestEnum(StrEnum):
    Unknown = 'Unknown'
    Operated = 'Operated'
    NonOperated = 'NonOperated'
    Royalty = 'Royalty'
    Override = 'Override'
    NoInterest = 'NoInterest'

@dataclass
class Well(PrimaryDataObject):
    external_id: str | None = ...
    external_source: str | None = ...
    creator: str | None = ...
    change_agent: ChangeAgentEnum = ...
    creation_date: datetime | None = ...
    last_modified_date: datetime | None = ...
    number: str | None = ...
    description: str | None = ...
    uwi: str | None = field(default=None, metadata=config(field_name='UWI'))
    original_uwi: str | None = ...
    division: Division | None = ...
    status: WellStatusEnum | None = ...
    is_live: bool | None = ...
    environment: EnvironmentTypeEnum | None = ...
    purpose: WellPurposeEnum | None = ...
    fluid_type: WellFluidEnum | None = ...
    well_direction: WellDirectionEnum | None = ...
    property_number: str | None = ...
    afe_number: str | None = field(default=None, metadata=config(field_name='AFENumber'))
    spud_date: datetime | None = ...
    completion_date: datetime | None = ...
    permit_date: datetime | None = ...
    plugged_date: datetime | None = ...
    target_zone: str | None = ...
    target_zone_id: int | None = ...
    latitude: float | None = ...
    longitude: float | None = ...
    location_datum: DatumTypeEnum | None = ...
    user_entered_latitude: float | None = ...
    user_entered_longitude: float | None = ...
    user_location_datum: DatumTypeEnum | None = ...
    user_entered_coordinate: Coordinate | None = ...
    user_entered_coordinate_system: CrsSpec | None = ...
    rig: str | None = ...
    pad: str | None = ...
    basin: str | None = ...
    play: str | None = ...
    zone: str | None = ...
    oil_field: str | None = field(default=None, metadata=config(field_name='Field'))
    country: str | None = ...
    state: str | None = ...
    county: str | None = ...
    region: str | None = ...
    district: str | None = ...
    block: str | None = ...
    land_grid_location: str | None = ...
    license_number: str | None = ...
    license_issue_date: datetime | None = ...
    operator: str | None = ...
    operator_division: str | None = ...
    operator_property_number: str | None = ...
    interest: float | None = ...
    interest_type: WellInterestEnum | None = ...
    elevation: float | None = ...
    elevation_type: WellElevationTypeEnum | None = ...
    elevation_units: WellElevationUnitsEnum | None = ...
    elevations: list[WellElevation] = dataclasses.field(default_factory=list[WellElevation])
    strat_column: StratColumnEntry | None = ...
    azimuth: float | None = ...
    primary_well_bore_md: float | None = field(default=None, metadata=config(field_name='PrimaryWellBoreMD'))
    primary_well_bore_tvd: float | None = field(default=None, metadata=config(field_name='PrimaryWellBoreTVD'))
    wellbores: list[Wellbore] = dataclasses.field(default_factory=list[Wellbore])
    primary_well_bore_net_pay: float | None = ...
    documents: list[Document] = dataclasses.field(default_factory=list[Document])
    archive_dir_name: ClassVar[str] = ...
    archive_json_filename: ClassVar[str] = ...
    @property
    def location(self) -> GeoLocation: ...
    @property
    def data_object_type(self) -> DataObjectTypeEnum: ...
    def init_primary_wellbore(self) -> None: ...
    def copy_ids_from(self, source: DataModel): ...
    def make_trimmed_copy(self) -> Well: ...
    def get_documents(self) -> list[Document]: ...
    @property
    def full_name(self) -> str: ...
    @property
    def primary_wellbore(self) -> Wellbore | None: ...

@dataclass
class WellEntry(DataModel):
    id: int = ...
    uwi: str | None = field(default=None, metadata=config(field_name='UWI'))
    name: str = ...
    number: str | None = ...
    description: str | None = ...
    division: Division | None = ...
    company_name: str | None = ...
    status: str | None = ...
    is_live: bool | None = ...
    latitude: float | None = ...
    longitude: float | None = ...
    @property
    def location(self) -> GeoLocation: ...
    @property
    def full_name(self): ...
    @property
    def well(self) -> Well: ...
