from ...datamodels.DataModel import DataModel as DataModel
from ...datamodels.wells.Survey import Survey as Survey
from _typeshed import Incomplete
from dataclasses import dataclass, field
from dataclasses_json import config
from strenum import StrEnum

class WellTopDepthTypeEnum(StrEnum):
    NotSet = 'NotSet'
    MD = 'MD'
    TVD = 'TVD'
    Elevation = 'Elevation'

@dataclass
class Welltop(DataModel):
    observation_number: int | None = ...
    formation_id: int = ...
    formation_name: str = ...
    formation_symbol: str = ...
    strat_column_id: int = ...
    md: float | None = field(default=None, metadata=config(field_name='MD'))
    tvd: float | None = field(default=None, metadata=config(field_name='TVD'))
    elevation: float | None = ...
    entered_depth_type: WellTopDepthTypeEnum | None = ...
    vx: float | None = field(default=None, metadata=config(field_name='VX'))
    interpreter: str | None = ...
    description: str | None = ...
    porosity: float | None = ...
    water_saturation: float | None = ...
    shale_content: float | None = ...
    hc_porosity: float | None = field(default=None, metadata=config(field_name='HCPorosity'))
    geoprog_top: bool = ...
    survey_id: int | None = ...
    survey: Survey | None = field(metadata=config(exclude=Incomplete), default=None)
