"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .amountdecimalvalidationerror import (
    AmountDecimalValidationError,
    AmountDecimalValidationErrorTypedDict,
)
from moovio_sdk.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CreateTransferLineItemOptionValidationErrorTypedDict(TypedDict):
    name: NotRequired[str]
    group: NotRequired[str]
    price_modifier: NotRequired[AmountDecimalValidationErrorTypedDict]
    quantity: NotRequired[str]
    image_i_ds: NotRequired[str]


class CreateTransferLineItemOptionValidationError(BaseModel):
    name: Optional[str] = None

    group: Optional[str] = None

    price_modifier: Annotated[
        Optional[AmountDecimalValidationError], pydantic.Field(alias="priceModifier")
    ] = None

    quantity: Optional[str] = None

    image_i_ds: Annotated[Optional[str], pydantic.Field(alias="imageIDs")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["name", "group", "priceModifier", "quantity", "imageIDs"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
