from .edges import WRITE_EDGES_STEP
from .files import METRO_EDGES_FILE as METRO_EDGES_FILE
from .files import METRO_VEHICLE_TYPES_FILE as METRO_VEHICLE_TYPES_FILE
from .vehicle_types import VEHICLE_TYPES_TABLE, WRITE_VEHICLE_TYPES_STEP

SUPPLY_CONFIG_SCHEMA = [VEHICLE_TYPES_TABLE]

SUPPLY_STEPS = [WRITE_EDGES_STEP, WRITE_VEHICLE_TYPES_STEP]
