from amsdal.contrib.crm.models.pipeline import Pipeline as Pipeline
from amsdal_models.classes.data_models.constraints import UniqueConstraint
from amsdal_models.classes.data_models.indexes import IndexInfo
from amsdal_models.classes.model import Model
from amsdal_utils.models.enums import ModuleType
from pydantic import ConfigDict
from typing import ClassVar

class Stage(Model):
    """Pipeline stage model.

    Represents a stage within a sales pipeline with win probability
    and closed status indicators.
    """
    model_config: ClassVar[ConfigDict] = ...
    __module_type__: ClassVar[ModuleType] = ...
    __constraints__: ClassVar[list[UniqueConstraint]] = ...
    __indexes__: ClassVar[list[IndexInfo]] = ...
    pipeline: Pipeline = ...
    name: str = ...
    order: int = ...
    probability: float = ...
    is_closed_won: bool = ...
    is_closed_lost: bool = ...
    @property
    def display_name(self) -> str:
        """Return display name for the stage."""
