from easyroutine.inference.base_model_interface import BaseInferenceModelConfig
from easyroutine.inference.vllm_model_interface import VLLMInferenceModel, VLLMInferenceModelConfig
from easyroutine.inference.litellm_model_interface import LiteLLMInferenceModel, LiteLLMInferenceModelConfig