symbols = {
    # self replacemtn commands:
    # from https://latexref.xyz/Math-functions.html
    "_":      ["_"],
    "$":      ["$"],
    "{":      ["{"],
    "}":      ["}"],
    "#":      ["#"],
    "&":      ["&"],
    "arccos": ["a", "r", "c", "c", "o", "s"],
    "arcsin": ["a", "r", "c", "s", "i", "n"],
    "arctan": ["a", "r", "c", "t", "a", "n"],
    "arg":  ["a", "r", "g"],
    "bmod": ["b", "m", "o", "d"],
    "cos":  ["c", "o", "s"],
    "cosh": ["c", "o", "s", "h"],
    "cot":  ["c", "o", "t"],
    "coth": ["c", "o", "t", "h"],
    "csc":  ["c", "s", "c"],
    "deg":  ["d", "e", "g"],
    "det":  ["d", "e", "t"],
    "dim":  ["d", "i", "m"],
    "exp":  ["e", "x", "p"],
    "gcd":  ["g", "c", "d"],
    "hom":  ["h", "o", "m"],
    "inf":  ["i", "n", "f"],
    "ker":  ["k", "e", "r"],
    "lg":   ["l", "g"],
    "lim":  ["l", "i", "m"],
    "liminf": ["l", "i", "m", "i", "n", "f"],
    "limsup": ["l", "i", "m", "s", "u", "p"],
    "ln":   ["l", "n"],
    "log":  ["l", "o", "g"],
    "max":  ["m", "a", "x"],
    "min":  ["m", "i", "n"],
    "pmod": ["p", "m", "o", "d"],
    "Pr":   ["P", "r"],
    "sec":  ["s", "e", "c"],
    "sin":  ["s", "i", "n"],
    "sinh": ["s", "i", "n", "h"],
    "sup":  ["s", "u", "p"],
    "tan":  ["t", "a", "n"],
    "tanh": ["t", "a", "n", "h"],
    "%": ["%"],
    # from https://latexref.xyz/Spacing-in-math-mode.html
    " ": [" "],
    ";": [" "],
    ":": [" "],
    ">": [" "],
    ",": [" "],
    "!": [],
    "quad":  [" ", " "],
    "qquad": [" ", " ", " ", " "],
    # my own
    "LaTeX":    ["L", "ᴬ", "T", "ₑ", "X"],
    "TeXicode":    ["T", "ᵉ", "X", "ᵢ", "c", "ₒ", "d", "ₑ"],
    "mod":      [" ", " ", "m", "o", "d"],
    "boxtimes": ["⊠"],  # found in overleaf
    "cdots":    ["⋯"],
    "dots":     ["…"],
    "ldots":    ["…"],
    "vdots":    ["⋮"],
    "ddots":    ["⋱"],
    "lvert":    ["|"],
    "rvert":    ["|"],
    "divides":  ["∣"],
    "because":  ["∵"],
    "therefore": ["∴"],
    "trianglelefteq": ["⊴"],
    # from https://latexref.xyz/Math-symbols.html
    "|": ["∥"],
    "aleph": ["ℵ"],
    "alpha": ["α"],
    "amalg": ["⨿"],
    "angle": ["∠"],
    "approx": ["≈"],
    "ast": ["∗"],
    "asymp": ["≍"],
    "backslash": ["\\"],
    "beta": ["β"],
    # "bigcap": "⋂",
    "bigcirc": ["◯"],
    # "bigcup": "⋃",
    # "bigodot": "⨀",
    # "bigoplus": "⨁",
    # "bigotimes": "⨂",
    # "bigtriangledown": "▽", "varbigtriangledown": "▽",
    # "bigtriangleup": "△", "varbigtriangleup": "△",
    # "bigsqcup": "⨆",
    # "biguplus": "⨄",
    # "bigvee": "⋁",
    # "bigwedge": "⋀",
    "bot":            ["⊥"],
    "bowtie":         ["⋈"],
    "Box":            ["□"],
    "bullet":         ["•"],
    "cap":            ["∩"],
    "cdot":           ["⋅"],
    "chi":            ["χ"],
    "circ":           ["∘"],
    "clubsuit":       ["♣"],
    "complement":     ["∁"],
    "cong":           ["≅"],
    "coprod":         ["∐"],
    "cup":            ["∪"],
    "dagger":         ["†"],
    "dashv":          ["⊣"],
    "ddagger":        ["‡"],
    "Delta":          ["Δ"],
    "delta":          ["δ"],
    "Diamond":        ["◇"],
    "diamond":        ["⋄"],
    "diamondsuit":    ["♢"],
    "div":            ["÷"],
    "doteq":          ["≐"],
    "downarrow":      ["↓"],
    "Downarrow":      ["⇓"],
    "ell":            ["ℓ"],
    "emptyset":       ["∅"],
    "epsilon":        ["ϵ"],
    "equiv":          ["≡"],
    "eta":            ["η"],
    "exists":         ["∃"],
    "flat":           ["♭"],
    "forall":         ["∀"],
    "frown":          ["⌢"],
    "Gamma":          ["Γ"],
    "gamma":          ["γ"],
    "ge":             ["≥"],
    "geq":            ["≥"],
    "gets":           ["←"],
    "gg":             ["≫"],
    "hbar":           ["ℏ"],
    "heartsuit":      ["♡"],
    "hookleftarrow":  ["↩"],
    "hookrightarrow": ["↪"],
    "iff":            ["⟷", " "],
    "Im":             ["ℑ"],
    "imath":          ["ı"],
    "in":             ["∈"],
    "infty":          ["∞"],
    "int":            ["∫"],
    "iota":           ["ι"],
    "Join":           ["⨝"],
    "jmath":          ["ȷ"],
    "kappa":          ["κ"],
    "Lambda":         ["Λ"],
    "lambda":         ["λ"],
    "land":           ["∧"],
    "langle":         ["⟨"],
    "lbrace":         ["{"],
    "lbrack":         ["["],
    "lceil":          ["⌈"],
    "le":             ["≤"],
    "leadsto":        ["⇝"],
    "Leftarrow":      ["⇐"],
    "leftarrow":      ["←"],
    "leftharpoondown": ["↽"],
    "leftharpoonup":  ["↼"],
    "Leftrightarrow": ["⇔"],
    "leftrightarrow": ["↔"],
    "leq":            ["≤"],
    "lfloor":         ["⌊"],
    "lhd":            ["◁"],
    "ll":             ["≪"],
    "lnot":           ["¬"],
    "longleftarrow":  ["⟵", " "],
    "longleftrightarrow": ["⟷", " "],
    "longmapsto":     ["⟼", " "],
    "longrightarrow": ["⟶", " "],
    "lor":            ["∨"],
    "mapsto":         ["↦"],
    "mho":            ["℧"],
    "mid":            ["∣"],
    "models":         ["⊨"],
    "mp":             ["∓"],
    "mu":             ["μ"],
    "nabla":          ["∇"],
    "natural":        ["♮"],
    "ne":             ["≠"],
    "nearrow":        ["↗"],
    "neg":            ["¬"],
    "neq":            ["≠"],
    "ni":             ["∋"],
    "not":            ["⧸"],  # you can also use \u0337 or 0338
    "notin":          ["∉"],
    "nu":             ["ν"],
    "nwarrow":        ["↖"],
    "odot":           ["⊙"],
    "oint":           ["∮"],
    "Omega":          ["Ω"],
    "omega":          ["ω"],
    "ominus":         ["⊖"],
    "oplus":          ["⊕"],
    "oslash":         ["⊘"],
    "otimes":         ["⊗"],
    "owns":           ["∋"],
    "parallel":       ["∥"],
    "partial":        ["∂"],
    "perp":           ["⟂"],
    "Phi":            ["Φ"],
    "phi":            ["ϕ"],
    "Pi":             ["Π"],
    "pi":             ["π"],
    "pm":             ["±"],
    "prec":           ["≺"],
    "preceq":         ["⪯"],
    "prime":          ["′"],
    "prod":           ["∏"],
    "propto":         ["∝"],
    "Psi":            ["Ψ"],
    "psi":            ["ψ"],
    "rangle":         ["⟩"],
    "rbrace":         ["}"],
    "rbrack":         ["]"],
    "rceil":          ["⌉"],
    "Re":             ["ℜ"],
    "restriction":    ["↾"],
    "revemptyset":    ["⦰"],
    "rfloor":         ["⌋"],
    "rhd":            ["◁"],
    "rho":            ["ρ"],
    "Rightarrow":     ["⇒"],
    "rightarrow":     ["→"],
    "rightharpoondown":  ["⇁"],
    "rightharpoonup":    ["⇀"],
    "rightleftharpoons": ["⇌"],
    "searrow":        ["↘"],
    "setminus":       ["⧵"],
    "sharp":          ["♯"],
    "Sigma":          ["Σ"],
    "sigma":          ["σ"],
    "sim":            ["∼"],
    "simeq":          ["≃"],
    "smallint":       ["∫"],
    "smile":          ["⌣"],
    "spadesuit":      ["♠"],
    "sqcap":          ["⊓"],
    "sqcup":          ["⊔"],
    "sqsubset":       ["⊏"],
    "sqsubseteq":     ["⊑"],
    "sqsupset":       ["⊐"],
    "sqsupseteq":     ["⊒"],
    "star":           ["⋆"],
    "subset":         ["⊂"],
    "subseteq":       ["⊆"],
    "succ":           ["≻"],
    "succeq":         ["⪰"],
    "sum":            ["∑"],
    "supset":         ["⊃"],
    "supseteq":       ["⊇"],
    "surd":           ["√"],
    "swarrow":        ["↙"],
    "tau":            ["τ"],
    "theta":          ["θ"],
    "times":          ["×"],
    "to":             ["→"],
    "top":            ["⊤"],
    "triangle":       ["△"],
    "triangleleft":   ["◁"],
    "triangleright":  ["▷"],
    "unlhd":          ["⊴"],
    "unrhd":          ["⊵"],
    "Uparrow":        ["⇑"],
    "uparrow":        ["↑"],
    "Updownarrow":    ["⇕"],
    "updownarrow":    ["↕"],
    "upharpoonright": ["↾"],
    "uplus":          ["⊎"],
    "Upsilon":        ["Υ"],
    "upsilon":        ["υ"],
    "varepsilon":     ["ε"],
    "vanothing":      ["∅"],
    "varphi":         ["φ"],
    "varpi":          ["ϖ"],
    "varrho":         ["ϱ"],
    "varsigma":       ["ς"],
    "vartheta":       ["ϑ"],
    "vdash":          ["⊢"],
    "vee":            ["∨"],
    "Vert":           ["‖"],
    "vert":           ["|"],
    "wedge":          ["∧"],
    "wp":             ["℘"],
    "wr":             ["≀"],
    "Xi":             ["Ξ"],
    "xi":             ["ξ"],
    "zeta":           ["ζ"],
    "mathdollar":     ["$"],
    "mathparagraph":  ["¶"],
    "mathsection":    ["§"],
    "mathsterling":   ["£"],
    "mathunderscore": ["_"],
}
