"""
Pydantic Models for MONITOR - log/forticloud_report/download

Runtime validation models for log/forticloud_report/download configuration.
Generated from FortiOS schema version unknown.
"""

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Any


# ============================================================================
# Module Exports
# ============================================================================

__all__ = [
    "DownloadModel",]


# ============================================================================
# Generated by hfortix generator v0.6.0
# Schema: 1.7.0
# Generated: 2026-01-10T08:58:15.321556Z
# ============================================================================