"""flowerhub_client package

Exports the async client API suitable for Home Assistant integrations.
"""

from .async_client import AsyncFlowerhubClient
from .exceptions import ApiError, AuthenticationError
from .types import (
    AgreementState,
    Asset,
    AssetInfo,
    AssetModel,
    AssetOwner,
    AssetOwnerDetails,
    AssetOwnerProfile,
    Battery,
    Compensation,
    ConsumptionRecord,
    ElectricityAgreement,
    FlowerHubStatus,
    InstallerInfo,
    Inverter,
    Invoice,
    InvoiceLine,
    LoginResponse,
    Manufacturer,
    PostalAddress,
    Revenue,
    RevenueResult,
    SimpleDistributor,
    SimpleInstaller,
    UptimeHistoryEntry,
    UptimeMonth,
    UptimePieResult,
    User,
)

__all__ = [
    "AsyncFlowerhubClient",
    "AuthenticationError",
    "ApiError",
    "FlowerHubStatus",
    "User",
    "LoginResponse",
    "Asset",
    "AssetOwner",
    "AssetOwnerProfile",
    "AssetOwnerDetails",
    "AssetInfo",
    "AssetModel",
    "Inverter",
    "Battery",
    "Manufacturer",
    "PostalAddress",
    "InstallerInfo",
    "SimpleInstaller",
    "SimpleDistributor",
    "Compensation",
    "UptimeMonth",
    "UptimeHistoryEntry",
    "UptimePieResult",
    "AgreementState",
    "ElectricityAgreement",
    "ConsumptionRecord",
    "Invoice",
    "InvoiceLine",
    "Revenue",
    "RevenueResult",
]
