__all__ = ['CEOutOfRange', 'CEInvalidArguments', 'CENotInitialized', 'CEOutOfLeagueException', 'CECannotRecoveryException', 'CEInvalidValueException', 'CEMissMatchedException', 'CENullException', 'CENotFoundException', 'CECommunicationError', 'CEMandatoryError', 'CENotSupportException', 'CELogicErrorException']

class CEOutOfRange(Exception): ...
class CEInvalidArguments(Exception): ...
class CENotInitialized(Exception): ...
class CEOutOfLeagueException(Exception): ...
class CECannotRecoveryException(Exception): ...
class CEInvalidValueException(Exception): ...
class CEMissMatchedException(Exception): ...
class CENullException(Exception): ...
class CENotFoundException(Exception): ...
class CECommunicationError(Exception): ...
class CEMandatoryError(Exception): ...
class CENotSupportException(Exception): ...
class CELogicErrorException(Exception): ...
class CENotConnectedException(Exception): ...
class CEUnIntendedException(Exception): ...
