from datetime import tzinfo

def DATE() -> str: ...
def TIME() -> str: ...
def get_UTC() -> float: ...
def get_DATE(date_format: str = '%Y-%m-%d %H:%M:%S') -> str: ...
def get_ZONE() -> str: ...
def get_UTC_time(any_date: str, timezone: str, date_format: str = '%Y-%m-%d %H:%M:%S') -> str: ...
def get_UTC_timestamp(any_date: str, timezone: str, date_format: str = '%Y-%m-%d %H:%M:%S') -> float: ...
def cvt_utc(utc: float, date_format: str = '%Y-%m-%d %H:%M:%S') -> str: ...
def cvt_utc_DATE(utc: float, timezone: tzinfo = None, zone_utc: bool = False) -> tuple[str, str]: ...
def cvt_DATE(from_date: str, from_tz: str, to_tz: str, utc_gap: float = 0.0) -> str: ...
def get_GAP(from_date: str, from_tz: str, to_date: str, to_tz: str) -> float: ...
