from .lib_logger import *
from _typeshed import Incomplete

logger: Incomplete

class CPath:
    @staticmethod
    def join_paths(path1: str, path2: str) -> str: ...
    @staticmethod
    def get_rootpath(): ...
    @staticmethod
    def get_module_root(module, internal_path: Incomplete | None = None): ...
    @staticmethod
    def get_dirpath(filepath: str): ...
    @staticmethod
    def get_filename(filepath): ...
    @staticmethod
    def split_filename_ext(filepath): ...
    @staticmethod
    def is_abspath(path: str): ...
    @staticmethod
    def get_relpath(target_abs_path: str, base_path: str) -> str: ...
    @staticmethod
    def get_abspath(rel_path: str = None) -> str: ...
    @staticmethod
    def get_rear_path(full_path: str, rear_cnt: int): ...
    @staticmethod
    def check_exist(path: str, attribute: str): ...
    @staticmethod
    def classfy_files_dirs(dirpath: str): ...
    @staticmethod
    def make_dirs(dirpath: str): ...
    @staticmethod
    def send_local_to_linux(src: str, dest_dir: str, send_func): ...
