from .lib_retry import *
from .exception import *
from .lib_logger import *
from .lib_ps import CProcess as CProcess
from _typeshed import Incomplete

logger: Incomplete

class TYPE:
    DIR: str
    FILE: str
    ALL_FILES: str

class TAR_TYPE:
    GZ: str
    TGZ: str
    @staticmethod
    def all(): ...

def local_shell(command: str, timeout_sec: int = 5): ...
def local_check_process(cmd: str, name: str = None, user: str = None, kill: bool = False): ...
def local_execute_backend(command: str, working_dir: str = None): ...
def local_start_adbd(): ...
def local_kill_adbd(): ...
def local_mkdir(dir_path: str): ...
def local_date() -> str: ...
def local_ping(ip: str, cnt: int = 5) -> str: ...
def local_copy(src: str, src_type: TYPE, dest: str, dest_type: TYPE = ...): ...
def local_remove(src: str, type: TYPE = ...): ...
def local_tar_compress(src: list[str], out: str, src_dir: str = None, out_type: TAR_TYPE = ..., timeout_sec: int = 5): ...
