from .lib_logger import *
import types
from _typeshed import Incomplete

logger: Incomplete

def import_module(absolute_path: str): ...
def import_class(module: types.ModuleType, class_name: str): ...
def get_path_class(data: dict): ...
def get_class_reference(data: dict, local_root: str): ...
