from enum import Enum
from http import HTTPStatus

class HTTPStatusCode(int, Enum):
    OK = HTTPStatus.OK.value
    CREATED = HTTPStatus.CREATED.value
    BAD_REQUEST = HTTPStatus.BAD_REQUEST.value
    UNAUTHORIZED = HTTPStatus.UNAUTHORIZED.value
    FORBIDDEN = HTTPStatus.FORBIDDEN.value
    NOT_FOUND = HTTPStatus.NOT_FOUND.value
    CONFLICT = HTTPStatus.CONFLICT.value
    TOO_MANY_REQUESTS = HTTPStatus.TOO_MANY_REQUESTS.value
    INTERNAL_SERVER_ERROR = HTTPStatus.INTERNAL_SERVER_ERROR.value

class APICode(str, Enum):
    OK = "OK"
    CREATED = "CREATED"
    BAD_REQUEST = "BAD_REQUEST"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    NOT_FOUND = "NOT_FOUND"
    ROUTE_NOT_FOUND = "ROUTE_NOT_FOUND"
    DATA_NOT_FOUND = "DATA_NOT_FOUND"
    CONFLICT = "CONFLICT"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS"
    VALIDATION = "VALIDATION"
    ERROR = "ERROR"
    EMAIL_VERIFICATION = "EMAIL_VERIFICATION"
    INVALID_COUPON = "INVALID_COUPON"
    DATA_EXIST = "DATA_EXIST"
