# Field names from feature_spec.proto.
SOURCE_DATA_COLUMN_INFO = "source_data_column_info"
FEATURE_COLUMN_INFO = "feature_column_info"
ON_DEMAND_COLUMN_INFO = "on_demand_column_info"
INPUT_COLUMNS = "input_columns"
NAME = "name"
OUTPUT_NAME = "output_name"
INPUT_TABLES = "input_tables"
TABLE_NAME = "table_name"
TABLE_ID = "table_id"
SERIALIZATION_VERSION = "serialization_version"
INPUT_FUNCTIONS = "input_functions"
INCLUDE = "include"
DATA_TYPE = "data_type"
TOPOLOGICAL_ORDERING = "topological_ordering"
UDF_NAME = "udf_name"
INPUT_BINDINGS = "input_bindings"
PARAMETER = "parameter"
BOUND_TO = "bound_to"

# FeatureSpec YAML source field and allowed values
SOURCE = "source"
TRAINING_DATA = "training_data"
FEATURE_STORE = "feature_store"
ON_DEMAND_FEATURE = "on_demand_feature"
