export declare const AUTHENTICATION = "Authentication";
export declare const AUTHORIZATION_H = "Authorization";
export declare const AUTHORIZATION_L = "authorization";
export declare const UNAUTHORIZED = "Unauthorized";
export declare const AUTHORIZATION_HEADER = "Authorization header";
export declare const INVALID_ERROR_PREFIX = "Invalid";
export declare const INCORRECT_ERROR_PREFIX = "Incorrect";
export declare const AUTHENTICATION_ERROR_PREFIX = "authentication_error";
export declare const INVALID_REQUEST_ERROR_PREFIX = "invalid_request_error";
export declare const CONTENT_TYPE_H_KEY = "Content-Type";
export declare const CONTENT_TYPE_L_KEY = "content-type";
export declare const APPLICATION_JSON = "application/json";
export declare const OBJECT = "object";
export declare const COMPLETED = "completed";
export declare const BEARER_PREFIX = "Bearer ";
export declare const GET = "GET";
export declare const POST = "POST";
export declare const UPLOAD_AN_AUDIO_FILE = "Upload an audio file";
//# sourceMappingURL=serviceConstants.d.ts.map