# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Category.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x43\x61tegory.proto\x12\x14Xiaoyang.Measurement*\xf3\x01\n\x13MeasurementCategory\x12\x08\n\x04None\x10\x00\x12\r\n\tHeartRate\x10\x01\x12\x11\n\rBloodPressure\x10\x02\x12\x0f\n\x0b\x42loodOxygen\x10\x04\x12\x08\n\x04Risk\x10\x08\x12\x10\n\x0c\x41ggressivity\x10\x10\x12\x0b\n\x07\x41nxiety\x10 \x12\x0e\n\nDepression\x10@\x12\r\n\x08Vitality\x10\x80\x01\x12\x0f\n\nPositivity\x10\x80\x02\x12\x10\n\x0bSuppression\x10\x80\x04\x12\x0c\n\x07\x46\x61tigue\x10\x80\x08\x12\x0e\n\nPhysiology\x10\x0f\x12\x0c\n\x07\x45motion\x10\xb1\r\x12\x08\n\x03\x41ll\x10\xbf\rB/\n#cn.xiaoyang.measurement.abstractionB\x08\x43\x61tegoryb\x06proto3')

_MEASUREMENTCATEGORY = DESCRIPTOR.enum_types_by_name['MeasurementCategory']
MeasurementCategory = enum_type_wrapper.EnumTypeWrapper(_MEASUREMENTCATEGORY)
globals()['None'] = 0
HeartRate = 1
BloodPressure = 2
BloodOxygen = 4
Risk = 8
Aggressivity = 16
Anxiety = 32
Depression = 64
Vitality = 128
Positivity = 256
Suppression = 512
Fatigue = 1024
Physiology = 15
Emotion = 1713
All = 1727


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n#cn.xiaoyang.measurement.abstractionB\010Category'
  _MEASUREMENTCATEGORY._serialized_start=41
  _MEASUREMENTCATEGORY._serialized_end=284
# @@protoc_insertion_point(module_scope)
