system_to_redshift = {
    "integer": "BIGINT",
    "int": "BIGINT",
    "real": "REAL",
    "bigint": "BIGINT",
    "long": "BIGINT",
    "numeric": "DECIMAL",
    "number": "DECIMAL",
    "decimal": "DECIMAL",
    "double": "DOUBLE PRECISION",
    "boolean": "BOOLEAN",
    "binary": "VARBYTE(16777215)",
    "varbinary": "VARBYTE(16777215)",
    "varbyte": "VARBYTE(16777215)",
    "bit": "BOOLEAN",
    "id": "VARCHAR",
    "reference": "VARCHAR(255)",
    "string": "VARCHAR(65535)",
    "text": "VARCHAR(65535)",
    "picklist": "VARCHAR(255)",
    "character varying": "VARCHAR(65535)",
    "character": "VARCHAR(65535)",
    "varchar": "VARCHAR(65535)",
    "date": "DATE",
    "timestamp": "TIMESTAMP",
    "timestamptz": "TIMESTAMPTZ",
    "datetime": "TIMESTAMPTZ",
    "time": "VARCHAR(255)",
    "none": "NULL",
    "null": "NULL"
}
