from typing import Self
from ..theory import Theory
from ..structure import Structure
from ..vocabulary import Vocabulary
from ._pure import *

class _KnowledgeBaseIter:
    def __iter__(self) -> Self: ...
    def __next__(self) -> tuple[str, Block]: ...

class _KnowledgeBase:
    @classmethod
    def from_str(cls, knowledge_base: str) -> Self: ...
    def __getitem__(self, name: str) -> Block: ...
    def __iter__(self) -> _KnowledgeBaseIter: ...
    def __len__(self) -> int: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class Inferenceable:
    def __init__(self, theory: Theory, structure: Structure) -> None: ...
    @classmethod
    def from_specification(cls, spec: str) -> Self: ...
    @classmethod
    def from_blocks(cls, *blocks: LogicalBlock) -> Self: ...
    def structure(self) -> Structure: ...
    def vocab(self) -> Vocabulary: ...
    def theory(self) -> Theory: ...
    def __str__(self) -> str: ...
