"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from gr4vy.types import BaseModel
from gr4vy.utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Any, Dict, Literal, Optional
from typing_extensions import Annotated, TypedDict


class AccountsReceivablesReportSpecTypedDict(TypedDict):
    params: Dict[str, Any]
    r"""The parameters for the accounts receivables report model."""
    model: Literal["accounts_receivables"]
    r"""The report model type."""


class AccountsReceivablesReportSpec(BaseModel):
    params: Dict[str, Any]
    r"""The parameters for the accounts receivables report model."""

    MODEL: Annotated[
        Annotated[
            Optional[Literal["accounts_receivables"]],
            AfterValidator(validate_const("accounts_receivables")),
        ],
        pydantic.Field(alias="model"),
    ] = "accounts_receivables"
    r"""The report model type."""
