# re-export settings for convenience
from .settings import (
    SHINGLE_K, NUM_PERM, LSH_THRESH, JACCARD_THRESH_LEX, JACCARD_THRESH_STRUCT,
    RANDOM_SEED, SPLIT_RATIOS, STRING_PLACEHOLDER, NUMBER_PLACEHOLDER
)
