from ...datamodels.Helpers import MakeIsodateOptionalField as MakeIsodateOptionalField
from .SurveyModPoint import SurveyModPoint as SurveyModPoint
from dataclasses import dataclass, field as field
from datetime import datetime
from strenum import StrEnum
from zonevu.datamodels.DataModel import DataModel as DataModel
from zonevu.datamodels.surveymods.SurveyModEntry import SurveyModTypeEnum as SurveyModTypeEnum

class HDomain(StrEnum):
    MD = 'MD'
    VX = 'VX'

@dataclass
class SurveyMod(DataModel):
    description: str | None = ...
    type: SurveyModTypeEnum = ...
    creation_date: datetime | None = ...
    survey_id: int = ...
    wellbore_id: int = ...
    well_id: int = ...
    vertical_section_azimuth: float | None = ...
    domain: HDomain | None = ...
    allow_display_in_other_domains: bool | None = ...
    start_with_tie_point: bool | None = ...
    anchor_survey_station_id: int | None = ...
    show_drilling_window: bool = ...
    window_above: float | None = ...
    window_below: float | None = ...
    window_left: float | None = ...
    window_right: float | None = ...
    points: list[SurveyModPoint] = ...
