from apps.locals.user_data import EntityModelAdmin

from . import site as site  # noqa: F401
from .emails import EmailCollectorAdmin, EmailInboxAdmin, EmailSearchForm
from .forms import (
    CustomerAccountRFIDForm,
    EmailInboxAdminForm,
    EmailOutboxAdminForm,
    EmailOutboxInlineForm,
    MaskedPasswordFormMixin,
    OpenPayProcessorAdminForm,
    OdooEmployeeAdminForm,
    OdooProductAdminForm,
    PayPalProcessorAdminForm,
    ProfileFormMixin,
    ProfileInlineFormSet,
    RFIDConfirmImportForm,
    RFIDExportForm,
    RFIDImportForm,
    StripeProcessorAdminForm,
    UserChangeRFIDForm,
    UserCreationWithExpirationForm,
    keep_existing,
)
from .inlines import (
    CustomerAccountRFIDInline,
    EmailCollectorInline,
    GROUP_PROFILE_INLINES,
    PROFILE_MODELS,
    USER_PROFILE_INLINES,
    UserPhoneNumberInline,
    _build_profile_inline,
)
from .invites import InviteLeadAdmin
from .mixins import (
    OwnableAdminMixin,
    ProfileAdminMixin,
    SaveBeforeChangeAction,
    _build_credentials_actions,
)
from .odoo import OdooCustomerSearchForm, OdooEmployeeAdmin, OdooProductAdmin
from .payments import (
    OpenPayProcessorAdmin,
    PayPalProcessorAdmin,
    PaymentProcessorAdmin,
    StripeProcessorAdmin,
)
from .rfid import CopyRFIDForm, RFIDAdmin, RFIDForm, RFIDResource
from .usage import UsageEventAdmin
from .site import (
    _append_operate_as,
    _include_require_2fa,
    _include_site_template,
    _include_site_template_add,
    _include_temporary_expiration,
    changelist_view_with_object_links,
    get_app_list_with_protocol_forwarder,
)
from .users import UserAdmin

__all__ = [
    "CustomerAccountRFIDForm",
    "CustomerAccountRFIDInline",
    "EmailCollectorAdmin",
    "EmailCollectorInline",
    "EmailInboxAdmin",
    "EmailInboxAdminForm",
    "EmailOutboxAdminForm",
    "EmailOutboxInlineForm",
    "EmailSearchForm",
    "EntityModelAdmin",
    "GROUP_PROFILE_INLINES",
    "InviteLeadAdmin",
    "MaskedPasswordFormMixin",
    "OdooCustomerSearchForm",
    "OdooEmployeeAdmin",
    "OdooEmployeeAdminForm",
    "OdooProductAdmin",
    "OdooProductAdminForm",
    "OpenPayProcessorAdmin",
    "OpenPayProcessorAdminForm",
    "OwnableAdminMixin",
    "PayPalProcessorAdmin",
    "PayPalProcessorAdminForm",
    "PaymentProcessorAdmin",
    "PROFILE_MODELS",
    "ProfileAdminMixin",
    "ProfileFormMixin",
    "ProfileInlineFormSet",
    "RFIDAdmin",
    "RFIDConfirmImportForm",
    "RFIDExportForm",
    "RFIDForm",
    "RFIDImportForm",
    "RFIDResource",
    "SaveBeforeChangeAction",
    "StripeProcessorAdmin",
    "StripeProcessorAdminForm",
    "UsageEventAdmin",
    "USER_PROFILE_INLINES",
    "UserAdmin",
    "UserChangeRFIDForm",
    "UserCreationWithExpirationForm",
    "UserPhoneNumberInline",
    "_append_operate_as",
    "_build_credentials_actions",
    "_build_profile_inline",
    "_include_require_2fa",
    "_include_site_template",
    "_include_site_template_add",
    "_include_temporary_expiration",
    "changelist_view_with_object_links",
    "get_app_list_with_protocol_forwarder",
    "keep_existing",
    "CopyRFIDForm",
]
