from __future__ import annotations

from typing import Callable, overload

from fnutil.if_ import _If
from fnutil.match import _Match

__all__ = [
    "expr",
    "Expr",
]

class Expr[T]:
    inner: T | Exception

    @overload
    def __init__(self, *, val: T) -> None: ...
    @overload
    def __init__(self, *, err: Exception) -> None: ...
    @property
    def is_err(self) -> bool: ...
    @property
    def is_val(self) -> bool: ...
    @property
    def err(self) -> Exception | None: ...
    @property
    def val(self) -> T | None: ...
    def unwrap(self) -> T: ...
    def map[V](self, fn: Callable[[T], V]) -> Expr[V]: ...
    def map_err[V](self, fn: Callable[[Exception], V]) -> Expr[V]: ...
    def match[V](self) -> _Match[T, V]: ...
    def if_[V](self) -> _If[V]: ...

def expr[T](value: T, /) -> Expr[T]: ...
