from enum import Enum
 
class DeviationCode(Enum):
    IMAGE_NOT_VISIBLE = 1
    AXL_DISTANCE_DEVIATION = 2
    FRONTWHEEL_NOT_IN_PHOTOZONE = 3
    PHOTOZONE_LINES_DETERIORATED = 4
    PHOTOZONE_LINES_SNOW = 5
    WINDSHIELD_NOT_TRANSPARENT = 6
    DRIVER_NOT_ID_IMAGE_QUALITY = 7
    DRIVER_NOT_ID_CAMOUFLAGED = 8
    DRIVER_NOT_ID_OBSTRUCTED_MIRROR = 9
    DRIVER_NOT_ID_OBSTRUCTED_WINDOW_POST = 10
    SERIES_DISCARDED = 11
    INCORRECT_NUMBER_OF_AXLES = 12
    NOT_SAME_VEHICLE = 13
    LP_NOT_IN_AUTOSYS = 14
    LP_INVALIDLY_CONSTRUCTED = 15
    LP_COVERED_BY_ANOTHER_VEHICLE = 16
    VEHICLE_FROM_SWEDEN_OR_DENMARK = 17
    VEHICLE_HAS_FAKE_LICENSE_PLATE = 18
    VEHICLE_NOT_SCANDINAVIAN = 19
    LP_MISSING_DRIVER_ID = 20
    LP_MISSING_DRIVER_NOT_ID = 21
    MILITARY_VEHICLE = 22
    MOTORCYCLE = 23
    TWO_VEHICLES_IN_AREA_OF_INFLUENCE = 24
    LP_NOT_READABLE_DRIVER_NOT_ID = 25
    LP_NOT_READABLE_DRIVER_ID = 26
    ENFORCEMENT_JSON_NOT_VERIFIED = 27
    AXL_SPEED = 28
