from .argentina import AR_VALIDATOR
from .colombia import CO_VALIDATOR
from .peru import PE_VALIDATOR
from .spain import ES_VALIDATOR
from .usa import US_VALIDATOR
from .venezuela import VE_VALIDATOR

PLATFORM_VALIDATORS = {
    "BANK_TRANSFER_AR": AR_VALIDATOR,
    "CASH_PICKUP_CO": CO_VALIDATOR,
    "INTERBANK_TRANSFER_CO": CO_VALIDATOR,
    "BANK_TRANSFER_EU": ES_VALIDATOR,
    "BANK_TRANSFER_USD_PE": PE_VALIDATOR,
    "BANK_TRANSFER_PEN_PE": PE_VALIDATOR,
    "CASH_PICKUP_PEN_PE": PE_VALIDATOR,
    "WALLET_PEN_PE": PE_VALIDATOR,
    "BANK_TRANSFER_USD": US_VALIDATOR,
    "BANK_TRANSFER": VE_VALIDATOR,
    "P2P_PHONE_TRANSFER": VE_VALIDATOR,
    "CASH_PICKUP_USD_VE": VE_VALIDATOR,
}
