"""Third-person mood indicators (verbs ending in 's')."""

from __future__ import annotations

THIRD_PERSON_INDICATORS = {
    "returns",
    "gets",
    "sets",
    "creates",
    "updates",
    "deletes",
    "fetches",
    "retrieves",
    "calculates",
    "computes",
    "generates",
    "validates",
    "checks",
    "verifies",
    "converts",
    "transforms",
    "processes",
    "handles",
    "manages",
    "initializes",
    "configures",
    "executes",
    "performs",
    "provides",
    "represents",
    "contains",
    "holds",
    "loads",
    "saves",
    "reads",
    "writes",
    "detects",
    "analyzes",
    "records",
    "visits",
    "searches",
    "yields",
    "raises",
    "parses",
    "builds",
    "scans",
    "iterates",
    "collects",
    "extracts",
    "adds",
    "removes",
}
