"""
Geode-Implicit Python binding
"""
from __future__ import annotations
import geode_implicit.lib64.geode_implicit_py_implicitation
import opengeode.lib64.opengeode_py_mesh
import opengeode_geosciences.lib64.opengeode_geosciences_py_explicit
import opengeode_geosciences.lib64.opengeode_geosciences_py_implicit
__all__: list[str] = ['ClosedSurfacesFromCurves', 'ImplicitModelFromSolid', 'ImplicitModelFromStructuralModel', 'ImplicitWorkflowsLibrary', 'SingleSurfaceFromVertices', 'extract_implicit_cross_section_from_axis', 'extract_stratigraphic_section_from_axis']
class ClosedSurfacesFromCurves:
    def __init__(self) -> None:
        ...
    def add_closed_curve_data(self, arg0: opengeode.lib64.opengeode_py_mesh.EdgedCurve3D, arg1: float, arg2: float) -> None:
        ...
    def build(self, arg0: geode_implicit.lib64.geode_implicit_py_implicitation.ImplicitationParameters) -> list[opengeode.lib64.opengeode_py_mesh.TriangulatedSurface3D]:
        ...
class ImplicitModelFromSolid:
    def __init__(self, arg0: opengeode.lib64.opengeode_py_mesh.TetrahedralSolid3D, arg1: opengeode_geosciences.lib64.opengeode_geosciences_py_implicit.HorizonsStack3D) -> None:
        ...
    def add_fault_surface(self, arg0: opengeode.lib64.opengeode_py_mesh.TriangulatedSurface3D) -> None:
        ...
    def add_model_boundary_surface(self, arg0: opengeode.lib64.opengeode_py_mesh.TriangulatedSurface3D) -> None:
        ...
    def build(self) -> opengeode_geosciences.lib64.opengeode_geosciences_py_implicit.ImplicitStructuralModel:
        ...
    def horizons_stack(self) -> opengeode_geosciences.lib64.opengeode_geosciences_py_implicit.HorizonsStack3D:
        ...
    def set_horizon_scalar_function_and_isovalue(self, arg0: opengeode_geosciences.lib64.opengeode_geosciences_py_explicit.Horizon3D, arg1: str, arg2: float) -> None:
        ...
    def set_stratigraphic_unit_scalar_function(self, arg0: opengeode_geosciences.lib64.opengeode_geosciences_py_explicit.StratigraphicUnit3D, arg1: str) -> None:
        ...
class ImplicitModelFromStructuralModel:
    def __init__(self, arg0: opengeode_geosciences.lib64.opengeode_geosciences_py_explicit.StructuralModel, arg1: opengeode_geosciences.lib64.opengeode_geosciences_py_implicit.HorizonsStack3D) -> None:
        ...
    def build(self) -> opengeode_geosciences.lib64.opengeode_geosciences_py_implicit.ImplicitStructuralModel:
        ...
    def horizons_stack(self) -> opengeode_geosciences.lib64.opengeode_geosciences_py_implicit.HorizonsStack3D:
        ...
    def set_horizon_scalar_function_and_isovalue(self, arg0: opengeode_geosciences.lib64.opengeode_geosciences_py_explicit.Horizon3D, arg1: str, arg2: float) -> None:
        ...
    def set_stratigraphic_unit_scalar_function(self, arg0: opengeode_geosciences.lib64.opengeode_geosciences_py_explicit.StratigraphicUnit3D, arg1: str) -> None:
        ...
class ImplicitWorkflowsLibrary:
    @staticmethod
    def initialize() -> None:
        ...
class SingleSurfaceFromVertices:
    def __init__(self) -> None:
        ...
    def add_data_curve(self, arg0: opengeode.lib64.opengeode_py_mesh.EdgedCurve3D, arg1: float, arg2: float) -> None:
        ...
    def add_data_points(self, arg0: opengeode.lib64.opengeode_py_mesh.PointSet3D, arg1: float, arg2: float) -> None:
        ...
    def add_outline(self, arg0: opengeode.lib64.opengeode_py_mesh.EdgedCurve3D, arg1: float) -> None:
        ...
    def build_with_mesh_size(self, arg0: float) -> opengeode.lib64.opengeode_py_mesh.TriangulatedSurface3D:
        ...
    def build_with_parameters(self, arg0: geode_implicit.lib64.geode_implicit_py_implicitation.ImplicitationParameters) -> opengeode.lib64.opengeode_py_mesh.TriangulatedSurface3D:
        ...
def extract_implicit_cross_section_from_axis(arg0: opengeode_geosciences.lib64.opengeode_geosciences_py_implicit.ImplicitStructuralModel, arg1: int, arg2: float) -> opengeode_geosciences.lib64.opengeode_geosciences_py_implicit.ImplicitCrossSection:
    ...
def extract_stratigraphic_section_from_axis(arg0: opengeode_geosciences.lib64.opengeode_geosciences_py_implicit.StratigraphicModel, arg1: int, arg2: float) -> opengeode_geosciences.lib64.opengeode_geosciences_py_implicit.StratigraphicSection:
    ...
