basemap_dict = {
    "topo-3d": {
        "baseMapLayers": [
            {
                "id": "18c679fb712-layer-37",
                "layerType": "VectorTileLayer",
                "opacity": 1.0,
                "styleUrl": "https://cdn.arcgis.com/sharing/rest/content/items/1e7d1784d1ef4b79ba6764d0bd6c3150/resources/styles/root.json",
                "title": "Topographic",
                "visibility": True,
            },
            {
                "disablePopup": True,
                "id": "18c679ff88d-layer-39",
                "layerDefinition": {},
                "layerType": "ArcGISSceneServiceLayer",
                "listMode": "show",
                "opacity": 1.0,
                "screenSizePerspective": True,
                "showLabels": False,
                "showLegend": True,
                "timeAnimation": True,
                "title": "Trees",
                "url": "https://basemaps3d.arcgis.com/arcgis/rest/services/OpenStreetMap3D_Trees_Thematic_v1/SceneServer/layers/0",
                "visibility": True,
            },
            {
                "disablePopup": True,
                "id": "18c67a02c0e-layer-40",
                "layerDefinition": {},
                "layerType": "ArcGISSceneServiceLayer",
                "listMode": "show",
                "opacity": 1.0,
                "screenSizePerspective": True,
                "showLabels": False,
                "showLegend": True,
                "timeAnimation": True,
                "title": "Places and Labels",
                "url": "https://basemaps3d.arcgis.com/arcgis/rest/services/OpenStreetMap3D_DarkLabels_v1/SceneServer/layers/0",
                "visibility": True,
            },
            {
                "disablePopup": True,
                "id": "18c679fde82-layer-38",
                "layerDefinition": {},
                "layerType": "ArcGISSceneServiceLayer",
                "listMode": "show",
                "opacity": 1.0,
                "screenSizePerspective": True,
                "showLabels": False,
                "showLegend": True,
                "timeAnimation": True,
                "title": "Buildings",
                "url": "https://basemaps3d.arcgis.com/arcgis/rest/services/Esri3D_Buildings_v1/SceneServer/layers/0",
                "visibility": True,
            },
        ],
        "id": "18c679f066c-basemap-24",
        "title": "Topographic",
    },
    "navigation-3d": {
        "baseMapLayers": [
            {
                "id": "187e8fed2af-layer-0",
                "layerType": "VectorTileLayer",
                "opacity": 1.0,
                "styleUrl": "https://cdn.arcgis.com/sharing/rest/content/items/ccc904ff872b4144b94934e55e32784b/resources/styles/root.json",
                "title": "Navigation",
                "visibility": True,
            },
            {
                "disablePopup": True,
                "id": "187e9050b73-layer-118",
                "layerDefinition": {},
                "layerType": "ArcGISSceneServiceLayer",
                "listMode": "show",
                "opacity": 1.0,
                "screenSizePerspective": True,
                "showLabels": False,
                "showLegend": True,
                "timeAnimation": True,
                "title": "Places and Labels",
                "url": "https://basemaps3d.arcgis.com/arcgis/rest/services/OpenStreetMap3D_DarkLabels_v1/SceneServer/layers/0",
                "visibility": True,
            },
            {
                "disablePopup": True,
                "id": "187e902e9f5-layer-117",
                "layerDefinition": {},
                "layerType": "ArcGISSceneServiceLayer",
                "listMode": "show",
                "opacity": 1.0,
                "screenSizePerspective": True,
                "showLabels": False,
                "showLegend": True,
                "timeAnimation": True,
                "title": "Buildings",
                "url": "https://basemaps3d.arcgis.com/arcgis/rest/services/Esri3D_Buildings_v1/SceneServer/layers/0",
                "visibility": True,
            },
        ],
        "id": "187e8fedaab-basemap-36",
        "title": "Navigation",
    },
    "streets-3d": {
        "baseMapLayers": [
            {
                "id": "188f6cabbc4-layer-0",
                "layerType": "VectorTileLayer",
                "opacity": 1.0,
                "styleUrl": "https://cdn.arcgis.com/sharing/rest/content/items/198298c4c64c4cb19de5b46aa00c198d/resources/styles/root.json",
                "title": "Streets",
                "visibility": True,
            },
            {
                "disablePopup": True,
                "id": "188f6c665f1-layer-63",
                "layerDefinition": {},
                "layerType": "ArcGISSceneServiceLayer",
                "listMode": "show",
                "opacity": 1.0,
                "screenSizePerspective": True,
                "showLabels": False,
                "showLegend": True,
                "timeAnimation": True,
                "title": "Places and Labels",
                "url": "https://basemaps3d.arcgis.com/arcgis/rest/services/OpenStreetMap3D_DarkLabels_v1/SceneServer/layers/0",
                "visibility": True,
            },
            {
                "disablePopup": True,
                "id": "188f6ccb089-layer-64",
                "layerDefinition": {},
                "layerType": "ArcGISSceneServiceLayer",
                "listMode": "show",
                "opacity": 1.0,
                "screenSizePerspective": True,
                "showLabels": False,
                "showLegend": True,
                "timeAnimation": True,
                "title": "Buildings",
                "url": "https://basemaps3d.arcgis.com/arcgis/rest/services/Esri3D_Buildings_v1/SceneServer/layers/0",
                "visibility": True,
            },
        ],
        "id": "189012ccb2b-basemap-38",
        "title": "Streets",
    },
    "osm-3d": {
        "baseMapLayers": [
            {
                "id": "18dfc1e01ef-layer-49",
                "layerType": "VectorTileLayer",
                "opacity": 1.0,
                "styleUrl": "https://cdn.arcgis.com/sharing/rest/content/items/8628d259c9d14bdc848771c23c513940/resources/styles/root.json",
                "title": "OpenStreetMap",
                "visibility": True,
            },
            {
                "disablePopup": True,
                "id": "18dfc1e3c1b-layer-50",
                "layerDefinition": {},
                "layerType": "ArcGISSceneServiceLayer",
                "listMode": "show",
                "opacity": 1.0,
                "screenSizePerspective": True,
                "showLabels": False,
                "showLegend": True,
                "timeAnimation": True,
                "title": "Trees",
                "url": "https://basemaps3d.arcgis.com/arcgis/rest/services/OpenStreetMap3D_Trees_Thematic_v1/SceneServer/layers/0",
                "visibility": True,
            },
            {
                "disablePopup": True,
                "id": "18dfc1e7cd5-layer-52",
                "layerDefinition": {},
                "layerType": "ArcGISSceneServiceLayer",
                "listMode": "show",
                "opacity": 1.0,
                "screenSizePerspective": True,
                "showLabels": False,
                "showLegend": True,
                "timeAnimation": True,
                "title": "Places and Labels",
                "url": "https://basemaps3d.arcgis.com/arcgis/rest/services/OpenStreetMap3D_DarkLabels_v1/SceneServer/layers/0",
                "visibility": True,
            },
            {
                "disablePopup": True,
                "id": "18dfc1e591a-layer-51",
                "layerDefinition": {},
                "layerType": "ArcGISSceneServiceLayer",
                "listMode": "show",
                "opacity": 1.0,
                "screenSizePerspective": True,
                "showLabels": False,
                "showLegend": True,
                "timeAnimation": True,
                "title": "Buildings",
                "url": "https://basemaps3d.arcgis.com/arcgis/rest/services/OpenStreetMap3D_Buildings_v1/SceneServer/layers/0",
                "visibility": True,
            },
        ],
        "id": "18dfc17dee0-basemap-27",
        "title": "OpenStreetMap",
    },
    "gray-3d": {
        "baseMapLayers": [
            {
                "id": "189007ef83c-layer-0",
                "layerType": "VectorTileLayer",
                "opacity": 1.0,
                "styleUrl": "https://cdn.arcgis.com/sharing/rest/content/items/01a14b466345455ba4176d2e6390db92/resources/styles/root.json",
                "title": "Light Gray Canvas",
                "visibility": True,
            },
            {
                "disablePopup": True,
                "id": "189007fe854-layer-64",
                "layerDefinition": {},
                "layerType": "ArcGISSceneServiceLayer",
                "listMode": "show",
                "opacity": 1.0,
                "screenSizePerspective": True,
                "showLabels": False,
                "showLegend": True,
                "timeAnimation": True,
                "title": "Places and Labels",
                "url": "https://basemaps3d.arcgis.com/arcgis/rest/services/OpenStreetMap3D_DarkLabels_v1/SceneServer/layers/0",
                "visibility": True,
            },
            {
                "disablePopup": True,
                "id": "189007fb122-layer-63",
                "layerDefinition": {},
                "layerType": "ArcGISSceneServiceLayer",
                "listMode": "show",
                "opacity": 1.0,
                "screenSizePerspective": True,
                "showLabels": False,
                "showLegend": True,
                "timeAnimation": True,
                "title": "Buildings",
                "url": "https://basemaps3d.arcgis.com/arcgis/rest/services/Esri3D_Buildings_v1/SceneServer/layers/0",
                "visibility": True,
            },
        ],
        "id": "189007f0249-basemap-38",
        "title": "Light Gray Canvas",
    },
    "navigation-dark-3d": {
        "baseMapLayers": [
            {
                "id": "187e8fee2e2-layer-0",
                "layerType": "VectorTileLayer",
                "opacity": 1.0,
                "styleUrl": "https://cdn.arcgis.com/sharing/rest/content/items/451a1777ab3f4bf095fae24a117439d9/resources/styles/root.json",
                "title": "Navigation (Dark)",
                "visibility": True,
            },
            {
                "disablePopup": True,
                "id": "187e918bf48-layer-116",
                "layerDefinition": {},
                "layerType": "ArcGISSceneServiceLayer",
                "listMode": "show",
                "opacity": 1.0,
                "screenSizePerspective": True,
                "showLabels": False,
                "showLegend": True,
                "timeAnimation": True,
                "title": "Places and Labels",
                "url": "https://basemaps3d.arcgis.com/arcgis/rest/services/OpenStreetMap3D_LightLabels_v1/SceneServer/layers/0",
                "visibility": True,
            },
            {
                "disablePopup": True,
                "id": "187e918e06c-layer-117",
                "layerDefinition": {
                    "drawingInfo": {
                        "renderer": {
                            "authoringInfo": {},
                            "symbol": {
                                "symbolLayers": [
                                    {
                                        "castShadows": True,
                                        "material": {"color": [55.0, 59.0, 62.0]},
                                        "type": "Fill",
                                    }
                                ],
                                "type": "MeshSymbol3D",
                            },
                            "type": "simple",
                        }
                    },
                    "elevationInfo": {"mode": "relativeToGround", "unit": "meter"},
                },
                "layerType": "ArcGISSceneServiceLayer",
                "listMode": "show",
                "opacity": 1.0,
                "screenSizePerspective": True,
                "showLabels": False,
                "showLegend": True,
                "timeAnimation": True,
                "title": "Buildings",
                "url": "https://basemaps3d.arcgis.com/arcgis/rest/services/Esri3D_Buildings_v1/SceneServer/layers/0",
                "visibility": True,
            },
        ],
        "id": "187e8feecb4-basemap-36",
        "title": "Navigation (Dark)",
    },
    "streets-dark-3d": {
        "baseMapLayers": [
            {
                "id": "188f6beaae0-layer-65",
                "layerType": "VectorTileLayer",
                "opacity": 1.0,
                "styleUrl": "https://cdn.arcgis.com/sharing/rest/content/items/bc599b6d741a4ac084b7eea7bf8c5938/resources/styles/root.json",
                "title": "Streets (Dark)",
                "visibility": True,
            },
            {
                "disablePopup": True,
                "id": "188f6bf48b3-layer-66",
                "layerDefinition": {},
                "layerType": "ArcGISSceneServiceLayer",
                "listMode": "show",
                "opacity": 1.0,
                "screenSizePerspective": True,
                "showLabels": False,
                "showLegend": True,
                "timeAnimation": True,
                "title": "Places and Labels",
                "url": "https://basemaps3d.arcgis.com/arcgis/rest/services/OpenStreetMap3D_LightLabels_v1/SceneServer/layers/0",
                "visibility": True,
            },
            {
                "disablePopup": True,
                "id": "188f6bc8733-layer-63",
                "layerDefinition": {
                    "drawingInfo": {
                        "renderer": {
                            "authoringInfo": {},
                            "symbol": {
                                "symbolLayers": [
                                    {
                                        "castShadows": True,
                                        "material": {"color": [63.0, 67.0, 74.0]},
                                        "type": "Fill",
                                    }
                                ],
                                "type": "MeshSymbol3D",
                            },
                            "type": "simple",
                        }
                    },
                    "elevationInfo": {"mode": "relativeToGround", "unit": "meter"},
                },
                "layerType": "ArcGISSceneServiceLayer",
                "listMode": "show",
                "opacity": 1.0,
                "screenSizePerspective": True,
                "showLabels": False,
                "showLegend": True,
                "timeAnimation": True,
                "title": "Buildings",
                "url": "https://basemaps3d.arcgis.com/arcgis/rest/services/Esri3D_Buildings_v1/SceneServer/layers/0",
                "visibility": True,
            },
        ],
        "id": "188fb97e335-basemap-38",
        "title": "Streets (Dark)",
    },
    "dark-gray-3d": {
        "baseMapLayers": [
            {
                "id": "18900921725-layer-0",
                "layerType": "VectorTileLayer",
                "opacity": 1.0,
                "styleUrl": "https://cdn.arcgis.com/sharing/rest/content/items/4178f71acb934fb89f169e7d667c20c6/resources/styles/root.json",
                "title": "Dark Gray Canvas",
                "visibility": True,
            },
            {
                "disablePopup": True,
                "id": "1890092f8c2-layer-64",
                "layerDefinition": {},
                "layerType": "ArcGISSceneServiceLayer",
                "listMode": "show",
                "opacity": 1.0,
                "screenSizePerspective": True,
                "showLabels": False,
                "showLegend": True,
                "timeAnimation": True,
                "title": "Places and Labels",
                "url": "https://basemaps3d.arcgis.com/arcgis/rest/services/OpenStreetMap3D_LightLabels_v1/SceneServer/layers/0",
                "visibility": True,
            },
            {
                "disablePopup": True,
                "id": "1890093eabc-layer-65",
                "layerDefinition": {
                    "drawingInfo": {
                        "renderer": {
                            "authoringInfo": {},
                            "symbol": {
                                "symbolLayers": [
                                    {
                                        "castShadows": True,
                                        "material": {"color": [69.0, 75.0, 82.0]},
                                        "type": "Fill",
                                    }
                                ],
                                "type": "MeshSymbol3D",
                            },
                            "type": "simple",
                        }
                    },
                    "elevationInfo": {"mode": "relativeToGround", "unit": "meter"},
                },
                "layerType": "ArcGISSceneServiceLayer",
                "listMode": "show",
                "opacity": 1.0,
                "screenSizePerspective": True,
                "showLabels": False,
                "showLegend": True,
                "timeAnimation": True,
                "title": "Buildings",
                "url": "https://basemaps3d.arcgis.com/arcgis/rest/services/Esri3D_Buildings_v1/SceneServer/layers/0",
                "visibility": True,
            },
        ],
        "id": "1890092201e-basemap-38",
        "title": "Dark Gray Canvas",
    },
}
