#! /usr/bin/env python3
#
# Copyright (C) 2023  Michael Gale
# This file is part of the cq-gridfinity python module.
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without restriction,
# including without limitation the rights to use, copy, modify, merge,
# publish, distribute, sublicense, and/or sell copies of the Software,
# and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# Gridfinity base object class

import math
import os

import cadquery as cq

from microfinity.core.constants import (
    GRHU,
    GRU,
    GRU2,
    GR_BOT_H,
    GR_FILLET,
    GR_FLOOR,
    GR_HOLE_D,
    GR_HOLE_DIST,
    GR_LIP_H,
    GR_RAD,
    GR_TOL,
    GR_TOPSIDE_H,
    GR_UNDER_H,
    GR_WALL,
    SQRT2,
)
from microfinity.core.export import GridfinityExporter, SVGView

# Special test to see which version of CadQuery is installed and
# therefore if any compensation is required for extruded zlen
# CQ versions < 2.4.0 typically require zlen correction, i.e.
# scaling the vertical extrusion extent by 1/cos(taper)
ZLEN_FIX = True
_r = cq.Workplane("XY").rect(2, 2).extrude(1, taper=45)
_bb = _r.vals()[0].BoundingBox()
if abs(_bb.zlen - 1.0) < 1e-3:
    ZLEN_FIX = False


class GridfinityObject:
    """Base Gridfinity object class

    This class bundles glabally relevant constants, properties, and methods
    for derived Gridfinity object classes.

    Micro-grid support:
        micro_divisions: int (1, 2, or 4) - Enables quarter-grid positioning.
            - 1 = standard Gridfinity (default)
            - 2 = half-grid (21mm pitch)
            - 4 = quarter-grid (10.5mm pitch)

        When micro_divisions > 1:
            - length_u and width_u can be fractional (multiples of 1/micro_divisions)
            - Underside features include micro-boundary grooves for 0.25U positioning
            - Outer envelope remains phase-locked to the 42mm macro grid
    """

    def __init__(self, **kwargs):
        self.length_u = 1
        self.width_u = 1
        self.height_u = 1
        self.micro_divisions = 1  # 1=standard, 2=half-grid, 4=quarter-grid
        self._cq_obj = None
        self._obj_label = None
        for k, v in kwargs.items():
            if k in self.__dict__:
                self.__dict__[k] = v
        # Validate micro_divisions
        if self.micro_divisions not in (1, 2, 4):
            raise ValueError("micro_divisions must be 1, 2, or 4")
        # Validate fractional sizes align with micro_divisions
        if self.micro_divisions > 1:
            step = 1.0 / self.micro_divisions
            if abs(self.length_u / step - round(self.length_u / step)) > 1e-6:
                raise ValueError(
                    f"length_u={self.length_u} must be a multiple of {step} "
                    f"when micro_divisions={self.micro_divisions}"
                )
            if abs(self.width_u / step - round(self.width_u / step)) > 1e-6:
                raise ValueError(
                    f"width_u={self.width_u} must be a multiple of {step} "
                    f"when micro_divisions={self.micro_divisions}"
                )

    @property
    def cq_obj(self):
        if self._cq_obj is None:
            return self.render()
        return self._cq_obj

    @property
    def length(self):
        return self.length_u * GRU

    @property
    def width(self):
        return self.width_u * GRU

    @property
    def height(self):
        return 3.8 + GRHU * self.height_u

    @property
    def int_height(self):
        h = self.height - GR_LIP_H - GR_BOT_H
        if self.lite_style:
            return h + self.wall_th
        return h

    @property
    def max_height(self):
        return self.int_height + GR_UNDER_H + GR_TOPSIDE_H

    @property
    def floor_h(self):
        if self.lite_style:
            return GR_FLOOR - self.wall_th
        return GR_FLOOR

    @property
    def lip_width(self):
        if self.no_lip:
            return self.wall_th
        return GR_UNDER_H + self.wall_th

    @property
    def micro_pitch(self):
        """Returns the micro-pitch in mm for current micro_divisions setting."""
        return GRU / self.micro_divisions

    @property
    def outer_l(self):
        return self.length_u * GRU - GR_TOL

    @property
    def outer_w(self):
        return self.width_u * GRU - GR_TOL

    @property
    def macro_length_u(self):
        """Ceiling of length_u for macro feature replication."""
        return math.ceil(self.length_u)

    @property
    def macro_width_u(self):
        """Ceiling of width_u for macro feature replication."""
        return math.ceil(self.width_u)

    @property
    def outer_dim(self):
        return self.outer_l, self.outer_w

    @property
    def inner_l(self):
        return self.outer_l - 2 * self.wall_th

    @property
    def inner_w(self):
        return self.outer_w - 2 * self.wall_th

    @property
    def inner_dim(self):
        return self.inner_l, self.inner_w

    @property
    def half_l(self):
        return (self.length_u - 1) * GRU2

    @property
    def half_w(self):
        return (self.width_u - 1) * GRU2

    @property
    def half_dim(self):
        return self.half_l, self.half_w

    @property
    def half_in(self):
        return GRU2 - self.wall_th - GR_TOL / 2

    @property
    def outer_rad(self):
        return GR_RAD - GR_TOL / 2

    @property
    def inner_rad(self):
        return self.outer_rad - self.wall_th

    @property
    def under_h(self):
        return GR_UNDER_H - (self.wall_th - GR_WALL)

    @property
    def safe_fillet_rad(self):
        if not any([self.scoops, self.labels, self.length_div, self.width_div]):
            return GR_FILLET
        return min(GR_FILLET, (GR_UNDER_H + GR_WALL) - self.wall_th - 0.05)

    @property
    def grid_centres(self):
        """Returns center points for macro grid cells.

        For fractional sizes, uses ceiling to ensure full coverage of feet,
        which are then cropped by the outer envelope intersection.
        """
        return [(x * GRU, y * GRU) for x in range(self.macro_length_u) for y in range(self.macro_width_u)]

    @property
    def micro_grid_centres(self):
        """Returns center points for micro-grid cells.

        Positions micro feet at micro_pitch intervals, with outermost feet
        extending GR_TOL/2 (0.25mm) past the envelope boundary. This matches
        how 1U feet work: they're created at 42mm but cropped by the 41.5mm
        envelope, putting the profile 0.25mm "into" the chamfer at the edge.

        The envelope intersection (in render_shell) crops the outermost feet,
        producing identical chamfer profiles at the boundary for both 1U and
        micro feet.

        Key insight: micro feet are created at micro_pitch size (10.5mm), not
        micro_pitch - GR_TOL (10.0mm). The 0.5mm gaps between adjacent feet
        come from their chamfered profiles overlapping/merging, not from the
        foot size being smaller than the pitch.
        """
        if self.micro_divisions <= 1:
            return self.grid_centres

        # Use epsilon-safe integer conversion (consistent with validation in __init__)
        v_l = self.length_u * self.micro_divisions
        v_w = self.width_u * self.micro_divisions
        micro_count_l = int(round(v_l))
        micro_count_w = int(round(v_w))

        # Micro foot size matches micro_pitch (like 1U feet match GRU)
        # The envelope intersection will crop the outermost feet
        foot_size = self.micro_pitch  # 10.5mm for divisions=4

        # Position feet so outermost foot edges extend GR_TOL/2 past envelope
        # This matches 1U behavior: feet at 42mm, envelope at 41.5mm
        # After cropping, the chamfer profile is 0.25mm "in" at the edge
        env_min_l = -self.outer_l / 2
        env_min_w = -self.outer_w / 2

        # First foot center: half foot size from envelope edge
        # (foot edge will be at env_min - GR_TOL/2, gets cropped to env_min)
        first_l = env_min_l + foot_size / 2 - GR_TOL / 2
        first_w = env_min_w + foot_size / 2 - GR_TOL / 2

        # Generate centres, offset by half_l/half_w to match bin coordinate system
        return [
            (first_l + x * self.micro_pitch + self.half_l, first_w + y * self.micro_pitch + self.half_w)
            for x in range(micro_count_l)
            for y in range(micro_count_w)
        ]

    @property
    def hole_centres(self):
        """Returns center points for magnet/screw holes.

        Holes are placed only at macro corners. For fractional sizes,
        only holes that fall within the actual bin envelope are included.
        """
        # For fractional bins, we need to filter holes that fall outside
        # the actual footprint
        half_env_l = self.outer_l / 2
        half_env_w = self.outer_w / 2
        centres = []
        for x in range(self.macro_length_u):
            for y in range(self.macro_width_u):
                for i in (-1, 1):
                    for j in (-1, 1):
                        hx = x * GRU - GR_HOLE_DIST * i
                        hy = -(y * GRU - GR_HOLE_DIST * j)
                        # Check if hole falls within the actual envelope
                        # (with some margin for the hole radius)
                        if (
                            abs(hx - self.half_l) <= half_env_l - GR_HOLE_D / 2 - 0.5
                            and abs(hy + self.half_w) <= half_env_w - GR_HOLE_D / 2 - 0.5
                        ):
                            centres.append((hx, hy))
        return centres

    def safe_fillet(self, obj, selector, rad):
        if len(obj.edges(selector).vals()) > 0:
            return obj.edges(selector).fillet(rad)
        return obj

    def filename(self, prefix=None, path=None):
        """Returns a descriptive readable filename which represents a Gridfinity object.
        The filename can be optionally prefixed with arbitrary text and
        an optional path prefix can also be specified."""
        from microfinity import (
            GridfinityBaseplate,
            GridfinityBox,
            GridfinityDrawerSpacer,
        )

        if prefix is not None:
            prefix = prefix
        elif isinstance(self, GridfinityBaseplate):
            prefix = "gf_baseplate_"
        elif isinstance(self, GridfinityBox):
            prefix = "gf_box_"
            if self.lite_style:
                prefix = prefix + "lite_"
        elif isinstance(self, GridfinityDrawerSpacer):
            prefix = "gf_drawer_"
        else:
            prefix = ""
        fn = ""
        if path is not None:
            fn = fn.replace(os.sep, "")
            fn = path + os.sep
        fn = fn + prefix
        # Handle fractional sizes with micro-grid
        if self.length_u == int(self.length_u) and self.width_u == int(self.width_u):
            fn = fn + "%dx%d" % (int(self.length_u), int(self.width_u))
        else:
            fn = fn + "%.2fx%.2f" % (self.length_u, self.width_u)
        if self.micro_divisions > 1:
            fn = fn + "_micro%d" % (self.micro_divisions)
        if isinstance(self, GridfinityBox):
            fn = fn + "x%d" % (self.height_u)
            if self.length_div and not self.solid:
                fn = fn + "_div%d" % (self.length_div)
            if self.width_div and not self.solid:
                if self.length_div:
                    fn = fn + "x%d" % (self.width_div)
                else:
                    fn = fn + "_div_x%d" % (self.width_div)
            if abs(self.wall_th - GR_WALL) > 1e-3:
                fn = fn + "_%.2f" % (self.wall_th)
            if self.no_lip:
                fn = fn + "_basic"
            if self.holes:
                fn = fn + "_holes"
            if self.solid:
                fn = fn + "_solid"
            else:
                if self.scoops:
                    fn = fn + "_scoops"
                if self.labels:
                    fn = fn + "_labels"
        elif isinstance(self, GridfinityDrawerSpacer):
            if self._obj_label is not None:
                fn = fn + "_%s" % (self._obj_label)
        elif isinstance(self, GridfinityBaseplate):
            if self.ext_depth > 0:
                fn = fn + "x%.1f" % (self.ext_depth)
            if self.corner_screws:
                fn = fn + "_screwtabs"
        return fn

    def save_step_file(self, filename=None, path=None, prefix=None) -> str:
        """Save rendered geometry to STEP file.

        Args:
            filename: Output filename (auto-generated if None)
            path: Directory path prefix
            prefix: Filename prefix

        Returns:
            Absolute path to exported file
        """
        fn = filename if filename is not None else self.filename(path=path, prefix=prefix)
        return GridfinityExporter.to_step(self.cq_obj, fn)

    def save_stl_file(
        self,
        filename=None,
        path=None,
        prefix=None,
        tol: float = 1e-2,
        ang_tol: float = 0.1,
    ) -> str:
        """Save rendered geometry to STL file.

        Args:
            filename: Output filename (auto-generated if None)
            path: Directory path prefix
            prefix: Filename prefix
            tol: Linear mesh tolerance
            ang_tol: Angular mesh tolerance

        Returns:
            Absolute path to exported file
        """
        fn = filename if filename is not None else self.filename(path=path, prefix=prefix)
        return GridfinityExporter.to_stl(self.cq_obj, fn, tol, ang_tol)

    def save_svg_file(
        self,
        filename=None,
        path=None,
        prefix=None,
        view: SVGView = SVGView.ISOMETRIC,
    ) -> str:
        """Save SVG projection of rendered geometry.

        Args:
            filename: Output filename (auto-generated if None)
            path: Directory path prefix
            prefix: Filename prefix
            view: View orientation preset

        Returns:
            Absolute path to exported file
        """
        fn = filename if filename is not None else self.filename(path=path, prefix=prefix)
        return GridfinityExporter.to_svg(self.cq_obj, fn, view=view)

    def extrude_profile(self, sketch, profile, workplane="XY", angle=None):
        taper = profile[0][1] if isinstance(profile[0], (list, tuple)) else 0
        zlen = profile[0][0] if isinstance(profile[0], (list, tuple)) else profile[0]
        if abs(taper) > 0:
            if angle is None:
                zlen = zlen if ZLEN_FIX else zlen / SQRT2
            else:
                zlen = zlen / math.cos(math.radians(taper)) if ZLEN_FIX else zlen
        r = cq.Workplane(workplane).placeSketch(sketch).extrude(zlen, taper=taper)
        for level in profile[1:]:
            if isinstance(level, (tuple, list)):
                if angle is None:
                    zlen = level[0] if ZLEN_FIX else level[0] / SQRT2
                else:
                    zlen = level[0] / math.cos(math.radians(level[1])) if ZLEN_FIX else level[0]
                r = r.faces(">Z").wires().toPending().extrude(zlen, taper=level[1])
            else:
                r = r.faces(">Z").wires().toPending().extrude(level)
        return r

    @classmethod
    def to_step_file(cls, length_u, width_u, height_u=None, filename=None, prefix=None, path=None, **kwargs) -> str:
        """Convenience method to create, render and save a STEP file.

        Returns:
            Absolute path to exported file
        """
        obj = GridfinityObject.as_obj(cls, length_u, width_u, height_u, **kwargs)
        return obj.save_step_file(filename=filename, path=path, prefix=prefix)

    @classmethod
    def to_stl_file(cls, length_u, width_u, height_u=None, filename=None, prefix=None, path=None, **kwargs) -> str:
        """Convenience method to create, render and save an STL file.

        Returns:
            Absolute path to exported file
        """
        obj = GridfinityObject.as_obj(cls, length_u, width_u, height_u, **kwargs)
        return obj.save_stl_file(filename=filename, path=path, prefix=prefix)

    @staticmethod
    def as_obj(cls, length_u=None, width_u=None, height_u=None, **kwargs):
        from microfinity import GridfinityBaseplate, GridfinityBox, GridfinityDrawerSpacer

        if "GridfinityBox" in cls.__name__:
            obj = GridfinityBox(length_u, width_u, height_u, **kwargs)
            if "GridfinitySolidBox" in cls.__name__:
                obj.solid = True
        elif "GridfinityBaseplate" in cls.__name__:
            obj = GridfinityBaseplate(length_u, width_u, **kwargs)
        elif "GridfinityDrawerSpacer" in cls.__name__:
            obj = GridfinityDrawerSpacer(**kwargs)
        return obj
