# coding: utf-8

"""
    Asset Storage API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aurigma.asset_storage.models.create_tenant_dto import CreateTenantDto

class TestCreateTenantDto(unittest.TestCase):
    """CreateTenantDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateTenantDto:
        """Test CreateTenantDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateTenantDto`
        """
        model = CreateTenantDto()
        if include_optional:
            return CreateTenantDto(
                id = 56,
                settings = aurigma.asset_storage.models.tenant_settings_dto.TenantSettingsDto(
                    enable_assets_retention = True, 
                    assets_retention_period_in_days = 56, ),
                name = '1GZqFNGtlr{] Ug=C.AG=00',
                custom_fields = {
                    'key' : null
                    }
            )
        else:
            return CreateTenantDto(
                id = 56,
                name = '1GZqFNGtlr{] Ug=C.AG=00',
        )
        """

    def testCreateTenantDto(self):
        """Test CreateTenantDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
