"""Module for switch implementations."""

from .arista.arista_7050 import Arista7050
from .arista.base import Arista
from .brocade.base import Fabos
from .cisco.base import Cisco
from .cisco.nx_os import Cisco_NXOS
from .cisco.os_4000 import CiscoOS4000
from .cisco.os_6500 import CiscoOS6500
from .dell.dell_os9 import DellOS9
from .dell.dell_os10 import DellOS10
from .dell.dell_os9 import DellOS9_7000
from .dell.dell_os9 import DellOS9_8132
from .dell.dell_os9 import DellOS9_Force10
from .dell.dell_os9 import DellOS9_S4128
from .dell.dell_os9 import DellOS9_S5048
from .extreme.base import Extreme
from .extreme.extreme_exos import ExtremeExos
from .ibm.base import IBM
from .junos.base import Junos
from .mellanox.base import Mellanox
from .mellanox.mellanox_25G import Mellanox25G
from .ovs.base import Ovs
