# coding: utf-8

"""
    Arthur GenAI Engine

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.294
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from _generated.models.hallucination_details_response import HallucinationDetailsResponse

class TestHallucinationDetailsResponse(unittest.TestCase):
    """HallucinationDetailsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HallucinationDetailsResponse:
        """Test HallucinationDetailsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HallucinationDetailsResponse`
        """
        model = HallucinationDetailsResponse()
        if include_optional:
            return HallucinationDetailsResponse(
                score = True,
                message = '',
                claims = [
                    _generated.models.hallucination_claim_response.HallucinationClaimResponse(
                        claim = '', 
                        valid = True, 
                        reason = '', 
                        order_number = 56, )
                    ]
            )
        else:
            return HallucinationDetailsResponse(
                claims = [
                    _generated.models.hallucination_claim_response.HallucinationClaimResponse(
                        claim = '', 
                        valid = True, 
                        reason = '', 
                        order_number = 56, )
                    ],
        )
        """

    def testHallucinationDetailsResponse(self):
        """Test HallucinationDetailsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
