# coding: utf-8

"""
    Arthur GenAI Engine

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.294
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from _generated.models.saved_rag_config_input import SavedRagConfigInput

class TestSavedRagConfigInput(unittest.TestCase):
    """SavedRagConfigInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SavedRagConfigInput:
        """Test SavedRagConfigInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SavedRagConfigInput`
        """
        model = SavedRagConfigInput()
        if include_optional:
            return SavedRagConfigInput(
                type = 'saved',
                setting_configuration_id = '',
                version = 56,
                query_column = _generated.models.dataset_column_variable_source.DatasetColumnVariableSource(
                    type = 'dataset_column', 
                    dataset_column = _generated.models.dataset_column_source.DatasetColumnSource(
                        name = '', ), )
            )
        else:
            return SavedRagConfigInput(
                setting_configuration_id = '',
                version = 56,
                query_column = _generated.models.dataset_column_variable_source.DatasetColumnVariableSource(
                    type = 'dataset_column', 
                    dataset_column = _generated.models.dataset_column_source.DatasetColumnSource(
                        name = '', ), ),
        )
        """

    def testSavedRagConfigInput(self):
        """Test SavedRagConfigInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
