# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.unchecked_base_model import UncheckedBaseModel
from .rating_definition_params_field_configuration import RatingDefinitionParamsFieldConfiguration


class RatingDefinitionParams(UncheckedBaseModel):
    field_configuration: RatingDefinitionParamsFieldConfiguration
    name: str = pydantic.Field()
    """
    Field definition name
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
