import pytest
import mcpath


@pytest.mark.xfail(
    raises=NotImplementedError, reason="Feature not supported on this platform"
)
def test_preview_gdk():
    resultA = mcpath.previewGDK.get_users()
    resultB = mcpath.previewGDK.get_root_dir()
    resultC = mcpath.previewGDK.get_game_dir()
    resultD = mcpath.previewGDK.get_worlds_dir()
    resultE = mcpath.previewGDK.get_world_templates_dir()
    resultF = mcpath.previewGDK.get_resource_packs_dir()
    resultG = mcpath.previewGDK.get_behavior_packs_dir()
    resultH = mcpath.previewGDK.get_skin_packs_dir()
    resultI = mcpath.previewGDK.get_development_resource_packs_dir()
    resultJ = mcpath.previewGDK.get_development_behavior_packs_dir()
    resultK = mcpath.previewGDK.get_development_skin_packs_dir()
    resultL = mcpath.previewGDK.get_custom_skins_dir()
    resultM = mcpath.previewGDK.get_screenshots_dir()
    resultN = mcpath.previewGDK.get_worlds()
    resultO = mcpath.previewGDK.get_behavior_packs()
    resultP = mcpath.previewGDK.get_resource_packs()
    resultQ = mcpath.previewGDK.get_development_behavior_packs()
    resultR = mcpath.previewGDK.get_development_resource_packs()
    resultS = mcpath.previewGDK.get_development_skin_packs()
    resultT = mcpath.previewGDK.get_screenshots()

    assert not resultB or isinstance(resultB, str)
    assert not resultC or isinstance(resultC, str)
    assert not resultD or isinstance(resultD, str)
    assert not resultE or isinstance(resultE, str)
    assert not resultF or isinstance(resultF, str)
    assert not resultG or isinstance(resultG, str)
    assert not resultH or isinstance(resultH, str)
    assert not resultI or isinstance(resultI, str)
    assert not resultJ or isinstance(resultJ, str)
    assert not resultK or isinstance(resultK, str)
    assert not resultL or isinstance(resultL, str)
    assert not resultM or isinstance(resultM, str)
    assert isinstance(resultA, list)
    assert isinstance(resultN, list)
    assert isinstance(resultO, list)
    assert isinstance(resultP, list)
    assert isinstance(resultQ, list)
    assert isinstance(resultR, list)
    assert isinstance(resultS, list)
    assert isinstance(resultT, list)


@pytest.mark.xfail(
    raises=NotImplementedError, reason="Feature not supported on this platform"
)
def test_preview_uwp():
    resultA = mcpath.previewUWP.get_game_dir()
    resultB = mcpath.previewUWP.get_worlds_dir()
    resultC = mcpath.previewUWP.get_world_templates_dir()
    resultD = mcpath.previewUWP.get_resource_packs_dir()
    resultE = mcpath.previewUWP.get_behavior_packs_dir()
    resultF = mcpath.previewUWP.get_skin_packs_dir()
    resultG = mcpath.previewUWP.get_development_resource_packs_dir()
    resultH = mcpath.previewUWP.get_development_behavior_packs_dir()
    resultI = mcpath.previewUWP.get_development_skin_packs_dir()
    resultJ = mcpath.previewUWP.get_custom_skins_dir()
    resultK = mcpath.previewUWP.get_screenshots_dir()
    resultL = mcpath.previewUWP.get_worlds()
    resultM = mcpath.previewUWP.get_behavior_packs()
    resultN = mcpath.previewUWP.get_resource_packs()
    resultO = mcpath.previewUWP.get_development_behavior_packs()
    resultP = mcpath.previewUWP.get_development_resource_packs()
    resultQ = mcpath.previewUWP.get_development_skin_packs()
    resultR = mcpath.previewUWP.get_screenshots()

    assert not resultA or isinstance(resultA, str)
    assert not resultB or isinstance(resultB, str)
    assert not resultC or isinstance(resultC, str)
    assert not resultD or isinstance(resultD, str)
    assert not resultE or isinstance(resultE, str)
    assert not resultF or isinstance(resultF, str)
    assert not resultG or isinstance(resultG, str)
    assert not resultH or isinstance(resultH, str)
    assert not resultI or isinstance(resultI, str)
    assert not resultJ or isinstance(resultJ, str)
    assert not resultK or isinstance(resultK, str)
    assert isinstance(resultL, list)
    assert isinstance(resultM, list)
    assert isinstance(resultN, list)
    assert isinstance(resultO, list)
    assert isinstance(resultP, list)
    assert isinstance(resultQ, list)
    assert isinstance(resultR, list)
