# this might be a bit much...
HEADER_QUOTES = [
    "Science is what we understand well enough to explain to a computer. Art is everything else we do. (Knuth, 1995)",  # https://www2.math.upenn.edu/~wilf/foreword.pdf
    "Science advances whenever an Art becomes a Science. (Knuth, 1995)",
    "If a machine is expected to be infallible, it cannot also be intelligent. (Turing, 1947)",  # https://plato.stanford.edu/entries/turing/
    "I believe that in about fifty years' time it will be possible to programme computers, with a storage capacity of about 10^9, to make them play the imitation game so well that an average interrogator will not have more than 70 per cent chance of making the right identification after five minutes of questioning. (Turing, 1950)",
    "Machines take me by suprise with great frequency. This is largely because I do not do sufficient calculation to decide what to expect them to do, or rather because, although I do a calculation, I do it in a hurried, slipshod fashion, taking risks. (Turing, 1950)",
    "We offer no explanation as to why these architectures seem to work; we attribute their success, as all else, to divine benevolence. (Shazeer, 2020)",
    "OLMo_θ(x)=softmax(H^L W_O), H^L=f^L∘f^{L-1}∘...∘f^1(E), E=W_Ex + W_Pt, Attn(Q,K,V)=softmax( QK^T / √d_k )V, Q=XW_Q, K=XW_K, V=XW_V, H=concat(H_1, ..., H_h)W_O, H^l = LN(H^{l-1} + Attn(Q,K,V)), Z^l = LN(H^l + FFN(H^l)), FFN(x)=max(0, xW_1+b_1)W_2+b_2, L=-∑ylog(ŷ), θ←θ-η∇L",
    "http://www.ai.mit.edu/lab/gsb/gsl-archive/gsl95-12dec08.html (I found this on Lilian Lee's website)",
    "Thus we may have knowledge of the past but cannot control it; we may control the future but have no knowledge of it. (Shannon, 1959)",  # https://www.gwern.net/docs/cs/1959-shannon.pdf
    "What's the relation between how I think and how I think I think? (Minsky, 1979)",
    "My wife still uses Emacs, which is the most contentious point in our marriage. (Weinberger, 2024)",  # https://quotes.cs.cornell.edu
    "Our modest goal is world domination. (Patterson, 2015, describing the RISC-V project)",  # https://quotes.cs.cornell.edu/speaker/Dave-Patterson/
    "A picture is worth a thousand words, a video is worth a thousand pictures and a demo a thousand videos. So we're up to, um, ten to the nine. (LeCun, 2004)",  # https://quotes.cs.cornell.edu/speaker/Yann--LeCun/
    "Although perhaps of no practical importance, the question is of theoretical interest, and it is hoped that a satisfactory solution of this problem will act as a wedge in attacking other problems of a similar nature and of greater significance. (Shannon on Chess, 1950)",  # https://vision.unipv.it/IA1/ProgrammingaComputerforPlayingChess.pdf
    "What is now proved was once only imagined. (William Blake, 1790)",
    "There ain't no such thing as a free lunch",  # https://ieeexplore.ieee.org/document/585893 (Wolpert & Macready, 2002) -- Although AFAIK the quote came before the term was adopted by the field
    "From one gut feeling I derive much consolation: I suspect that machines to be programmed in our native tongues — be it Dutch, English, American, French, German, or Swahili — are as damned difficult to make as they would be to use. (Dijkstra, 1978)",  # https://www.cs.utexas.edu/~EWD/transcriptions/EWD06xx/EWD667.html
    "Instruction tables will have to be made up by mathematicians with computing experience and perhaps a certain puzzle-solving ability… This process of constructing instruction tables should be very fascinating. There need be no real danger of it ever becoming a drudge, for any processes that are quite mechanical may be turned over to the machine itself. (Turing, 1945)",  # https://people.csail.mit.edu/asolar/SynthesisCourse/Lecture1.htm
    "The fundamental problem of communication is that of reproducing at one point either exactly or approximately a message selected at another point. (Shannon, 1948)",  # https://people.math.harvard.edu/~ctm/home/text/others/shannon/entropy/entropy.pdf
    "An article about computational science in a scientific publication is not the scholarship itself, it is merely advertising of the scholarship. The actual scholarship is the complete software development environment and the complete set of instructions which generated the figures. (Buckheit & Donoho, 1995)",  # https://link.springer.com/chapter/10.1007/978-1-4612-2544-7_5 -- Originally found on https://arxiv.org/pdf/2409.11363#page=2.10
    "Deep Learning waves have lapped at the shores of computational linguistics for several years now, but 2015 seems like the year when the full force of the tsunami hit the major Natural Language Processing (NLP) conferences. However, some pundits are predicting that the final damage will be even worse. (Manning, 2015)",  # https://watermark02.silverchair.com/coli_a_00239.pdf
    "Overall, I think we should feel excited and glad to live in a time when Natural Language Processing is seen as so central to both the further development of machine learning and industry application problems. The future is bright. However, I would encourage everyone to think about problems, architectures, cognitive science, and the details of human language, how it is learned, processed, and how it changes, rather than just chasing state-of-the-art numbers on a benchmark task (Manning, 2015).",  # https://watermark02.silverchair.com/coli_a_00239.pdf
    "I think that the most exciting areas over the next five years will be really understanding text and videos. I will be disappointed if in five years’ time we do not have something that can watch a YouTube video and tell a story about what happened. In a few years time we will put [Deep Learning] on a chip that fits into someone’s ear and have an English-decoding chip that’s just like a real Babel fish. (Hinton, 2014 in a Reddit AMA)",  # https://www.reddit.com/r/MachineLearning/comments/2lmo0l/ama_geoffrey_hinton
    "Intellectually I think that NLP is fascinating, allowing us to focus on highly structured inference problems, on issues that go to the core of ‘what is thought’ but remain eminently practical, and on a technology that surely would make the world a better place (Michael Jordan, 2014)",  # https://watermark02.silverchair.com/coli_a_00239.pdf <- Referenced here
    "DL appears outwardly to be driven entirely by engineering concerns, but its connectionist roots are still strong and, as Pater documents, connectionism was founded on many of the same core principles as modern linguistics. Both fields can achieve more if they work together (Potts, 2018).",  # https://web.stanford.edu/~cgpotts/temp/pater-commentary-by-potts.pdf
    "Verification, the key to AI (Sutton, 2001)", # https://dennyzhou.github.io/LLM-Reasoning-Stanford-CS-25.pdf#page=22
    "The truth always turns out to be simpler than you thought. (Feynman)", # https://www.math.ucla.edu/~tao/quotes.html
    "Meaning is not a unique property of language, but a general characteristic of human activity ... We cannot say that each morpheme or word has a single or central meaning, or even that it has a continuous or coherent range of meanings ... there are two separate uses and meanings of language – the concrete ... and the abstract (Harris, Distributional Structure 1954).)", # https://aclanthology.org/2020.emnlp-main.703
    "In order to talk about concepts, we must understand the importance of mental models... we set up a model of the world which serves as a framework in which to organize our thoughts. We abstract the presence of particular objects, having properties, and entering into events and relationships (Winograd, 1971).", # https://aclanthology.org/2020.emnlp-main.703
    "The risk of a wrong decision is preferable to the terror of indecision. (Maimonides, 1135-1204)", # https://youtu.be/G4_C5pyiS9A?t=1159
    "Reports that say that something hasn't happened are always interesting to me, because as we know, there are known knowns; there are things we know we know. We also know there are known unknowns; that is to say we know there are some things we do not know. But there are also unknown unknowns—the ones we don't know we don't know. And if one looks throughout the history of our country and other free countries, it is the latter category that tends to be the difficult ones (Rumsfeld, 2002)", # https://en.wikipedia.org/wiki/There_are_unknown_unknowns
    "Although this wave of popularity is certainly pleasant and exciting for those of us working in the field, it carries at the same time an element of danger... It will be all too easy for our somewhat artificial prosperity to collapse overnight when it is realized that the use of a few exciting words like information, entropy, redundancy, do not solve all our problems (Shannon on the popularity of information theory, 1956).", # https://aclanthology.org/J10-4001
    "It is fair to assume that neither [(1) “Colorless green ideas sleep furiously”] nor [(2) “Furiously sleep ideas green colorless”] (nor indeed any part of these sentences) has ever occurred in an English discourse. Hence, in any statistical model for grammaticalness, these sentences will be ruled out on identical grounds as equally 'remote' from English. Yet (1), though nonsensical, is grammatical, while (2) is not (Ye olde spicy opinion, 1957).", # https://aclanthology.org/J10-4001
]