from ...datamodels.DataModel import DataModel as DataModel
from ...datamodels.PrimaryDataObject import DataObjectTypeEnum as DataObjectTypeEnum, PrimaryDataObject as PrimaryDataObject
from ..Company import Division as Division
from .Formation import Formation as Formation
from dataclasses import dataclass, field
from typing import ClassVar

@dataclass
class StratColumn(PrimaryDataObject):
    description: str | None = ...
    division: Division | None = ...
    basin: str | None = ...
    formations: list[Formation] = field(default_factory=list[Formation])
    archive_dir_name: ClassVar[str] = ...
    archive_json_filename: ClassVar[str] = ...
    def copy_ids_from(self, source: DataModel): ...
    @property
    def data_object_type(self) -> DataObjectTypeEnum: ...
    @property
    def full_name(self) -> str: ...

@dataclass
class StratColumnEntry(DataModel):
    division: Division | None = ...
    description: str | None = ...
    row_version: str | None = ...
