# interfaces/logger_interface.py
from typing import Protocol

class IDockerHandler(Protocol):
    def get_image_name_and_version(self, tags) -> None: ...
    def create_port_item(port, binding) -> None: ...
    def create_container_log(container_data) -> None: ...
    def get_current_container_info() -> None: ...
    def set_container_metadata(image_name_env_key, image_version_env_key) -> None: ...
    def get_container_metadata() -> None: ...
