# interfaces/env_handler_interface.py
from typing import Optional, Protocol

class IEnvHandler(Protocol):
    def set_logger(self, logger) -> None: ...
    def val_str(self, value: Optional[object]) -> str: ...
    def is_value_null_or_empty(self, value: Optional[str]) -> bool: ...
    def get_env_value(self, key: str) -> Optional[str]: ...
    def get_env_value_secret(self, key: str, file_key: str) -> str: ...
