from amsdal.contrib.auth.models.user import User as User
from amsdal.models.mixins import TimestampMixin as TimestampMixin
from amsdal_models.classes.data_models.indexes import IndexInfo
from amsdal_models.classes.model import Model
from amsdal_utils.models.enums import ModuleType
from datetime import datetime
from enum import Enum
from typing import ClassVar, Literal

class ActivityType(str, Enum):
    """Activity type enumeration."""
    TASK = 'task'
    EVENT = 'event'
    EMAIL = 'email'
    NOTE = 'note'
    CALL = 'call'

class ActivityRelatedTo(str, Enum):
    """What type of record this activity is related to."""
    CONTACT = 'Contact'
    ACCOUNT = 'Account'
    DEAL = 'Deal'

class Activity(TimestampMixin, Model):
    """Base activity model with polymorphic related_to field.

    Activities can be linked to Contacts, Accounts, or Deals using
    a generic foreign key pattern (related_to_type + related_to_id).
    """
    __module_type__: ClassVar[ModuleType] = ...
    __indexes__: ClassVar[list[IndexInfo]] = ...
    activity_type: ActivityType = ...
    subject: str = ...
    description: str | None = ...
    related_to_type: ActivityRelatedTo = ...
    related_to_id: str = ...
    owner_email: str = ...
    due_date: datetime | None = ...
    completed_at: datetime | None = ...
    is_completed: bool = ...
    @property
    def display_name(self) -> str:
        """Return display name for the activity."""
    def has_object_permission(self, user: User, action: str) -> bool:
        """Check if user has permission to perform action on this activity.

        Args:
            user: The user attempting the action
            action: The action being attempted (read, create, update, delete)

        Returns:
            True if user has permission, False otherwise
        """

class Task(Activity):
    """Task activity with priority and status."""
    activity_type: Literal[ActivityType.TASK] = ...
    priority: Literal['low', 'medium', 'high'] = ...
    status: Literal['not_started', 'in_progress', 'waiting', 'completed'] = ...

class Event(Activity):
    """Event/meeting activity with start/end times."""
    activity_type: Literal[ActivityType.EVENT] = ...
    start_time: datetime = ...
    end_time: datetime = ...
    location: str | None = ...

class EmailActivity(Activity):
    """Email activity with sender/recipients."""
    activity_type: Literal[ActivityType.EMAIL] = ...
    from_address: str = ...
    to_addresses: list[str] = ...
    cc_addresses: list[str] | None = ...
    body: str = ...
    is_outbound: bool = ...

class Note(Activity):
    """Simple note activity."""
    activity_type: Literal[ActivityType.NOTE] = ...

class Call(Activity):
    """Phone call activity."""
    activity_type: Literal[ActivityType.CALL] = ...
    phone_number: str = ...
    duration_seconds: int | None = ...
    call_outcome: str | None = ...
