from ..data.EnumDefine import *
from synchronizer_rpc.policy.POLICY import *
from libuseful.lib_usermng import *
from libuseful.lib_logger import *
from _typeshed import Incomplete
from typing import Callable

logging: Incomplete

class SVCProvider:
    SVC_NAME: str
    def stop(self) -> None: ...
    def wait_unsubscribe(self, uid: str): ...
    def get_TimestampMsg(self) -> None: ...
    def make_ErrorDataMsg(self, errno: EErrorDesp = None, msg: str = 'None'): ...
    def is_available_user(self, uid: str): ...
    def is_available_service(self, uid: str): ...
    def __init__(self, user_mng: UserManager, enable_keepalive: bool = False, func_unreg_user: Callable[[str], None] = None) -> None: ...
    def __del__(self) -> None: ...
