"""
    EMIL Tenant Service

    The EMIL TenantService API description  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: kontakt@emil.de
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import eis.tenant
from eis.tenant.model.data_report_filter_dto import DataReportFilterDto
globals()['DataReportFilterDto'] = DataReportFilterDto
from eis.tenant.model.create_data_report_request_dto import CreateDataReportRequestDto


class TestCreateDataReportRequestDto(unittest.TestCase):
    """CreateDataReportRequestDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateDataReportRequestDto(self):
        """Test CreateDataReportRequestDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateDataReportRequestDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
