from pprint import pp

from src.sm_blueprint_lib import *

path = utils.get_paths()[0]
print("Blueprint from direct Class instancing")
bp = Blueprint(bodies=[Body(childs=[BarrierBlock(shapeId='09ca2713-28ee-4119-9622-e85490034758',
                                                 pos=Pos(x=20, y=-5, z=3),
                                                 color='CE9E0C',
                                                 joints=[ID(id=4316)],
                                                 xaxis=1,
                                                 zaxis=3,
                                                 bounds=Bounds(x=1, y=1, z=1))]),
                       Body(childs=[Sensor5(shapeId='20dcd41c-0a11-4668-9b00-97f278ce21af',
                                            pos=Pos(x=14, y=-5, z=3),
                                            color='DF7F01',
                                            joints=None,
                                            xaxis=1,
                                            zaxis=3,
                                            controller=SensorController(controllers=None,
                                                                        id=9301497,
                                                                        joints=None,
                                                                        audioEnabled=False,
                                                                        buttonMode=True,
                                                                        color='EEEEEE',
                                                                        colorMode=False,
                                                                        range=1)),
                                    Sensor1(shapeId='1d4793af-cb66-4628-804a-9d7404712643',
                                            pos=Pos(x=10, y=-5, z=3),
                                            color='DF7F01',
                                            joints=None,
                                            xaxis=1,
                                            zaxis=3,
                                            controller=SensorController(controllers=None,
                                                                        id=9301493,
                                                                        joints=None,
                                                                        audioEnabled=False,
                                                                        buttonMode=True,
                                                                        color='EEEEEE',
                                                                        colorMode=False,
                                                                        range=1)),
                                    Sensor2(shapeId='cf46678b-c947-4267-ba85-f66930f5faa4',
                                            pos=Pos(x=11, y=-5, z=3),
                                            color='DF7F01',
                                            joints=None,
                                            xaxis=1,
                                            zaxis=3,
                                            controller=SensorController(controllers=None,
                                                                        id=9301494,
                                                                        joints=None,
                                                                        audioEnabled=False,
                                                                        buttonMode=True,
                                                                        color='EEEEEE',
                                                                        colorMode=False,
                                                                        range=1)),
                                    Sensor3(shapeId='90fc3603-3544-4254-97ef-ea6723510961',
                                            pos=Pos(x=12, y=-5, z=3),
                                            color='DF7F01',
                                            joints=None,
                                            xaxis=1,
                                            zaxis=3,
                                            controller=SensorController(controllers=None,
                                                                        id=9301495,
                                                                        joints=None,
                                                                        audioEnabled=False,
                                                                        buttonMode=True,
                                                                        color='EEEEEE',
                                                                        colorMode=False,
                                                                        range=1)),
                                    Sensor4(shapeId='de018bc6-1db5-492c-bfec-045e63f9d64b',
                                            pos=Pos(x=13, y=-5, z=3),
                                            color='DF7F01',
                                            joints=None,
                                            xaxis=1,
                                            zaxis=3,
                                            controller=SensorController(controllers=None,
                                                                        id=9301496,
                                                                        joints=None,
                                                                        audioEnabled=False,
                                                                        buttonMode=True,
                                                                        color='EEEEEE',
                                                                        colorMode=False,
                                                                        range=1)),
                                    BarrierBlock(shapeId='09ca2713-28ee-4119-9622-e85490034758',
                                                 pos=Pos(x=0, y=-5, z=2),
                                                 color='CE9E0C',
                                                 joints=[ID(id=4300),
                                                         ID(id=4301),
                                                         ID(id=4303),
                                                         ID(id=4304),
                                                         ID(id=4305),
                                                         ID(id=4306),
                                                         ID(id=4307),
                                                         ID(id=4308),
                                                         ID(id=4309),
                                                         ID(id=4310),
                                                         ID(id=4311),
                                                         ID(id=4312),
                                                         ID(id=4313),
                                                         ID(id=4314),
                                                         ID(id=4315),
                                                         ID(id=4316)],
                                                 xaxis=1,
                                                 zaxis=3,
                                                 bounds=Bounds(x=21, y=1, z=1))]),
                       Body(childs=[BarrierBlock(shapeId='09ca2713-28ee-4119-9622-e85490034758',
                                                 pos=Pos(x=5, y=-5, z=6),
                                                 color='CE9E0C',
                                                 joints=[ID(id=4306),
                                                         ID(id=4307),
                                                         ID(id=4308),
                                                         ID(id=4309),
                                                         ID(id=4310)],
                                                 xaxis=1,
                                                 zaxis=3,
                                                 bounds=Bounds(x=5, y=1, z=1))]),
                       Body(childs=[BarrierBlock(shapeId='09ca2713-28ee-4119-9622-e85490034758',
                                                 pos=Pos(x=15, y=-5, z=4),
                                                 color='CE9E0C',
                                                 joints=[ID(id=4311),
                                                         ID(id=4312),
                                                         ID(id=4313),
                                                         ID(id=4314),
                                                         ID(id=4315)],
                                                 xaxis=1,
                                                 zaxis=3,
                                                 bounds=Bounds(x=5, y=1, z=1))]),
                       Body(childs=[BarrierBlock(shapeId='09ca2713-28ee-4119-9622-e85490034758',
                                                 pos=Pos(x=0, y=-5, z=5),
                                                 color='CE9E0C',
                                                 joints=[ID(id=4300),
                                                         ID(id=4301),
                                                         ID(id=4303),
                                                         ID(id=4304),
                                                         ID(id=4305)],
                                                 xaxis=1,
                                                 zaxis=3,
                                                 bounds=Bounds(x=5, y=1, z=1))])],
               joints=[SportSuspension1(childA=6,
                                        childB=9,
                                        color='DF7F01',
                                        id=4300,
                                        posA=Pos(x=0, y=-5, z=3),
                                        posB=Pos(x=0, y=-5, z=5),
                                        shapeId='67da25c9-3825-41f6-9724-4546a11cb2a5',
                                        xaxisA=1,
                                        xaxisB=1,
                                        zaxisA=3,
                                        zaxisB=3,
                                        controller=SuspensionJointController(controllers=None,
                                                                             id=9301482,
                                                                             joints=None,
                                                                             stiffnessLevel=1)),
                       SportSuspension2(childA=6,
                                        childB=9,
                                        color='DF7F01',
                                        id=4301,
                                        posA=Pos(x=1, y=-5, z=3),
                                        posB=Pos(x=1, y=-5, z=5),
                                        shapeId='aae686a2-0eb3-43b3-b998-def282de79e9',
                                        xaxisA=1,
                                        xaxisB=1,
                                        zaxisA=3,
                                        zaxisB=3,
                                        controller=SuspensionJointController(controllers=None,
                                                                             id=9301483,
                                                                             joints=None,
                                                                             stiffnessLevel=1)),
                       SportSuspension3(childA=6,
                                        childB=9,
                                        color='DF7F01',
                                        id=4303,
                                        posA=Pos(x=2, y=-5, z=3),
                                        posB=Pos(x=2, y=-5, z=5),
                                        shapeId='d0aa2676-5266-432a-bf7e-3887e6ddedd5',
                                        xaxisA=1,
                                        xaxisB=1,
                                        zaxisA=3,
                                        zaxisB=3,
                                        controller=SuspensionJointController(controllers=None,
                                                                             id=9301485,
                                                                             joints=None,
                                                                             stiffnessLevel=1)),
                       SportSuspension4(childA=6,
                                        childB=9,
                                        color='DF7F01',
                                        id=4304,
                                        posA=Pos(x=3, y=-5, z=3),
                                        posB=Pos(x=3, y=-5, z=5),
                                        shapeId='d9adddcc-972d-4726-a376-67f950b99a44',
                                        xaxisA=1,
                                        xaxisB=1,
                                        zaxisA=3,
                                        zaxisB=3,
                                        controller=SuspensionJointController(controllers=None,
                                                                             id=9301486,
                                                                             joints=None,
                                                                             stiffnessLevel=1)),
                       SportSuspension5(childA=6,
                                        childB=9,
                                        color='DF7F01',
                                        id=4305,
                                        posA=Pos(x=4, y=-5, z=3),
                                        posB=Pos(x=4, y=-5, z=5),
                                        shapeId='52855106-a95c-4427-9970-3f227109b66d',
                                        xaxisA=1,
                                        xaxisB=1,
                                        zaxisA=3,
                                        zaxisB=3,
                                        controller=SuspensionJointController(controllers=None,
                                                                             id=9301487,
                                                                             joints=None,
                                                                             stiffnessLevel=1)),
                       OffRoadSuspension1(childA=6,
                                          childB=7,
                                          color='DF7F01',
                                          id=4306,
                                          posA=Pos(x=5, y=-5, z=3),
                                          posB=Pos(x=5, y=-5, z=6),
                                          shapeId='f3cfef9d-faef-4be8-9283-476eb99614d7',
                                          xaxisA=1,
                                          xaxisB=1,
                                          zaxisA=3,
                                          zaxisB=3,
                                          controller=SuspensionJointController(controllers=None,
                                                                               id=9301488,
                                                                               joints=None,
                                                                               stiffnessLevel=1)),
                       OffRoadSuspension2(childA=6,
                                          childB=7,
                                          color='DF7F01',
                                          id=4307,
                                          posA=Pos(x=6, y=-5, z=3),
                                          posB=Pos(x=6, y=-5, z=6),
                                          shapeId='00284190-1484-4286-a198-b2ddef768c2e',
                                          xaxisA=1,
                                          xaxisB=1,
                                          zaxisA=3,
                                          zaxisB=3,
                                          controller=SuspensionJointController(controllers=None,
                                                                               id=9301489,
                                                                               joints=None,
                                                                               stiffnessLevel=1)),
                       OffRoadSuspension3(childA=6,
                                          childB=7,
                                          color='DF7F01',
                                          id=4308,
                                          posA=Pos(x=7, y=-5, z=3),
                                          posB=Pos(x=7, y=-5, z=6),
                                          shapeId='a9658eaf-0dd8-46a6-8cac-be6978f19b79',
                                          xaxisA=1,
                                          xaxisB=1,
                                          zaxisA=3,
                                          zaxisB=3,
                                          controller=SuspensionJointController(controllers=None,
                                                                               id=9301490,
                                                                               joints=None,
                                                                               stiffnessLevel=1)),
                       OffRoadSuspension4(childA=6,
                                          childB=7,
                                          color='DF7F01',
                                          id=4309,
                                          posA=Pos(x=8, y=-5, z=3),
                                          posB=Pos(x=8, y=-5, z=6),
                                          shapeId='4c3f6a7c-45c6-4ed8-bf13-c247c3db6b81',
                                          xaxisA=1,
                                          xaxisB=1,
                                          zaxisA=3,
                                          zaxisB=3,
                                          controller=SuspensionJointController(controllers=None,
                                                                               id=9301491,
                                                                               joints=None,
                                                                               stiffnessLevel=1)),
                       OffRoadSuspension5(childA=6,
                                          childB=7,
                                          color='DF7F01',
                                          id=4310,
                                          posA=Pos(x=9, y=-5, z=3),
                                          posB=Pos(x=9, y=-5, z=6),
                                          shapeId='73f838db-783e-4a41-bc0f-9008967780f3',
                                          xaxisA=1,
                                          xaxisB=1,
                                          zaxisA=3,
                                          zaxisB=3,
                                          controller=SuspensionJointController(controllers=None,
                                                                               id=9301492,
                                                                               joints=None,
                                                                               stiffnessLevel=1)),
                       Piston1(childA=6,
                               childB=8,
                               color='DF7F01',
                               id=4311,
                               posA=Pos(x=15, y=-5, z=3),
                               posB=Pos(x=15, y=-5, z=4),
                               shapeId='8c741785-5eae-4c48-9f99-d62bf522a83f',
                               xaxisA=1,
                               xaxisB=1,
                               zaxisA=3,
                               zaxisB=3,
                               controller=PistonJointController(controllers=None,
                                                                id=9301498,
                                                                joints=None,
                                                                length=0,
                                                                speed=0)),
                       Piston2(childA=6,
                               childB=8,
                               color='DF7F01',
                               id=4312,
                               posA=Pos(x=16, y=-5, z=3),
                               posB=Pos(x=16, y=-5, z=4),
                               shapeId='31f14f52-f4d8-4b9f-9d6e-7412497c9284',
                               xaxisA=1,
                               xaxisB=1,
                               zaxisA=3,
                               zaxisB=3,
                               controller=PistonJointController(controllers=None,
                                                                id=9301499,
                                                                joints=None,
                                                                length=0,
                                                                speed=0)),
                       Piston3(childA=6,
                               childB=8,
                               color='DF7F01',
                               id=4313,
                               posA=Pos(x=17, y=-5, z=3),
                               posB=Pos(x=17, y=-5, z=4),
                               shapeId='46396518-8c29-4da9-81bb-a020f4baf5b2',
                               xaxisA=1,
                               xaxisB=1,
                               zaxisA=3,
                               zaxisB=3,
                               controller=PistonJointController(controllers=None,
                                                                id=9301500,
                                                                joints=None,
                                                                length=0,
                                                                speed=0)),
                       Piston4(childA=6,
                               childB=8,
                               color='DF7F01',
                               id=4314,
                               posA=Pos(x=18, y=-5, z=3),
                               posB=Pos(x=18, y=-5, z=4),
                               shapeId='7324219e-2b19-4098-baa3-9876984ead08',
                               xaxisA=1,
                               xaxisB=1,
                               zaxisA=3,
                               zaxisB=3,
                               controller=PistonJointController(controllers=None,
                                                                id=9301501,
                                                                joints=None,
                                                                length=0,
                                                                speed=0)),
                       Piston5(childA=6,
                               childB=8,
                               color='DF7F01',
                               id=4315,
                               posA=Pos(x=19, y=-5, z=3),
                               posB=Pos(x=19, y=-5, z=4),
                               shapeId='2f004fdf-bfb0-46f3-a7ac-7711100bee0c',
                               xaxisA=1,
                               xaxisB=1,
                               zaxisA=3,
                               zaxisB=3,
                               controller=PistonJointController(controllers=None,
                                                                id=9301502,
                                                                joints=None,
                                                                length=0,
                                                                speed=0)),
                       Bearing(childA=6,
                               childB=0,
                               color='DF7F01',
                               id=4316,
                               posA=Pos(x=20, y=-5, z=3),
                               posB=Pos(x=20, y=-5, z=3),
                               shapeId='4a1b886b-913e-4aad-b5b6-6e41b0db23a6',
                               xaxisA=1,
                               xaxisB=1,
                               zaxisA=3,
                               zaxisB=3)],
               version=4)

pp(bp)

print("Blueprint from json string")
bp1 = load_blueprint_from_string("""
{
    "bodies": [
        {
            "childs": [
                {
                    "bounds": { "x": 1, "y": 1, "z": 1 },
                    "color": "CE9E0C",
                    "joints": [{ "id": 4316 }],
                    "pos": { "x": 20, "y": -5, "z": 3 },
                    "shapeId": "09ca2713-28ee-4119-9622-e85490034758",
                    "xaxis": 1,
                    "zaxis": 3
                }
            ]
        },
        {
            "childs": [
                {
                    "color": "DF7F01",
                    "controller": {
                        "audioEnabled": false,
                        "buttonMode": true,
                        "color": "EEEEEE",
                        "colorMode": false,
                        "controllers": null,
                        "id": 9301497,
                        "joints": null,
                        "range": 1
                    },
                    "pos": { "x": 14, "y": -5, "z": 3 },
                    "shapeId": "20dcd41c-0a11-4668-9b00-97f278ce21af",
                    "xaxis": 1,
                    "zaxis": 3
                },
                {
                    "color": "DF7F01",
                    "controller": {
                        "audioEnabled": false,
                        "buttonMode": true,
                        "color": "EEEEEE",
                        "colorMode": false,
                        "controllers": null,
                        "id": 9301493,
                        "joints": null,
                        "range": 1
                    },
                    "pos": { "x": 10, "y": -5, "z": 3 },
                    "shapeId": "1d4793af-cb66-4628-804a-9d7404712643",
                    "xaxis": 1,
                    "zaxis": 3
                },
                {
                    "color": "DF7F01",
                    "controller": {
                        "audioEnabled": false,
                        "buttonMode": true,
                        "color": "EEEEEE",
                        "colorMode": false,
                        "controllers": null,
                        "id": 9301494,
                        "joints": null,
                        "range": 1
                    },
                    "pos": { "x": 11, "y": -5, "z": 3 },
                    "shapeId": "cf46678b-c947-4267-ba85-f66930f5faa4",
                    "xaxis": 1,
                    "zaxis": 3
                },
                {
                    "color": "DF7F01",
                    "controller": {
                        "audioEnabled": false,
                        "buttonMode": true,
                        "color": "EEEEEE",
                        "colorMode": false,
                        "controllers": null,
                        "id": 9301495,
                        "joints": null,
                        "range": 1
                    },
                    "pos": { "x": 12, "y": -5, "z": 3 },
                    "shapeId": "90fc3603-3544-4254-97ef-ea6723510961",
                    "xaxis": 1,
                    "zaxis": 3
                },
                {
                    "color": "DF7F01",
                    "controller": {
                        "audioEnabled": false,
                        "buttonMode": true,
                        "color": "EEEEEE",
                        "colorMode": false,
                        "controllers": null,
                        "id": 9301496,
                        "joints": null,
                        "range": 1
                    },
                    "pos": { "x": 13, "y": -5, "z": 3 },
                    "shapeId": "de018bc6-1db5-492c-bfec-045e63f9d64b",
                    "xaxis": 1,
                    "zaxis": 3
                },
                {
                    "bounds": { "x": 21, "y": 1, "z": 1 },
                    "color": "CE9E0C",
                    "joints": [
                        { "id": 4300 },
                        { "id": 4301 },
                        { "id": 4303 },
                        { "id": 4304 },
                        { "id": 4305 },
                        { "id": 4306 },
                        { "id": 4307 },
                        { "id": 4308 },
                        { "id": 4309 },
                        { "id": 4310 },
                        { "id": 4311 },
                        { "id": 4312 },
                        { "id": 4313 },
                        { "id": 4314 },
                        { "id": 4315 },
                        { "id": 4316 }
                    ],
                    "pos": { "x": 0, "y": -5, "z": 2 },
                    "shapeId": "09ca2713-28ee-4119-9622-e85490034758",
                    "xaxis": 1,
                    "zaxis": 3
                }
            ]
        },
        {
            "childs": [
                {
                    "bounds": { "x": 5, "y": 1, "z": 1 },
                    "color": "CE9E0C",
                    "joints": [
                        { "id": 4306 },
                        { "id": 4307 },
                        { "id": 4308 },
                        { "id": 4309 },
                        { "id": 4310 }
                    ],
                    "pos": { "x": 5, "y": -5, "z": 6 },
                    "shapeId": "09ca2713-28ee-4119-9622-e85490034758",
                    "xaxis": 1,
                    "zaxis": 3
                }
            ]
        },
        {
            "childs": [
                {
                    "bounds": { "x": 5, "y": 1, "z": 1 },
                    "color": "CE9E0C",
                    "joints": [
                        { "id": 4311 },
                        { "id": 4312 },
                        { "id": 4313 },
                        { "id": 4314 },
                        { "id": 4315 }
                    ],
                    "pos": { "x": 15, "y": -5, "z": 4 },
                    "shapeId": "09ca2713-28ee-4119-9622-e85490034758",
                    "xaxis": 1,
                    "zaxis": 3
                }
            ]
        },
        {
            "childs": [
                {
                    "bounds": { "x": 5, "y": 1, "z": 1 },
                    "color": "CE9E0C",
                    "joints": [
                        { "id": 4300 },
                        { "id": 4301 },
                        { "id": 4303 },
                        { "id": 4304 },
                        { "id": 4305 }
                    ],
                    "pos": { "x": 0, "y": -5, "z": 5 },
                    "shapeId": "09ca2713-28ee-4119-9622-e85490034758",
                    "xaxis": 1,
                    "zaxis": 3
                }
            ]
        }
    ],
    "joints": [
        {
            "childA": 6,
            "childB": 9,
            "color": "DF7F01",
            "controller": {
                "controllers": null,
                "id": 9301482,
                "joints": null,
                "stiffnessLevel": 1
            },
            "id": 4300,
            "posA": { "x": 0, "y": -5, "z": 3 },
            "posB": { "x": 0, "y": -5, "z": 5 },
            "shapeId": "67da25c9-3825-41f6-9724-4546a11cb2a5",
            "xaxisA": 1,
            "xaxisB": 1,
            "zaxisA": 3,
            "zaxisB": 3
        },
        {
            "childA": 6,
            "childB": 9,
            "color": "DF7F01",
            "controller": {
                "controllers": null,
                "id": 9301483,
                "joints": null,
                "stiffnessLevel": 1
            },
            "id": 4301,
            "posA": { "x": 1, "y": -5, "z": 3 },
            "posB": { "x": 1, "y": -5, "z": 5 },
            "shapeId": "aae686a2-0eb3-43b3-b998-def282de79e9",
            "xaxisA": 1,
            "xaxisB": 1,
            "zaxisA": 3,
            "zaxisB": 3
        },
        {
            "childA": 6,
            "childB": 9,
            "color": "DF7F01",
            "controller": {
                "controllers": null,
                "id": 9301485,
                "joints": null,
                "stiffnessLevel": 1
            },
            "id": 4303,
            "posA": { "x": 2, "y": -5, "z": 3 },
            "posB": { "x": 2, "y": -5, "z": 5 },
            "shapeId": "d0aa2676-5266-432a-bf7e-3887e6ddedd5",
            "xaxisA": 1,
            "xaxisB": 1,
            "zaxisA": 3,
            "zaxisB": 3
        },
        {
            "childA": 6,
            "childB": 9,
            "color": "DF7F01",
            "controller": {
                "controllers": null,
                "id": 9301486,
                "joints": null,
                "stiffnessLevel": 1
            },
            "id": 4304,
            "posA": { "x": 3, "y": -5, "z": 3 },
            "posB": { "x": 3, "y": -5, "z": 5 },
            "shapeId": "d9adddcc-972d-4726-a376-67f950b99a44",
            "xaxisA": 1,
            "xaxisB": 1,
            "zaxisA": 3,
            "zaxisB": 3
        },
        {
            "childA": 6,
            "childB": 9,
            "color": "DF7F01",
            "controller": {
                "controllers": null,
                "id": 9301487,
                "joints": null,
                "stiffnessLevel": 1
            },
            "id": 4305,
            "posA": { "x": 4, "y": -5, "z": 3 },
            "posB": { "x": 4, "y": -5, "z": 5 },
            "shapeId": "52855106-a95c-4427-9970-3f227109b66d",
            "xaxisA": 1,
            "xaxisB": 1,
            "zaxisA": 3,
            "zaxisB": 3
        },
        {
            "childA": 6,
            "childB": 7,
            "color": "DF7F01",
            "controller": {
                "controllers": null,
                "id": 9301488,
                "joints": null,
                "stiffnessLevel": 1
            },
            "id": 4306,
            "posA": { "x": 5, "y": -5, "z": 3 },
            "posB": { "x": 5, "y": -5, "z": 6 },
            "shapeId": "f3cfef9d-faef-4be8-9283-476eb99614d7",
            "xaxisA": 1,
            "xaxisB": 1,
            "zaxisA": 3,
            "zaxisB": 3
        },
        {
            "childA": 6,
            "childB": 7,
            "color": "DF7F01",
            "controller": {
                "controllers": null,
                "id": 9301489,
                "joints": null,
                "stiffnessLevel": 1
            },
            "id": 4307,
            "posA": { "x": 6, "y": -5, "z": 3 },
            "posB": { "x": 6, "y": -5, "z": 6 },
            "shapeId": "00284190-1484-4286-a198-b2ddef768c2e",
            "xaxisA": 1,
            "xaxisB": 1,
            "zaxisA": 3,
            "zaxisB": 3
        },
        {
            "childA": 6,
            "childB": 7,
            "color": "DF7F01",
            "controller": {
                "controllers": null,
                "id": 9301490,
                "joints": null,
                "stiffnessLevel": 1
            },
            "id": 4308,
            "posA": { "x": 7, "y": -5, "z": 3 },
            "posB": { "x": 7, "y": -5, "z": 6 },
            "shapeId": "a9658eaf-0dd8-46a6-8cac-be6978f19b79",
            "xaxisA": 1,
            "xaxisB": 1,
            "zaxisA": 3,
            "zaxisB": 3
        },
        {
            "childA": 6,
            "childB": 7,
            "color": "DF7F01",
            "controller": {
                "controllers": null,
                "id": 9301491,
                "joints": null,
                "stiffnessLevel": 1
            },
            "id": 4309,
            "posA": { "x": 8, "y": -5, "z": 3 },
            "posB": { "x": 8, "y": -5, "z": 6 },
            "shapeId": "4c3f6a7c-45c6-4ed8-bf13-c247c3db6b81",
            "xaxisA": 1,
            "xaxisB": 1,
            "zaxisA": 3,
            "zaxisB": 3
        },
        {
            "childA": 6,
            "childB": 7,
            "color": "DF7F01",
            "controller": {
                "controllers": null,
                "id": 9301492,
                "joints": null,
                "stiffnessLevel": 1
            },
            "id": 4310,
            "posA": { "x": 9, "y": -5, "z": 3 },
            "posB": { "x": 9, "y": -5, "z": 6 },
            "shapeId": "73f838db-783e-4a41-bc0f-9008967780f3",
            "xaxisA": 1,
            "xaxisB": 1,
            "zaxisA": 3,
            "zaxisB": 3
        },
        {
            "childA": 6,
            "childB": 8,
            "color": "DF7F01",
            "controller": {
                "controllers": null,
                "id": 9301498,
                "joints": null,
                "length": 0,
                "speed": 0
            },
            "id": 4311,
            "posA": { "x": 15, "y": -5, "z": 3 },
            "posB": { "x": 15, "y": -5, "z": 4 },
            "shapeId": "8c741785-5eae-4c48-9f99-d62bf522a83f",
            "xaxisA": 1,
            "xaxisB": 1,
            "zaxisA": 3,
            "zaxisB": 3
        },
        {
            "childA": 6,
            "childB": 8,
            "color": "DF7F01",
            "controller": {
                "controllers": null,
                "id": 9301499,
                "joints": null,
                "length": 0,
                "speed": 0
            },
            "id": 4312,
            "posA": { "x": 16, "y": -5, "z": 3 },
            "posB": { "x": 16, "y": -5, "z": 4 },
            "shapeId": "31f14f52-f4d8-4b9f-9d6e-7412497c9284",
            "xaxisA": 1,
            "xaxisB": 1,
            "zaxisA": 3,
            "zaxisB": 3
        },
        {
            "childA": 6,
            "childB": 8,
            "color": "DF7F01",
            "controller": {
                "controllers": null,
                "id": 9301500,
                "joints": null,
                "length": 0,
                "speed": 0
            },
            "id": 4313,
            "posA": { "x": 17, "y": -5, "z": 3 },
            "posB": { "x": 17, "y": -5, "z": 4 },
            "shapeId": "46396518-8c29-4da9-81bb-a020f4baf5b2",
            "xaxisA": 1,
            "xaxisB": 1,
            "zaxisA": 3,
            "zaxisB": 3
        },
        {
            "childA": 6,
            "childB": 8,
            "color": "DF7F01",
            "controller": {
                "controllers": null,
                "id": 9301501,
                "joints": null,
                "length": 0,
                "speed": 0
            },
            "id": 4314,
            "posA": { "x": 18, "y": -5, "z": 3 },
            "posB": { "x": 18, "y": -5, "z": 4 },
            "shapeId": "7324219e-2b19-4098-baa3-9876984ead08",
            "xaxisA": 1,
            "xaxisB": 1,
            "zaxisA": 3,
            "zaxisB": 3
        },
        {
            "childA": 6,
            "childB": 8,
            "color": "DF7F01",
            "controller": {
                "controllers": null,
                "id": 9301502,
                "joints": null,
                "length": 0,
                "speed": 0
            },
            "id": 4315,
            "posA": { "x": 19, "y": -5, "z": 3 },
            "posB": { "x": 19, "y": -5, "z": 4 },
            "shapeId": "2f004fdf-bfb0-46f3-a7ac-7711100bee0c",
            "xaxisA": 1,
            "xaxisB": 1,
            "zaxisA": 3,
            "zaxisB": 3
        },
        {
            "childA": 6,
            "childB": 0,
            "color": "DF7F01",
            "id": 4316,
            "posA": { "x": 20, "y": -5, "z": 3 },
            "posB": { "x": 20, "y": -5, "z": 3 },
            "shapeId": "4a1b886b-913e-4aad-b5b6-6e41b0db23a6",
            "xaxisA": 1,
            "xaxisB": 1,
            "zaxisA": 3,
            "zaxisB": 3
        }
    ],
    "version": 4
}
""")
pp(bp1)


