# coding: utf-8

"""
    OurSky

    Fully merged Converged Node Platform API documentation

    The version of the OpenAPI document: 1.3.9356
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictBool, StrictInt
from ourskyai_node_platform_api.models.roof_state import RoofState

class V1RoofStatus(BaseModel):
    """
    Roof Status  # noqa: E501
    """
    connected: StrictBool = Field(...)
    state: RoofState = Field(...)
    front_position: StrictInt = Field(..., alias="frontPosition")
    rear_position: StrictInt = Field(..., alias="rearPosition")
    __properties = ["connected", "state", "frontPosition", "rearPosition"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> V1RoofStatus:
        """Create an instance of V1RoofStatus from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> V1RoofStatus:
        """Create an instance of V1RoofStatus from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return V1RoofStatus.parse_obj(obj)

        _obj = V1RoofStatus.parse_obj({
            "connected": obj.get("connected"),
            "state": obj.get("state"),
            "front_position": obj.get("frontPosition"),
            "rear_position": obj.get("rearPosition")
        })
        return _obj


