from ..Company import Division as Division
from ..DataModel import ChangeAgentEnum as ChangeAgentEnum, DataModel as DataModel
from ..Document import Document as Document
from ..Helpers import MakeIsodateOptionalField as MakeIsodateOptionalField
from ..PrimaryDataObject import DataObjectTypeEnum as DataObjectTypeEnum, PrimaryDataObject as PrimaryDataObject
from ..geomodels.DataGrid import DataGrid as DataGrid
from ..geomodels.Structure import Structure as Structure
from ..strat.StratColumn import StratColumnEntry as StratColumnEntry
from dataclasses import dataclass, field
from datetime import datetime
from typing import ClassVar

@dataclass
class Geomodel(PrimaryDataObject):
    external_id: str | None = ...
    external_source: str | None = ...
    creator: str | None = ...
    change_agent: ChangeAgentEnum = ...
    creation_date: datetime | None = ...
    last_modified_date: datetime | None = ...
    division: Division | None = ...
    strat_column: StratColumnEntry | None = ...
    description: str | None = ...
    data_grids: list[DataGrid] = field(default_factory=list[DataGrid])
    structures: list[Structure] = field(default_factory=list[Structure])
    documents: list[Document] = field(default_factory=list[Document])
    archive_dir_name: ClassVar[str] = ...
    archive_json_filename: ClassVar[str] = ...
    @property
    def full_name(self) -> str: ...
    @property
    def data_object_type(self) -> DataObjectTypeEnum: ...

@dataclass
class GeomodelEntry(DataModel):
    division: Division | None = ...
    company_name: str | None = ...
    number: str | None = ...
    type: str = ...
    description: str | None = ...
    row_version: str | None = ...
    num_datasets: int = ...
    @property
    def geomodel(self) -> Geomodel: ...
