from typing import List


class __Trigger:
    def getModeIds(self) -> List[str]: ...
    def selectMode(self, modeId: str) -> None: ...
    def setShutterDuration(self, duration: float) -> None: ...
    def trigger(self) -> None: ...
