"""
    Delphix DCT API

    Delphix DCT API  # noqa: E501

    The version of the OpenAPI document: 3.26.0
    Contact: support@delphix.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import delphix.api.gateway
from delphix.api.gateway.model.masking_execution_metrics import MaskingExecutionMetrics
from delphix.api.gateway.model.paginated_response_metadata import PaginatedResponseMetadata
globals()['MaskingExecutionMetrics'] = MaskingExecutionMetrics
globals()['PaginatedResponseMetadata'] = PaginatedResponseMetadata
from delphix.api.gateway.model.masking_execution_metrics_report_response import MaskingExecutionMetricsReportResponse


class TestMaskingExecutionMetricsReportResponse(unittest.TestCase):
    """MaskingExecutionMetricsReportResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMaskingExecutionMetricsReportResponse(self):
        """Test MaskingExecutionMetricsReportResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MaskingExecutionMetricsReportResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
