"""
    Delphix DCT API

    Delphix DCT API  # noqa: E501

    The version of the OpenAPI document: 3.26.0
    Contact: support@delphix.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import delphix.api.gateway
from delphix.api.gateway.model.filesystem_layout_parameters import FilesystemLayoutParameters


class TestFilesystemLayoutParameters(unittest.TestCase):
    """FilesystemLayoutParameters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFilesystemLayoutParameters(self):
        """Test FilesystemLayoutParameters"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FilesystemLayoutParameters()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
