"""
    Delphix DCT API

    Delphix DCT API  # noqa: E501

    The version of the OpenAPI document: 3.26.0
    Contact: support@delphix.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import delphix.api.gateway
from delphix.api.gateway.model.license_usage_type_record import LicenseUsageTypeRecord
globals()['LicenseUsageTypeRecord'] = LicenseUsageTypeRecord
from delphix.api.gateway.model.license_usage_time_series_response import LicenseUsageTimeSeriesResponse


class TestLicenseUsageTimeSeriesResponse(unittest.TestCase):
    """LicenseUsageTimeSeriesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLicenseUsageTimeSeriesResponse(self):
        """Test LicenseUsageTimeSeriesResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LicenseUsageTimeSeriesResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
