"""
    Delphix DCT API

    Delphix DCT API  # noqa: E501

    The version of the OpenAPI document: 3.26.0
    Contact: support@delphix.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import delphix.api.gateway
from delphix.api.gateway.model.execution_component import ExecutionComponent
from delphix.api.gateway.model.paginated_response_metadata import PaginatedResponseMetadata
globals()['ExecutionComponent'] = ExecutionComponent
globals()['PaginatedResponseMetadata'] = PaginatedResponseMetadata
from delphix.api.gateway.model.execution_components_search_response import ExecutionComponentsSearchResponse


class TestExecutionComponentsSearchResponse(unittest.TestCase):
    """ExecutionComponentsSearchResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExecutionComponentsSearchResponse(self):
        """Test ExecutionComponentsSearchResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ExecutionComponentsSearchResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
