import numpy as np
from dvsense_driver.hal.camera_tool import ToolType, CameraTool
from dvsense_driver.hal.camera_tool import BasicParameterInfo, ToolInfo
from dvsense_driver.hal.dvs_camera_utils import CameraDescription

class FusionCamera:
    def __init__(self): ...
    def is_connected(self) -> bool: ...
    def get_description(self) -> CameraDescription: ...
    def start(self, stream_type): ...
    def stop(self, stream_type): ...
    def start_recording(self, file_path: str, file_name: str, stream_type) -> int: ...
    def stop_recording(self, stream_type) -> int: ...
    def get_width(self, stream_type) -> int: ...
    def get_height(self, stream_type) -> int: ...
    def get_all_tools_info(self) -> list[BasicParameterInfo]: ...
    def get_tool_info(self, tool_type: ToolType) -> ToolInfo: ...
    def get_tool(self, tool_type: ToolType) -> CameraTool: ...
    def add_event_stream_nocopy_callback(self, callback) -> int: ...
    def add_aps_frame_nocopy_callback(self, callback) -> int: ...
    def write_calibration_file(self, file_path: str) -> bool: ...
    def read_calibration_parameter(self, param) -> bool: ...