from amsdal_models.classes.data_models.constraints import UniqueConstraint
from amsdal_models.classes.model import Model
from amsdal_utils.models.enums import ModuleType
from typing import Any, ClassVar, Literal

class CustomFieldDefinition(Model):
    """Metadata about custom fields available for CRM entities.

    Defines custom fields that users can add to Contacts, Accounts, or Deals.
    Field values are stored in the entity's custom_fields JSON dict.
    """
    __module_type__: ClassVar[ModuleType] = ...
    __constraints__: ClassVar[list[UniqueConstraint]] = ...
    entity_type: Literal['Contact', 'Account', 'Deal'] = ...
    field_name: str = ...
    field_label: str = ...
    field_type: Literal['text', 'number', 'date', 'choice'] = ...
    choices: list[str] | None = ...
    is_required: bool = ...
    default_value: Any | None = ...
    help_text: str | None = ...
    display_order: int = ...
    @property
    def display_name(self) -> str:
        """Return display name for the custom field definition."""
