"""
Blessed Salesforce connector for Airbyte SDK.

Auto-generated from OpenAPI specification.
"""

from .connector import SalesforceConnector
from .models import (
    SalesforceAuthConfig,
    AccountAttributes,
    Account,
    AccountQueryResult,
    ContactAttributes,
    Contact,
    ContactQueryResult,
    LeadAttributes,
    Lead,
    LeadQueryResult,
    OpportunityAttributes,
    Opportunity,
    OpportunityQueryResult,
    TaskAttributes,
    Task,
    TaskQueryResult,
    EventAttributes,
    Event,
    EventQueryResult,
    CampaignAttributes,
    Campaign,
    CampaignQueryResult,
    CaseAttributes,
    Case,
    CaseQueryResult,
    NoteAttributes,
    Note,
    NoteQueryResult,
    ContentVersionAttributes,
    ContentVersion,
    ContentVersionQueryResult,
    AttachmentAttributes,
    Attachment,
    AttachmentQueryResult,
    QueryResult,
    SearchResultSearchrecordsItemAttributes,
    SearchResultSearchrecordsItem,
    SearchResult,
    SalesforceExecuteResult,
    SalesforceExecuteResultWithMeta
)
from .types import (
    AccountsListParams,
    AccountsGetParams,
    AccountsApiSearchParams,
    ContactsListParams,
    ContactsGetParams,
    ContactsApiSearchParams,
    LeadsListParams,
    LeadsGetParams,
    LeadsApiSearchParams,
    OpportunitiesListParams,
    OpportunitiesGetParams,
    OpportunitiesApiSearchParams,
    TasksListParams,
    TasksGetParams,
    TasksApiSearchParams,
    EventsListParams,
    EventsGetParams,
    EventsApiSearchParams,
    CampaignsListParams,
    CampaignsGetParams,
    CampaignsApiSearchParams,
    CasesListParams,
    CasesGetParams,
    CasesApiSearchParams,
    NotesListParams,
    NotesGetParams,
    NotesApiSearchParams,
    ContentVersionsListParams,
    ContentVersionsGetParams,
    ContentVersionsDownloadParams,
    AttachmentsListParams,
    AttachmentsGetParams,
    AttachmentsDownloadParams,
    QueryListParams
)

__all__ = ["SalesforceConnector", "SalesforceAuthConfig", "AccountAttributes", "Account", "AccountQueryResult", "ContactAttributes", "Contact", "ContactQueryResult", "LeadAttributes", "Lead", "LeadQueryResult", "OpportunityAttributes", "Opportunity", "OpportunityQueryResult", "TaskAttributes", "Task", "TaskQueryResult", "EventAttributes", "Event", "EventQueryResult", "CampaignAttributes", "Campaign", "CampaignQueryResult", "CaseAttributes", "Case", "CaseQueryResult", "NoteAttributes", "Note", "NoteQueryResult", "ContentVersionAttributes", "ContentVersion", "ContentVersionQueryResult", "AttachmentAttributes", "Attachment", "AttachmentQueryResult", "QueryResult", "SearchResultSearchrecordsItemAttributes", "SearchResultSearchrecordsItem", "SearchResult", "SalesforceExecuteResult", "SalesforceExecuteResultWithMeta", "AccountsListParams", "AccountsGetParams", "AccountsApiSearchParams", "ContactsListParams", "ContactsGetParams", "ContactsApiSearchParams", "LeadsListParams", "LeadsGetParams", "LeadsApiSearchParams", "OpportunitiesListParams", "OpportunitiesGetParams", "OpportunitiesApiSearchParams", "TasksListParams", "TasksGetParams", "TasksApiSearchParams", "EventsListParams", "EventsGetParams", "EventsApiSearchParams", "CampaignsListParams", "CampaignsGetParams", "CampaignsApiSearchParams", "CasesListParams", "CasesGetParams", "CasesApiSearchParams", "NotesListParams", "NotesGetParams", "NotesApiSearchParams", "ContentVersionsListParams", "ContentVersionsGetParams", "ContentVersionsDownloadParams", "AttachmentsListParams", "AttachmentsGetParams", "AttachmentsDownloadParams", "QueryListParams"]
