# coding: utf-8

"""
    OurSky

    Fully merged Converged Node Platform API documentation

    The version of the OpenAPI document: 1.3.9356
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from ourskyai_node_platform_api.models.v1_connected_camera import V1ConnectedCamera  # noqa: E501

class TestV1ConnectedCamera(unittest.TestCase):
    """V1ConnectedCamera unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1ConnectedCamera:
        """Test V1ConnectedCamera
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1ConnectedCamera`
        """
        model = V1ConnectedCamera()  # noqa: E501
        if include_optional:
            return V1ConnectedCamera(
                id = '',
                name = ''
            )
        else:
            return V1ConnectedCamera(
                id = '',
                name = '',
        )
        """

    def testV1ConnectedCamera(self):
        """Test V1ConnectedCamera"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
