# coding: utf-8

"""
    OurSky

    Fully merged Converged Node Platform API documentation

    The version of the OpenAPI document: 1.3.9356
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from ourskyai_node_platform_api.models.v1_mount_model import V1MountModel  # noqa: E501

class TestV1MountModel(unittest.TestCase):
    """V1MountModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1MountModel:
        """Test V1MountModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1MountModel`
        """
        model = V1MountModel()  # noqa: E501
        if include_optional:
            return V1MountModel(
                points = [
                    ourskyai_node_platform_api.models.v1_mount_model_point.V1MountModelPoint(
                        altitude_degrees = 1.337, 
                        azimuth_degrees = 1.337, 
                        ra_degrees = 1.337, 
                        dec_degrees = 1.337, )
                    ],
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return V1MountModel(
                points = [
                    ourskyai_node_platform_api.models.v1_mount_model_point.V1MountModelPoint(
                        altitude_degrees = 1.337, 
                        azimuth_degrees = 1.337, 
                        ra_degrees = 1.337, 
                        dec_degrees = 1.337, )
                    ],
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testV1MountModel(self):
        """Test V1MountModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
