from ...datamodels.Helpers import MakeIsodateOptionalField as MakeIsodateOptionalField
from ..Company import Division as Division
from ..DataModel import DataModel as DataModel
from ..Document import Document as Document
from ..PrimaryDataObject import DataObjectTypeEnum as DataObjectTypeEnum, PrimaryDataObject as PrimaryDataObject
from .Fault import FaultEntry as FaultEntry
from .SeisHorizon import SeisHorizon as SeisHorizon
from .SeismicDataset import SeismicDataset as SeismicDataset
from dataclasses import dataclass, field
from datetime import datetime
from strenum import StrEnum
from typing import ClassVar

class SurveyTypeEnum(StrEnum):
    Unknown = 'Unknown'
    Type_2D = 'Type_2D'
    Type_3D = 'Type_3D'

@dataclass
class SeismicSurvey(PrimaryDataObject):
    division: Division | None = ...
    number: str | None = ...
    type: SurveyTypeEnum = ...
    description: str | None = ...
    num_datasets: int = ...
    documents: list[Document] = field(default_factory=list[Document])
    seismic_datasets: list[SeismicDataset] = field(default_factory=list[SeismicDataset])
    faults: list[FaultEntry] = field(default_factory=list[FaultEntry])
    horizons: list[SeisHorizon] = field(default_factory=list[SeisHorizon])
    fold: int | None = ...
    county: str | None = ...
    state: str | None = ...
    country: str | None = ...
    year_recorded: int | None = ...
    day_recorded: int | None = ...
    contractor: int | None = ...
    contractee: int | None = ...
    environment: str | None = ...
    basin: str | None = ...
    play: str | None = ...
    geologic_region: str | None = ...
    date_acquired: datetime | None = ...
    contractor_name: str | None = ...
    energy_source: str | None = ...
    dynamite_charge_size: str | None = ...
    dynamite_depth: str | None = ...
    vibroseis_num_vibrators: int | None = ...
    vibroseis_sweep: str | None = ...
    vibroseis_sweep_length: str | None = ...
    airgun_num_airguns: int | None = ...
    airgun_pressure: str | None = ...
    recording_equipment: str | None = ...
    num_channels: int | None = ...
    surveyed_by: str | None = ...
    processed_by: str | None = ...
    date_processed: datetime | None = ...
    processing_remarks: str | None = ...
    original_owner: str | None = ...
    purchase_afe: str | None = ...
    purchase_date: datetime | None = ...
    purchased_from: str | None = ...
    price: float | None = ...
    total_cost: float | None = ...
    purchase_reference: str | None = ...
    original_media: str | None = ...
    date_copied: datetime | None = ...
    date_sent: datetime | None = ...
    media_remarks: str | None = ...
    archive_dir_name: ClassVar[str] = ...
    archive_json_filename: ClassVar[str] = ...
    @property
    def full_name(self) -> str: ...
    @property
    def data_object_type(self) -> DataObjectTypeEnum: ...

@dataclass
class SeismicSurveyEntry(DataModel):
    division: Division | None = ...
    company_name: str | None = ...
    number: str | None = ...
    type: SurveyTypeEnum = ...
    description: str | None = ...
    num_datasets: int = ...
    @property
    def seismic_survey(self) -> SeismicSurvey: ...
