from .demand import DEMAND_CONFIG_SCHEMA, DEMAND_STEPS
from .parameters import PARAMETERS_CONFIG_SCHEMA, PARAMETERS_STEPS
from .run import RUN_CONFIG_SCHEMA, RUN_STEPS
from .supply import SUPPLY_CONFIG_SCHEMA, SUPPLY_STEPS
from .results import RESULTS_STEPS

CONFIG_SCHEMA = DEMAND_CONFIG_SCHEMA + PARAMETERS_CONFIG_SCHEMA + SUPPLY_CONFIG_SCHEMA + RUN_CONFIG_SCHEMA

STEPS = DEMAND_STEPS + PARAMETERS_STEPS + SUPPLY_STEPS + RUN_STEPS + RESULTS_STEPS
