"""
    EMIL DocumentService

    The EMIL DocumentService API description  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: kontakt@emil.de
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import eis.document
from eis.document.model.create_html_template_dto import CreateHtmlTemplateDto


class TestCreateHtmlTemplateDto(unittest.TestCase):
    """CreateHtmlTemplateDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateHtmlTemplateDto(self):
        """Test CreateHtmlTemplateDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateHtmlTemplateDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
