"""
    EMIL DocumentService

    The EMIL DocumentService API description  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: kontakt@emil.de
    Generated by: https://openapi-generator.tech
"""


import unittest

import eis.document
from eis.document.api.documents_api import DocumentsApi  # noqa: E501


class TestDocumentsApi(unittest.TestCase):
    """DocumentsApi unit test stubs"""

    def setUp(self):
        self.api = DocumentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_document(self):
        """Test case for create_document

        Create the document  # noqa: E501
        """
        pass

    def test_create_presigned_post(self):
        """Test case for create_presigned_post

        Upload documents using pre-signed URL  # noqa: E501
        """
        pass

    def test_create_qr_bill_document(self):
        """Test case for create_qr_bill_document

        Create the QR bill document  # noqa: E501
        """
        pass

    def test_delete_document(self):
        """Test case for delete_document

        Delete the document  # noqa: E501
        """
        pass

    def test_export_document(self):
        """Test case for export_document

        Export internal document  # noqa: E501
        """
        pass

    def test_get_document_download_url(self):
        """Test case for get_document_download_url

        Fetches a document download URL  # noqa: E501
        """
        pass

    def test_get_signed_s3key_url(self):
        """Test case for get_signed_s3key_url

        Fetches a presigned URL for a S3 key  # noqa: E501
        """
        pass

    def test_list_documents(self):
        """Test case for list_documents

        List documents  # noqa: E501
        """
        pass

    def test_merge_documents(self):
        """Test case for merge_documents

        Create the merged document  # noqa: E501
        """
        pass

    def test_save_external_document(self):
        """Test case for save_external_document

        Save external document  # noqa: E501
        """
        pass

    def test_update_document(self):
        """Test case for update_document

        Update the document  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
