stn_dict = {
    '속초': {'id': 90, 'name_en': 'Sokcho'},
    '북춘천': {'id': 93, 'name_en': 'Bukchuncheon'},
    '철원': {'id': 95, 'name_en': 'Cheorwon'},
    '동두천': {'id': 98, 'name_en': 'Dongducheon'},
    '파주': {'id': 99, 'name_en': 'Paju'},
    '대관령': {'id': 100, 'name_en': 'Daegwallyeong'},
    '춘천': {'id': 101, 'name_en': 'Chuncheon'},
    '백령도': {'id': 102, 'name_en': 'Baengnyeongdo'},
    '북강릉': {'id': 104, 'name_en': 'Bukgangneung'},
    '강릉': {'id': 105, 'name_en': 'Gangneung'},
    '동해': {'id': 106, 'name_en': 'Donghae'},
    '서울': {'id': 108, 'name_en': 'Seoul'},
    '인천': {'id': 112, 'name_en': 'Incheon'},
    '원주': {'id': 114, 'name_en': 'Wonju'},
    '울릉도': {'id': 115, 'name_en': 'Ulleungdo'},
    '수원': {'id': 119, 'name_en': 'Suwon'},
    '영월': {'id': 121, 'name_en': 'Yeongwol'},
    '충주': {'id': 127, 'name_en': 'Chungju'},
    '서산': {'id': 129, 'name_en': 'Seosan'},
    '울진': {'id': 130, 'name_en': 'Uljin'},
    '청주': {'id': 131, 'name_en': 'Cheongju'},
    '대전': {'id': 133, 'name_en': 'Daejeon'},
    '추풍령': {'id': 135, 'name_en': 'Chupungnyeong'},
    '안동': {'id': 136, 'name_en': 'Andong'},
    '상주': {'id': 137, 'name_en': 'Sangju'},
    '포항': {'id': 138, 'name_en': 'Pohang'},
    '군산': {'id': 140, 'name_en': 'Gunsan'},
    '대구': {'id': 143, 'name_en': 'Daegu'},
    '전주': {'id': 146, 'name_en': 'Jeonju'},
    '울산': {'id': 152, 'name_en': 'Ulsan'},
    '창원': {'id': 155, 'name_en': 'Changwon'},
    '광주': {'id': 156, 'name_en': 'Gwangju'},
    '부산': {'id': 159, 'name_en': 'Busan'},
    '통영': {'id': 162, 'name_en': 'Tongyeong'},
    '목포': {'id': 165, 'name_en': 'Mokpo'},
    '여수': {'id': 168, 'name_en': 'Yeosu'},
    '흑산도': {'id': 169, 'name_en': 'Heuksando'},
    '완도': {'id': 170, 'name_en': 'Wando'},
    '고창': {'id': 172, 'name_en': 'Gochang'},
    '순천': {'id': 174, 'name_en': 'Suncheon'},
    '홍성': {'id': 177, 'name_en': 'Hongseong'},
    '제주': {'id': 184, 'name_en': 'Jeju'},
    '고산': {'id': 185, 'name_en': 'Gosan'},
    '성산': {'id': 188, 'name_en': 'Seongsan'},
    '서귀포': {'id': 189, 'name_en': 'Seogwipo'},
    '진주': {'id': 192, 'name_en': 'Jinju'},
    '강화': {'id': 201, 'name_en': 'Ganghwa'},
    '양평': {'id': 202, 'name_en': 'Yangpyeong'},
    '이천': {'id': 203, 'name_en': 'Icheon'},
    '홍천': {'id': 212, 'name_en': 'Hongcheon'},
    '인제': {'id': 211, 'name_en': 'Inje'},
    '태백': {'id': 216, 'name_en': 'Taebaek'},
    '정선군': {'id': 217, 'name_en': 'Jeongseon'},
    '제천': {'id': 221, 'name_en': 'Jecheon'},
    '보은': {'id': 226, 'name_en': 'Boeun'},
    '천안': {'id': 232, 'name_en': 'Cheonan'},
    '보령': {'id': 235, 'name_en': 'Boryeong'},
    '부여': {'id': 236, 'name_en': 'Buyeo'},
    '금산': {'id': 238, 'name_en': 'Geumsan'},
    '세종': {'id': 239, 'name_en': 'Sejong'},
    '부안': {'id': 243, 'name_en': 'Buan'},
    '임실': {'id': 244, 'name_en': 'Imsil'},
    '정읍': {'id': 245, 'name_en': 'Jeongeup'},
    '남원': {'id': 247, 'name_en': 'Namwon'},
    '장수': {'id': 248, 'name_en': 'Jangsu'},
    '고창군': {'id': 251, 'name_en': 'Gochang-gun'},
    '영광군': {'id': 252, 'name_en': 'Yeonggwang-gun'},
    '김해시': {'id': 253, 'name_en': 'Gimhae'},
    '순창군': {'id': 254, 'name_en': 'Sunchang-gun'},
    '북창원': {'id': 255, 'name_en': 'Bukchangwon'},
    '양산시': {'id': 257, 'name_en': 'Yangsan'},
    '보성군': {'id': 258, 'name_en': 'Boseong'},
    '강진군': {'id': 259, 'name_en': 'Gangjin'},
    '장흥': {'id': 260, 'name_en': 'Jangheung'},
    '해남': {'id': 261, 'name_en': 'Haenam'},
    '고흥': {'id': 262, 'name_en': 'Goheung'},
    '의령군': {'id': 263, 'name_en': 'Uiryeong'},
    '함양군': {'id': 264, 'name_en': 'Hamyang'},
    '광양시': {'id': 266, 'name_en': 'Gwangyang'},
    '진도군': {'id': 268, 'name_en': 'Jindo'},
    '봉화': {'id': 271, 'name_en': 'Bonghwa'},
    '영주': {'id': 272, 'name_en': 'Yeongju'},
    '문경': {'id': 273, 'name_en': 'Mungyeong'},
    '청송군': {'id': 276, 'name_en': 'Cheongsong'},
    '영덕': {'id': 277, 'name_en': 'Yeongdeok'},
    '의성': {'id': 278, 'name_en': 'Uiseong'},
    '구미': {'id': 279, 'name_en': 'Gumi'},
    '영천': {'id': 281, 'name_en': 'Yeongcheon'},
    '경주시': {'id': 283, 'name_en': 'Gyeongju'},
    '거창': {'id': 284, 'name_en': 'Geochang'},
    '합천': {'id': 285, 'name_en': 'Hapcheon'},
    '밀양': {'id': 288, 'name_en': 'Miryang'},
    '산청': {'id': 289, 'name_en': 'Sancheong'},
    '거제': {'id': 294, 'name_en': 'Geoje'},
    '남해': {'id': 295, 'name_en': 'Namhae'}
}


elemId = [
    'tm', 'avgta', 'minta', 'maxta', 'sumrndur', 'mi10maxrn', 'mi10maxrnhrmt', 
    'hr1maxrn', 'hr1maxrnhrmt', 'sumrn', 'avgws', 'avgtd', 'minrhm', 'avgrhm', 
    'avgpv', 'avgpa', 'ssdur', 'sumsshr', 'hr1maxicsr', 'sumgsr', 'ddmefs', 
    'ddmes', 'avgtca', 'avglmac', 'avgts', 'mintg', 'avgcm5te', 'avgcm10te', 
    'avgcm20te', 'avgcm30te', 'avgm05te', 'avgm10te', 'avgm15te', 'avgm30te', 
    'avgm50te', 'sumlrgev', 'sumsmev', 'n99rn', 'iscs', 'sumfogdur'
]

elemId_u = [
    'tm', 'avgTa', 'minTa', 'maxTa', 'sumRnDur', 'mi10MaxRn', 'mi10MaxRnHrmt',
    'hr1MaxRn', 'hr1MaxRnHrmt', 'sumRn', 'avgWs', 'avgTd', 'minRhm', 'avgRhm',
    'avgPv', 'avgPa', 'ssDur', 'sumSsHr', 'hr1MaxIcsr', 'sumGsr', 'ddMefs',
    'ddMes', 'avgTca', 'avgLmac', 'avgTs', 'minTg', 'avgCm5Te', 'avgCm10Te',
    'avgCm20Te', 'avgCm30Te', 'avgM05Te', 'avgM10Te', 'avgM15Te', 'avgM30Te',
    'avgM50Te', 'sumLrgEv', 'sumSmlEv', 'n99Rn', 'iscs', 'sumFogDur'
]

el_nino_years = [1973, 1977, 1978, 1980, 1982, 1983, 1987, 1988, 1991, 1992, 1993, 
                 1994, 1995, 1998, 2003, 2005, 2007, 2010, 2015, 2016, 2019, 2020, 2024]
la_nina_years = [1974, 1975, 1976, 1985, 1989, 1996, 1999, 2000, 2008, 2011, 2012, 2017,
                 2018, 2021, 2022, 2023]
