from dataclasses import dataclass
from dataclasses_json import DataClassJsonMixin

@dataclass
class Company(DataClassJsonMixin):
    Version: str = ...
    RuntimeVersion: str = ...
    CompanyName: str = ...
    UserName: str = ...
    Notice: str = ...
    def printNotice(self) -> None: ...

@dataclass
class Division(DataClassJsonMixin):
    dataclass_json_config = ...
    id: int
    name: str | None = ...
    parent: Division | None = ...
