from ..datamodels.Company import Division as Division
from ..datamodels.geomodels.Geomodel import GeomodelEntry as GeomodelEntry
from ..datamodels.geospatial.Crs import CrsSpec as CrsSpec
from ..datamodels.seismic.SeismicSurvey import SeismicSurveyEntry as SeismicSurveyEntry
from ..datamodels.strat.StratColumn import StratColumnEntry as StratColumnEntry
from ..datamodels.wells.Well import WellEntry as WellEntry
from .DataModel import ChangeAgentEnum as ChangeAgentEnum, DataModel as DataModel
from .Document import Document as Document
from .Helpers import MakeIsodateOptionalField as MakeIsodateOptionalField
from .PrimaryDataObject import DataObjectTypeEnum as DataObjectTypeEnum, PrimaryDataObject as PrimaryDataObject
from .geospatial.GeoBox import GeoBox as GeoBox
from .map.UserLayer import UserLayer as UserLayer
from dataclasses import dataclass, field
from dataclasses_json import config
from datetime import datetime
from strenum import PascalCaseStrEnum
from typing import ClassVar

class ProjectTypeEnum(PascalCaseStrEnum):
    Unspecified = ...
    Prospect = ...
    AreaOfInterest = ...
    Development = ...
    Operations = ...
    Job = ...
    Subscription = ...
    DealRoom = ...
    DataRoom = ...
    SeismicSurvey = ...
    Well = ...
    Pad = ...

@dataclass
class Project(PrimaryDataObject):
    division: Division | None = ...
    company_name: str | None = ...
    coordinate_system: CrsSpec | None = ...
    boundary: GeoBox | None = ...
    boundary_locked: bool = ...
    number: str | None = ...
    description: str | None = ...
    project_type: ProjectTypeEnum = ...
    external_id: str | None = ...
    external_source: str | None = ...
    creator: str | None = ...
    change_agent: ChangeAgentEnum = ...
    creation_date: datetime | None = ...
    last_modified_date: datetime | None = ...
    property_number: str | None = ...
    afe_number: str | None = ...
    basin: str | None = ...
    play: str | None = ...
    zone: str | None = ...
    producing_field: str | None = field(default=None, metadata=config(field_name='Field'))
    country: str | None = ...
    state: str | None = ...
    county: str | None = ...
    district: str | None = ...
    block: str | None = ...
    is_active: bool = ...
    is_complete: bool = ...
    is_confidential: bool = ...
    start_date: datetime | None = ...
    completion_date: datetime | None = ...
    confidential_release_date: datetime | None = ...
    wells: list[WellEntry] = field(default_factory=list[WellEntry])
    layers: list[UserLayer] = field(default_factory=list[UserLayer])
    documents: list[Document] = field(default_factory=list[Document])
    seismic_surveys: list[SeismicSurveyEntry] = field(default_factory=list[SeismicSurveyEntry])
    strat_column: StratColumnEntry | None = ...
    geomodel: GeomodelEntry | None = ...
    archive_dir_name: ClassVar[str] = ...
    archive_json_filename: ClassVar[str] = ...
    @property
    def full_name(self) -> str: ...
    @property
    def data_object_type(self) -> DataObjectTypeEnum: ...

@dataclass
class ProjectEntry(DataModel):
    division: Division | None = ...
    company_name: str | None = ...
    number: str | None = ...
    description: str | None = ...
    row_version: str | None = ...
    @property
    def project(self) -> Project: ...
