#    QPane - High-performance PySide6 image viewer
#    Copyright (C) 2025  Artificial Sweetener and contributors
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

import uuid
from enum import Enum
from pathlib import Path
from typing import Any, Iterable, Mapping, TypeVar

from PySide6.QtCore import (
    QEvent,
    QObject,
    QPoint,
    QPointF,
    QRect,
    QRectF,
    QSize,
    Signal,
)
from PySide6.QtGui import (
    QColor,
    QCursor,
    QEnterEvent,
    QImage,
    QKeyEvent,
    QMouseEvent,
    QPainter,
    QTransform,
    QWheelEvent,
)
from PySide6.QtWidgets import QWidget

from .catalog import ImageMap
from .concurrency import TaskExecutorProtocol, ThreadPolicy
from .core import (
    CursorProvider,
    OverlayDrawFn,
    ToolFactory,
    ToolSignalBinder,
)
from .masks.workflow import MaskInfo
from .masks.mask_undo import MaskUndoState
from .types import CatalogSnapshot, LinkedGroup

_ConfigT = TypeVar("_ConfigT", bound="Config")

class CacheMode(str, Enum):
    AUTO = "auto"
    HARD = "hard"

class PlaceholderScaleMode(str, Enum):
    AUTO = "auto"
    LOGICAL_FIT = "logical_fit"
    PHYSICAL_FIT = "physical_fit"
    RELATIVE_FIT = "relative_fit"

class ZoomMode(str, Enum):
    FIT = "fit"
    LOCKED_ZOOM = "locked_zoom"
    LOCKED_SIZE = "locked_size"

class ControlMode(str, Enum):
    CURSOR = "cursor"
    PANZOOM = "panzoom"
    DRAW_BRUSH = "draw-brush"
    SMART_SELECT = "smart-select"

class DiagnosticsDomain(str, Enum):
    CACHE: str
    SWAP: str
    MASK: str
    EXECUTOR: str
    RETRY: str
    SAM: str

class OverlayState:
    zoom: float
    qpane_rect: QRect
    source_image: QImage
    transform: QTransform
    current_pan: QPointF
    physical_viewport_rect: QRectF

class PanelHitTest:
    panel_point: QPoint
    raw_point: QPointF
    clamped_point: QPoint
    inside_image: bool

class Config:
    def __init__(self, **overrides: Any) -> None: ...
    @staticmethod
    def feature_descriptors() -> Mapping[str, object]: ...
    def configure(
        self: _ConfigT, config_obj: object | None = ..., **kwargs: Any
    ) -> _ConfigT: ...
    def copy(self: _ConfigT) -> _ConfigT: ...
    def as_dict(self) -> dict[str, Any]: ...

class ExtensionToolSignals(QObject):
    pan_requested: Signal
    zoom_requested: Signal
    repaint_overlay_requested: Signal
    cursor_update_requested: Signal

class ExtensionTool:
    signals: ExtensionToolSignals
    def __init__(self) -> None: ...
    def activate(self, dependencies: Mapping[str, Any]) -> None: ...
    def deactivate(self) -> None: ...
    def mousePressEvent(self, event: QMouseEvent) -> None: ...
    def mouseMoveEvent(self, event: QMouseEvent) -> None: ...
    def mouseReleaseEvent(self, event: QMouseEvent) -> None: ...
    def mouseDoubleClickEvent(self, event: QMouseEvent) -> None: ...
    def wheelEvent(self, event: QWheelEvent) -> None: ...
    def enterEvent(self, event: QEnterEvent) -> None: ...
    def leaveEvent(self, event: QEvent) -> None: ...
    def keyPressEvent(self, event: QKeyEvent) -> None: ...
    def keyReleaseEvent(self, event: QKeyEvent) -> None: ...
    def draw_overlay(self, painter: QPainter) -> None: ...
    def getCursor(self) -> QCursor | None: ...

class QPane(QWidget):
    CONTROL_MODE_PANZOOM: str
    CONTROL_MODE_CURSOR: str
    CONTROL_MODE_DRAW_BRUSH: str
    CONTROL_MODE_SMART_SELECT: str

    imageLoaded: Signal
    zoomChanged: Signal
    viewportRectChanged: Signal
    maskSaved: Signal
    maskUndoStackChanged: Signal
    currentImageChanged: Signal
    catalogChanged: Signal
    catalogSelectionChanged: Signal
    linkGroupsChanged: Signal
    diagnosticsOverlayToggled: Signal
    diagnosticsDomainToggled: Signal
    samCheckpointStatusChanged: Signal
    samCheckpointProgress: Signal

    def __init__(
        self,
        *,
        config: Config | None = ...,
        features: Iterable[str] | None = ...,
        task_executor: TaskExecutorProtocol | None = ...,
        thread_policy: ThreadPolicy | Mapping[str, Any] | None = ...,
        config_strict: bool = ...,
        **kwargs: Any,
    ) -> None: ...
    @staticmethod
    def imageMapFromLists(
        images: Iterable[QImage],
        paths: Iterable[Path | None] | None = ...,
        ids: Iterable[uuid.UUID] | None = ...,
    ) -> ImageMap: ...
    @property
    def settings(self) -> Config: ...
    @settings.setter
    def settings(self, new_settings: Config) -> None: ...
    @property
    def installedFeatures(self) -> tuple[str, ...]: ...
    def placeholderActive(self) -> bool: ...
    @property
    def currentImage(self) -> QImage: ...
    @property
    def currentImagePath(self) -> Path | None: ...
    @property
    def allImages(self) -> list[QImage]: ...
    @property
    def allImagePaths(self) -> list[Path | None]: ...
    def imagePath(self, image_id: uuid.UUID | None) -> Path | None: ...
    def currentImageID(self) -> uuid.UUID | None: ...
    def imageIDs(self) -> list[uuid.UUID]: ...
    def hasImages(self) -> bool: ...
    def linkedGroups(self) -> tuple[LinkedGroup, ...]: ...
    def activeMaskID(self) -> uuid.UUID | None: ...
    def maskIDsForImage(self, image_id: uuid.UUID | None = ...) -> list[uuid.UUID]: ...
    def listMasksForImage(
        self, image_id: uuid.UUID | None = ...
    ) -> tuple[MaskInfo, ...]: ...
    def getActiveMaskImage(self) -> QImage | None: ...
    def getMaskUndoState(self, mask_id: uuid.UUID) -> MaskUndoState | None: ...
    def diagnosticsOverlayEnabled(self) -> bool: ...
    def diagnosticsDomains(self) -> tuple[str, ...]: ...
    def diagnosticsDomainEnabled(self, domain: str | DiagnosticsDomain) -> bool: ...
    def maskFeatureAvailable(self) -> bool: ...
    def samFeatureAvailable(self) -> bool: ...
    def samCheckpointReady(self) -> bool: ...
    def samCheckpointPath(self) -> Path | None: ...
    def refreshSamFeature(self) -> tuple[bool, str]: ...
    def availableControlModes(self) -> tuple[str, ...]: ...
    def getControlMode(self) -> str: ...
    def currentZoom(self) -> float: ...
    def currentViewportRect(self) -> QRectF: ...
    def setZoomFit(self) -> None: ...
    def setZoom1To1(self, anchor: QPoint | QPointF | None = ...) -> None: ...
    def applyZoom(
        self,
        requested_zoom: float,
        anchor: QPoint | QPointF | None = ...,
    ) -> None: ...
    def panelHitTest(self, panel_pos: QPoint) -> PanelHitTest | None: ...
    def applySettings(
        self, *, config: Config | None = ..., **overrides: Any
    ) -> None: ...
    def setDiagnosticsOverlayEnabled(self, enabled: bool) -> None: ...
    def setDiagnosticsDomainEnabled(
        self, domain: str | DiagnosticsDomain, enabled: bool
    ) -> None: ...
    def registerOverlay(
        self,
        name: str,
        draw_fn: OverlayDrawFn,
    ) -> None: ...
    def unregisterOverlay(self, name: str) -> None: ...
    def contentOverlays(self) -> Mapping[str, OverlayDrawFn]: ...
    def overlaysSuspended(self) -> bool: ...
    def overlaysResumePending(self) -> bool: ...
    def resumeOverlays(self) -> None: ...
    def resumeOverlaysAndUpdate(self) -> None: ...
    def maybeResumeOverlays(self) -> None: ...
    def registerCursorProvider(self, mode: str, provider: CursorProvider) -> None: ...
    def unregisterCursorProvider(self, mode: str) -> None: ...
    def registerTool(
        self,
        mode: str,
        factory: ToolFactory,
        *,
        on_connect: ToolSignalBinder | None = ...,
        on_disconnect: ToolSignalBinder | None = ...,
    ) -> None: ...
    def unregisterTool(self, mode: str) -> None: ...
    def setImagesByID(
        self,
        image_map: ImageMap,
        current_id: uuid.UUID,
    ) -> None: ...
    def clearImages(self) -> None: ...
    def removeImageByID(self, image_id: uuid.UUID) -> None: ...
    def removeImagesByID(self, image_ids: list[uuid.UUID]) -> None: ...
    def setCurrentImageID(self, image_id: uuid.UUID | None) -> None: ...
    def setAllImagesLinked(self, enabled: bool) -> None: ...
    def setLinkedGroups(self, groups: Iterable[LinkedGroup]) -> None: ...
    def getCatalogSnapshot(self) -> CatalogSnapshot: ...
    def createBlankMask(self, size: QSize) -> uuid.UUID | None: ...
    def loadMaskFromFile(self, path: str) -> uuid.UUID | None: ...
    def removeMaskFromImage(self, image_id: uuid.UUID, mask_id: uuid.UUID) -> bool: ...
    def setActiveMaskID(self, mask_id: uuid.UUID | None) -> bool: ...
    def setMaskProperties(
        self,
        mask_id: uuid.UUID,
        color: QColor | None = ...,
        opacity: float | None = ...,
    ) -> bool: ...
    def prefetchMaskOverlays(
        self, image_id: uuid.UUID | None, *, reason: str = ...
    ) -> bool: ...
    def cycleMasksForward(self) -> bool: ...
    def cycleMasksBackward(self) -> bool: ...
    def undoMaskEdit(self) -> bool: ...
    def redoMaskEdit(self) -> bool: ...
    def setControlMode(
        self,
        mode: str,
    ) -> None: ...
