from typing import NamedTuple, List


class CoolingLimits(NamedTuple):
    min: float
    max: float


class __Cooling:
    def getIds(self) -> List[str]: ...
    def getActualTemperature(self, coolingId: str) -> float: ...
    def getDesiredTemperature(self, coolingId: str) -> float: ...
    def getLimits(self, coolingId: str) -> CoolingLimits: ...
    def getValueUnit(self, coolingId: str) -> str: ...

    def setDesiredTemperature(self, coolingId: str,
                              temperature: float) -> None: ...
