from typing import NamedTuple


class VidPid(NamedTuple):
    vendorId: int
    productId: int


class __DeviceProps:
    def getManufacturer(self) -> str: ...
    def getProduct(self) -> str: ...
    def getSerialNumber(self) -> str: ...
    def getConnectionString(self) -> str: ...
    def getUsbVidPid(self) -> VidPid: ...
    def getUsbInstancePath(self) -> str: ...
    def isUsbHighSpeed(self) -> bool: ...
    def isUsbSuperSpeed(self) -> bool: ...
