from typing import Final

from formed.constants import DEFAULT_FORMED_DIRECTORY, DEFAULT_WORKING_DIRECTORY

WORKFLOW_REFKEY: Final = "ref"
WORKFLOW_REFTYPE: Final = "ref"
WORKFLOW_DEFAULT_DIRECTORY: Final = DEFAULT_FORMED_DIRECTORY / "workflow"
WORKFLOW_DEFAULT_SETTINGS_PATH: Final = DEFAULT_WORKING_DIRECTORY / "formed.yml"
WORKFLOW_INTEGRATION_DIRECTORY: Final = DEFAULT_FORMED_DIRECTORY / "integrations"
WORKFLOW_WORKSPACE_DIRECTORY: Final = DEFAULT_FORMED_DIRECTORY / "workspaces"
