import numpy as np
from dvsense_driver.hal.camera_tool import ToolType, CameraTool
from dvsense_driver.hal.camera_tool import BasicParameterInfo, ToolInfo
from dvsense_driver.hal.dvs_camera_utils import CameraDescription
from dvsense_driver.base import ApsFrame, CalibratorParameters
from dvsense_driver.base import EventTriggerIn

class Calibrator:
    def __init__(self): ...
    def load_calibrator_param(sele, param:CalibratorParameters): ...
    def map_aps_to_dvs(self, aps_frame: ApsFrame) -> ApsFrame:...
    def map_dvs_to_aps(self, arr: np.ndarray): ...