"""Type stubs for the xtce_codec package."""

from typing import Any, Dict, List

# Re-export all functions from the Rust module with their type annotations

# General functions
def unpack_parameters(
    packet_bytes: bytes, offset_bits: int, recipe: List[Any]
) -> Dict[str, Any]: ...
def pack_parameters(recipe: List[Any], values: Dict[str, Any]) -> bytes: ...

# Integer decoding functions
def decode_ones_complement(value: int, bits: int) -> int: ...
def decode_twos_complement(value: int, bits: int) -> int: ...
def decode_sign_magnitude(value: int, bits: int) -> int: ...
def decode_unpacked_bcd(value: int, bits: int, signed: bool = False) -> int: ...
def decode_packed_bcd(value: int, bits: int, signed: bool = False) -> int: ...

# Integer encoding functions
def encode_ones_complement(value: int, bits: int) -> int: ...
def encode_twos_complement(value: int, bits: int) -> int: ...
def encode_sign_magnitude(value: int, bits: int) -> int: ...
def encode_unpacked_bcd(value: int, bits: int, signed: bool = False) -> int: ...
def encode_packed_bcd(value: int, bits: int, signed: bool = False) -> int: ...

# Floating-point decoding functions
def decode_ieee754_f16(value: int) -> float: ...
def decode_ieee754_f32(value: int) -> float: ...
def decode_ieee754_f64(value: int) -> float: ...
def decode_ieee754_f128(value: int) -> float: ...
def decode_ieee754_1985_f32(value: int) -> float: ...
def decode_ieee754_1985_f64(value: int) -> float: ...
def decode_ieee754_1985_f80(value: int) -> float: ...
def decode_mil_std_1750a_f32(value: int) -> float: ...
def decode_mil_std_1750a_f48(value: int) -> float: ...
def decode_dec_f32(value: int) -> float: ...
def decode_dec_f64(value: int) -> float: ...
def decode_ibm_f32(value: int) -> float: ...
def decode_ibm_f64(value: int) -> float: ...
def decode_ti_f32(value: int) -> float: ...
def decode_ti_f40(value: int) -> float: ...

# Floating-point encoding functions
def encode_ieee754_f16(value: float) -> int: ...
def encode_ieee754_f32(value: float) -> int: ...
def encode_ieee754_f64(value: float) -> int: ...
def encode_ieee754_f128(value: float) -> int: ...
def encode_ieee754_1985_f32(value: float) -> int: ...
def encode_ieee754_1985_f64(value: float) -> int: ...
def encode_ieee754_1985_f80(value: float) -> int: ...
def encode_mil_std_1750a_f32(value: float) -> int: ...
def encode_mil_std_1750a_f48(value: float) -> int: ...
def encode_dec_f32(value: float) -> int: ...
def encode_dec_f64(value: float) -> int: ...
def encode_ibm_f32(value: float) -> int: ...
def encode_ibm_f64(value: float) -> int: ...
def encode_ti_f32(value: float) -> int: ...
def encode_ti_f40(value: float) -> int: ...

# String decoding functions
def decode_us_ascii(bytes: bytes) -> str: ...
def decode_iso_8859_1(bytes: bytes) -> str: ...
def decode_windows_1252(bytes: bytes) -> str: ...
def decode_utf8(bytes: bytes) -> str: ...
def decode_utf16(bytes: bytes) -> str: ...
def decode_utf16le(bytes: bytes) -> str: ...
def decode_utf16be(bytes: bytes) -> str: ...
def decode_utf32(bytes: bytes) -> str: ...
def decode_utf32le(bytes: bytes) -> str: ...
def decode_utf32be(bytes: bytes) -> str: ...

# String encoding functions
def encode_us_ascii(text: str) -> bytes: ...
def encode_iso_8859_1(text: str) -> bytes: ...
def encode_windows_1252(text: str) -> bytes: ...
def encode_utf8(text: str) -> bytes: ...
def encode_utf16(text: str) -> bytes: ...
def encode_utf16le(text: str) -> bytes: ...
def encode_utf16be(text: str) -> bytes: ...
def encode_utf32(text: str) -> bytes: ...
def encode_utf32le(text: str) -> bytes: ...
def encode_utf32be(text: str) -> bytes: ...
