"""Default configuration for the pages application."""
from __future__ import annotations

from typing import Dict

DEFAULT_APPLICATION_DESCRIPTIONS: Dict[str, str] = {
    "app": "Application registry and metadata.",
    "audio": "Audio playback, capture, and signal processing helpers.",
    "aws": "AWS service integrations and infrastructure helpers.",
    "base": "Core configurations and shared utilities.",
    "cards": "Reusable UI cards and layout helpers.",
    "celery": "Celery integration and scheduled task tooling.",
    "certs": "Certificate management and lifecycle automation.",
    "chats": "Chat messaging and conversational flows.",
    "clocks": "Timekeeping utilities, schedules, and reminders.",
    "content": "Static content blocks and editorial assets.",
    "awg": "Power, Energy and Cost calculations.",
    "counters": "Counting helpers and numeric trackers.",
    "core": "Support for Business Processes and monetization.",
    "credentials": "Credential storage and secrets management helpers.",
    "dns": "Domain name utilities and DNS helpers.",
    "docs": "Documentation and reference pages.",
    "emails": "Email delivery and templating.",
    "ocpp": "Compatibility with Standards and Good Practices.",
    "ocpp_forwarder": "Forward OCPP payloads to downstream systems.",
    "ocpp_simulator": "Simulate OCPP devices and interactions.",
    "embeds": "Embeddable widgets and integrations.",
    "energy": "Support for Energy processes and monetization.",
    "flows": "Workflow orchestration and pipelines.",
    "ftp": "FTP connectivity and file transfer helpers.",
    "groups": "Shared group definitions and permissions.",
    "nodes": "System and Node-level operations.",
    "links": "Link management and redirects.",
    "locale": "Localization helpers and translations.",
    "locals": "Local environment helpers and overrides.",
    "logbook": "Audit logs and operational event tracking.",
    "maps": "Geospatial utilities and map views.",
    "media": "Media storage and asset management.",
    "mermaid": "Diagram rendering and Mermaid integration.",
    "meta": "Metadata helpers and system insights.",
    "nmcli": "Network manager CLI integrations.",
    "modules": "Module discovery and registry helpers.",
    "nginx": "Nginx configuration and reverse proxy helpers.",
    "odoo": "Odoo integrations and ERP data sync helpers.",
    "payments": "Payment gateways and billing helpers.",
    "pages": "User QA, Continuity Design and Chaos Testing.",
    "pyxel": "Pyxel game tooling and pixel-art helpers.",
    "protocols": "Protocol helpers and shared interfaces.",
    "rates": "Rates, pricing and tariff helpers.",
    "release": "Release management and deployment helpers.",
    "reports": "Reporting pipelines and analytics summaries.",
    "rfid": "RFID tag scanning and notifications.",
    "recipes": "Scriptable recipes for reusable actions and validations.",
    "repos": "Repository management and release helpers.",
    "screens": "UI screen definitions and templates.",
    "selenium": "Browser automation and Selenium helpers.",
    "sensors": "Sensor data ingestion and monitoring utilities.",
    "sigils": "Sigil handling and certificate helpers.",
    "sites": "Site management, domains, and tenancy helpers.",
    "socials": "Social integrations and sharing utilities.",
    "summary": "Aggregated dashboards and executive summaries.",
    "survey": "Survey collection and response management.",
    "teams": "Identity, Entitlements and Access Controls.",
    "tasks": "Task execution and job tracking.",
    "terms": "Terms, policies, and legal content management.",
    "tests": "Test fixtures, utilities, and QA helpers.",
    "totp": "Time-based OTP and MFA utilities.",
    "users": "User profiles and authentication helpers.",
    "vehicle": "Vehicle management and telemetry.",
    "video": "Video capture, playback, and streaming helpers.",
    "widgets": "Reusable UI widgets and embed components.",
    "wikis": "Wiki pages and collaborative documentation.",
}
