from typing_extensions import override
from typing import Iterator, Self
from ...vocabulary import Domain, Vocabulary
from ...structure import Structure, ExtTypeElement, TypeElement

class Set:
    def __init__(self, domain: Domain, structure: Structure) -> None: ...
    def vocab(self) -> Vocabulary: ...
    def __len__(self) -> int: ...
    def __contains__(self, args: tuple[ExtTypeElement]) -> bool: ...
    def add(self, args: tuple[ExtTypeElement]) -> None: ...
    def __iter__(self) -> Iterator[tuple[TypeElement]]:
        "@public"
        ...
    def negate(self) -> None: ...
    def __invert__(self) -> Self:
        "@public"
        ...
    @override
    def __repr__(self) -> str: ...
    @override
    def __str__(self) -> str: ...
