from __future__ import annotations
from ._pure import *
from ..structure import TypeInterp
from typing import Iterable, Self
from typing_extensions import override

class Domain:
    def __init__(self, vocabulary: "Vocabulary", types: Iterable[ExtType]) -> None: ...
    def __getitem__(self, index: int) -> Type: ...
    def __iter__(self) -> Iterable[Type]: ...
    def __len__(self) -> int: ...
    def vocab(self) -> "Vocabulary": ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class Symbol:
    def name(self) -> str: ...
    def domain(self) -> Domain | UnaryUniverse: ...
    def codomain(self) -> Type: ...
    def __str__(self) -> str: ...
class CustomSymbol(Symbol):
    def vocab(self) -> "Vocabulary": ...
class BuiltinBool(Symbol):
    @override
    def domain(self) -> UnaryUniverse: ...
    @override
    def codomain(self) -> BuiltinBool: ...
class BuiltinInt(Symbol):
    @override
    def domain(self) -> UnaryUniverse: ...
    @override
    def codomain(self) -> BuiltinBool: ...
class BuiltinReal(Symbol):
    @override
    def domain(self) -> UnaryUniverse: ...
    @override
    def codomain(self) -> BuiltinBool: ...
class IntType(CustomSymbol):
    @override
    def domain(self) -> UnaryUniverse: ...
    @override
    def codomain(self) -> BuiltinBool: ...
class RealType(CustomSymbol):
    @override
    def domain(self) -> UnaryUniverse: ...
    @override
    def codomain(self) -> BuiltinBool: ...
class StrType(CustomSymbol):
    @override
    def domain(self) -> UnaryUniverse: ...
    @override
    def codomain(self) -> BuiltinBool: ...
class Pfunc(CustomSymbol):
    @override
    def domain(self) -> Domain: ...
    @override
    def codomain(self) -> BuiltinBool: ...

class SymbolIter:
    def __iter__(self) -> Self: ...
    def __next__(self) -> Symbol: ...
    def vocab(self) -> "Vocabulary": ...

class TypeIter:
    def __iter__(self) -> Self: ...
    def __next__(self) -> CustomType: ...
    def vocab(self) -> "Vocabulary": ...

class PfuncIter:
    def __iter__(self) -> Self: ...
    def __next__(self) -> Pfunc: ...
    def vocab(self) -> "Vocabulary": ...

class Real:
    def __init__(self, value: int | float | str): ...
    def __add__(self, other: Self) -> Self: ...
    def __sub__(self, other: Self) -> Self: ...
    def __mul__(self, other: Self) -> Self: ...
    def __div__(self, other: Self) -> Self: ...
    def __mod__(self, other: Self) -> Self: ...
    def __float__(self) -> float: ...


class Vocabulary:
    def __init__(self) -> None: ...
    def parse(self, decls: str) -> None: ...
    def add_type(self, name: str, super_set: ExtType | None = None) -> None: ...
    def add_voc_type_interp(self, type: ExtCustomType, interp: TypeInterp) -> None: ...
    def parse_type(self, value: str) -> Type: ...
    def parse_pfunc(self, value: str) -> Pfunc: ...
    def parse_symbol(self, value: str) -> Symbol: ...
    def add_pfunc(
        self, name: str | Iterable[str], domain: Iterable[ExtType], codomain: ExtType
    ) -> None: ...
    def iter_symbols(self) -> SymbolIter: ...
    def iter_pfuncs(self) -> PfuncIter: ...
    def iter_types(self) -> TypeIter: ...
    def merge(self, other: Self) -> None: ...
    def __str__(self) -> str: ...
