from enum import Enum


class PaymentPurpose(str, Enum):
    """Enumeration of supported payout purposes."""

    FAMILY_SUPPORT = "FAMILY_SUPPORT"
    PAYMENT_OF_BILLS = "PAYMENT_OF_BILLS"
    PURCHASE_OF_GOODS = "PURCHASE_OF_GOODS"
    PROFESSIONAL_SERVICES = "PROFESSIONAL_SERVICES"
    RENTAL_OF_SPACES = "RENTAL_OF_SPACES"
    INVESTMENTS = "INVESTMENTS"
    COMMISSIONS_LOANS_CAPITAL_INCREASE = "COMMISSIONS_LOANS_CAPITAL_INCREASE"
    TRANSPORTATION_COSTS = "TRANSPORTATION_COSTS"
    FEES = "FEES"
