import numpy as np
from dvsense_driver.hal.camera_tool import ToolType, CameraTool
from dvsense_driver.hal.camera_tool import BasicParameterInfo, ToolInfo
from dvsense_driver.hal.dvs_camera_utils import CameraDescription

class DvsCamera:
    def __init__(self): ...
    def is_connected(self) -> bool: ...
    def get_description(self) -> CameraDescription: ...
    def get_next_batch(self) -> np.ndarray: ...
    def set_batch_events_num(self, n: int): ...
    def set_batch_events_time(self, t: int): ...
    def start(self): ...
    def stop(self): ...
    def start_recording(self, file_path: str) -> int: ...
    def stop_recording(self) -> int: ...
    def get_width(self) -> int: ...
    def get_height(self) -> int: ...
    def get_all_tools_info(self) -> list[BasicParameterInfo]: ...
    def get_tool_info(self, tool_type: ToolType) -> ToolInfo: ...
    def get_tool(self, tool_type: ToolType) -> CameraTool: ...
