statistics = (
    "quantile 5%",
    "quantile 10%",
    "quantile 15%",
    "quantile 20%",
    "quantile 25%",
    "quantile 30%",
    "quantile 35%",
    "quantile 40%",
    "quantile 45%",
    "quantile 50%",
    "quantile 55%",
    "quantile 60%",
    "quantile 65%",
    "quantile 70%",
    "quantile 75%",
    "quantile 80%",
    "quantile 85%",
    "quantile 90%",
    "quantile 95%",
    "mean",
    "sem",
    "std",
    "confidence interval of the mean at 95%",
)

statistic_aliases = {
    "quantile 5%": "FirstVigintile",
    "quantile 25%": "FirstQuartile",
    "quantile 50%": "Median",
    "quantile 75%": "LastQuartile",
    "quantile 95%": "LastVigintile",
    "mean": "Mean",
    "sem": "SE",
}
