from ..datamodels.Company import Company as Company, Division as Division
from ..datamodels.DataModel import DataObjectTypeEnum as DataObjectTypeEnum
from ..datamodels.Project import Project as Project, ProjectEntry as ProjectEntry
from .Client import Client as Client

class CompanyService:
    client: Client
    def __init__(self, c: Client) -> None: ...
    def get_info(self) -> Company: ...
    def get_divisions(self) -> list[Division]: ...
    def change_division(self, data_ids: list[int], data_type: DataObjectTypeEnum, division: Division | int) -> None: ...
    def get_delete_authorization(self) -> None: ...
    def confirm_delete_authorization(self, code: str) -> tuple[bool, str]: ...
