from ..datamodels.wells.Note import Note as Note
from ..datamodels.wells.NoteCategory import NoteCategory as NoteCategory
from ..datamodels.wells.Wellbore import Wellbore as Wellbore
from .Client import Client as Client

class NoteService:
    client: Client
    def __init__(self, c: Client) -> None: ...
    def get_notes(self, wellbore: Wellbore) -> list[Note]: ...
    def load_notes(self, wellbore: Wellbore) -> list[Note]: ...
    def add_notes(self, wellbore: Wellbore, notes: list[Note]) -> None: ...
    def delete_notes(self, wellbore: Wellbore) -> None: ...
    def get_categories(self) -> list[NoteCategory]: ...
