from ..datamodels.strat.StratColumn import StratColumn as StratColumn, StratColumnEntry as StratColumnEntry
from .Client import Client as Client

class StratService:
    client: Client
    def __init__(self, c: Client) -> None: ...
    def get_stratcolumns(self, match_token: str | None = None, exact_match: bool = False) -> list[StratColumnEntry]: ...
    def get_first_named(self, name: str) -> StratColumn | None: ...
    def find_stratcolumn(self, strat_column: StratColumnEntry | int) -> StratColumn: ...
    def add_stratcolumn(self, col: StratColumn) -> None: ...
