from .. import ZonevuError as ZonevuError
from ..datamodels.surveymods import SurveyModEntry as SurveyModEntry
from ..datamodels.surveymods.SurveyMod import SurveyMod as SurveyMod
from ..datamodels.wells.Wellbore import Wellbore as Wellbore
from .Client import Client as Client
from .SurveyService import SurveyService as SurveyService

class SurveyModsService:
    client: Client
    def __init__(self, c: Client) -> None: ...
    def get_mods(self, wellbore_id: int) -> list[SurveyModEntry]: ...
    def find_mod(self, mod_id: int) -> SurveyMod: ...
    def load_mods(self, wellbore: Wellbore) -> list[SurveyMod]: ...
    def add_mods(self, wellbore: Wellbore | int, mods: list[SurveyMod]) -> None: ...
    def delete_mod(self, mod: SurveyMod, delete_code: str) -> None: ...
    def update_survey_id(self, mod: SurveyMod, old_survey_id: int, new_survey_id: int) -> bool: ...
