from ..datamodels.wells.Station import Station as Station
from ..datamodels.wells.Survey import Survey as Survey
from ..datamodels.wells.Wellbore import Wellbore as Wellbore
from .Client import Client as Client

class SurveyService:
    client: Client
    def __init__(self, c: Client) -> None: ...
    def get_surveys(self, wellbore_id: int) -> list[Survey]: ...
    def find_survey(self, survey_id: int) -> Survey: ...
    def load_survey(self, survey: Survey) -> Survey: ...
    def load_surveys(self, wellbore: Wellbore) -> list[Survey]: ...
    def add_survey(self, wellbore: Wellbore, survey: Survey) -> None: ...
    def delete_survey(self, survey: Survey, delete_code: str) -> None: ...
    def add_stations(self, survey: Survey, stations: list[Station]) -> list[Station]: ...
    def update_survey(self, survey: Survey) -> None: ...
