"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .dto_costpoint import DtoCostPoint, DtoCostPointTypedDict
from .meter_meter import MeterMeter, MeterMeterTypedDict
from .price_price import PricePrice, PricePriceTypedDict
from flexprice_sdk_test.types import BaseModel
from typing import Dict, List, Optional
from typing_extensions import NotRequired, TypedDict


class DtoCostAnalyticItemTypedDict(TypedDict):
    cost_by_period: NotRequired[List[DtoCostPointTypedDict]]
    r"""Breakdown"""
    costsheet_id: NotRequired[str]
    currency: NotRequired[str]
    r"""Metadata"""
    customer_id: NotRequired[str]
    external_customer_id: NotRequired[str]
    meter: NotRequired[MeterMeterTypedDict]
    meter_id: NotRequired[str]
    meter_name: NotRequired[str]
    price: NotRequired[PricePriceTypedDict]
    price_id: NotRequired[str]
    properties: NotRequired[Dict[str, str]]
    source: NotRequired[str]
    total_cost: NotRequired[str]
    r"""Aggregated metrics"""
    total_events: NotRequired[int]
    total_quantity: NotRequired[str]


class DtoCostAnalyticItem(BaseModel):
    cost_by_period: Optional[List[DtoCostPoint]] = None
    r"""Breakdown"""

    costsheet_id: Optional[str] = None

    currency: Optional[str] = None
    r"""Metadata"""

    customer_id: Optional[str] = None

    external_customer_id: Optional[str] = None

    meter: Optional[MeterMeter] = None

    meter_id: Optional[str] = None

    meter_name: Optional[str] = None

    price: Optional[PricePrice] = None

    price_id: Optional[str] = None

    properties: Optional[Dict[str, str]] = None

    source: Optional[str] = None

    total_cost: Optional[str] = None
    r"""Aggregated metrics"""

    total_events: Optional[int] = None

    total_quantity: Optional[str] = None
