"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from flexprice_sdk_test.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class TypesHubSpotConnectionMetadataTypedDict(TypedDict):
    access_token: NotRequired[str]
    r"""Private App Access Token (encrypted)"""
    app_id: NotRequired[str]
    r"""HubSpot App ID (optional, not encrypted)"""
    client_secret: NotRequired[str]
    r"""Private App Client Secret for webhook verification (encrypted)"""


class TypesHubSpotConnectionMetadata(BaseModel):
    access_token: Optional[str] = None
    r"""Private App Access Token (encrypted)"""

    app_id: Optional[str] = None
    r"""HubSpot App ID (optional, not encrypted)"""

    client_secret: Optional[str] = None
    r"""Private App Client Secret for webhook verification (encrypted)"""
