"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class TypesPaymentMethodType(str, Enum):
    CARD = "CARD"
    ACH = "ACH"
    OFFLINE = "OFFLINE"
    CREDITS = "CREDITS"
    PAYMENT_LINK = "PAYMENT_LINK"
