from typing import Dict, List, Optional, Any, Union
from enum import Enum


# Enums
class LayoutAnchor(str, Enum):
    TOP_LEFT = "top_left"
    TOP_CENTER = "top_center"
    TOP_RIGHT = "top_right"
    BOTTOM_LEFT = "bottom_left"
    BOTTOM_CENTER = "bottom_center"
    BOTTOM_RIGHT = "bottom_right"


class ZOrder(str, Enum):
    TOP = "top"
    BOTTOM = "bottom"
    NORMAL = "normal"


# Base Models
class ConfigBaseModel:
    def __init__(self, **data: Any) -> None: ...

    def dict(self) -> Dict[str, Any]: ...

    def model_dump(self) -> Dict[str, Any]: ...

    def model_dump_json(self) -> str: ...

    @classmethod
    def model_validate(cls, obj: Any) -> 'ConfigBaseModel': ...

    @classmethod
    def model_validate_json(cls, data: str) -> 'ConfigBaseModel': ...

    ...


# Config Classes
class HideInteractionsConfig(ConfigBaseModel):
    state: bool = ...
    in_class: bool = ...
    clicked: bool = ...
    maximized: bool = ...
    fullscreen: bool = ...
    mini_mode: bool = ...


class WidgetEntry(ConfigBaseModel):
    type_id: str
    instance_id: str
    settings: Optional[Dict[str, Any]] = ...


class LocaleConfig(ConfigBaseModel):
    language: str = ...


class ScheduleDefaultDurationConfig(ConfigBaseModel):
    class_: int = ...
    break_: int = ...
    activity: int = ...


class AppConfig(ConfigBaseModel):
    debug_mode: bool = ...
    no_logs: bool = ...
    version: str = ...
    channel: str = ...
    tutorial_completed: bool = ...
    auto_startup: bool = ...


class PreferencesConfig(ConfigBaseModel):
    current_theme: str = ...
    scale_factor: float = ...
    opacity: float = ...
    widgets_anchor: LayoutAnchor = ...
    widgets_offset_x: int = ...
    widgets_offset_y: int = ...
    widgets_layer: ZOrder = ...
    display: Optional[str] = ...
    mini_mode: bool = ...
    widgets_presets: Dict[str, List[WidgetEntry]] = ...
    current_preset: str = ...
    font: str = ...
    font_weight: int = ...


class InteractionsConfig(ConfigBaseModel):
    hover_fade: bool = ...
    hide: HideInteractionsConfig = ...


class PluginsConfig(ConfigBaseModel):
    enabled: List[str] = ...
    configs: Dict[str, Dict] = ...


class ScheduleConfig(ConfigBaseModel):
    current_schedule: str = ...
    preparation_time: int = ...
    default_duration: ScheduleDefaultDurationConfig = ...
    time_offset: int = ...
    reschedule_day: Dict[str, Any] = ...


class NetworkConfig(ConfigBaseModel):
    mirrors: Dict[str, str] = ...
    current_mirror: str = ...
    mirror_enabled: bool = ...
    releases_url: str = ...
    auto_check_updates: bool = ...


class RootConfig(ConfigBaseModel):
    app: AppConfig = ...
    locale: LocaleConfig = ...
    schedule: ScheduleConfig = ...
    preferences: PreferencesConfig = ...
    interactions: InteractionsConfig = ...
    plugins: PluginsConfig = ...
    network: NetworkConfig = ...


# ============ Config Manager ============
class ConfigManager:
    configChanged: Any = ...  # Signal 类型

    def __init__(self, path: Any, filename: str) -> None: ...

    def load_config(self) -> None: ...

    def save(self, silent: bool = ...) -> None: ...

    def __getattr__(self, name: str) -> Any: ...

    @property
    def data(self) -> Dict[str, Any]: ...

    def set(self, key: str, value: Any) -> None: ...

    def setPlugin(self, plugin_id: str, key: str, value: Any) -> None: ...

    ...


__all__ = [
    'ConfigBaseModel',
    'LayoutAnchor',
    'ZOrder',
    'WidgetEntry',
    'LocaleConfig',
    'ScheduleDefaultDurationConfig',
    'AppConfig',
    'PreferencesConfig',
    'InteractionsConfig',
    'PluginsConfig',
    'ScheduleConfig',
    'NetworkConfig',
    'RootConfig',
    'ConfigManager',
]