"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .productoptionvalidationerror import (
    ProductOptionValidationError,
    ProductOptionValidationErrorTypedDict,
)
from moovio_sdk.types import BaseModel
import pydantic
from typing import Dict, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ProductOptionGroupValidationErrorTypedDict(TypedDict):
    name: NotRequired[str]
    description: NotRequired[str]
    min_select: NotRequired[str]
    max_select: NotRequired[str]
    options: NotRequired[Dict[str, ProductOptionValidationErrorTypedDict]]


class ProductOptionGroupValidationError(BaseModel):
    name: Optional[str] = None

    description: Optional[str] = None

    min_select: Annotated[Optional[str], pydantic.Field(alias="minSelect")] = None

    max_select: Annotated[Optional[str], pydantic.Field(alias="maxSelect")] = None

    options: Optional[Dict[str, ProductOptionValidationError]] = None
