from enum import StrEnum


class ImpersonatorTool(StrEnum):
    PLAYWRIGHT = "PLAYWRIGHT"
    PLAYWRIGHT_CDP_BROWSERLESS = "PLAYWRIGHT_CDP_BROWSERLESS"
    PLAYWRIGHT_CDP = "PLAYWRIGHT_CDP"
    PLAYWRIGHT_VNC = "PLAYWRIGHT_VNC"
    PLAYWRIGHT_WEBRTC = "PLAYWRIGHT_WEBRTC"
    TEMPLATE = "TEMPLATE"
