"""Type stubs for __util__ module."""

import time
from pathlib import Path
from typing import Any, List, Optional

class AbortError(Exception): ...
class SnapshotTransferError(AbortError): ...
class InsufficientSpaceError(AbortError): ...

class Snapshot:
    location: Path
    prefix: str
    endpoint: Any
    time_obj: time.struct_time
    locks: set
    parent_locks: set

    def __init__(
        self,
        location: str | Path,
        prefix: str,
        endpoint: Any,
        time_obj: Optional[time.struct_time] = None,
    ) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __lt__(self, other: "Snapshot") -> bool: ...
    def __repr__(self) -> str: ...
    def get_name(self) -> str: ...
    def get_path(self) -> Path: ...
    def find_parent(
        self, present_snapshots: List["Snapshot"]
    ) -> Optional["Snapshot"]: ...

def exec_subprocess(
    command: List[str], method: str = "check_output", **kwargs: Any
) -> Any: ...
def log_heading(caption: str) -> str: ...
def date_to_str(
    timestamp: Optional[time.struct_time] = None, fmt: Optional[str] = None
) -> str: ...
def str_to_date(
    time_string: Optional[str] = None, fmt: Optional[str] = None
) -> time.struct_time: ...
def is_btrfs(path: str | Path) -> bool: ...
def is_subvolume(path: str | Path) -> bool: ...
def read_locks(s: str) -> dict[str, Any]: ...
def write_locks(lock_dict: dict[str, Any]) -> str: ...
