from bclearer_core.constants.standard_constants import (
    UUIDS_COLUMN_NAME,
)

UUID_COLUMN_NAME_SEPARATOR = "_"

UUIDIFIED_DATAFRAME_PREFIX = "uuidified"
UUIDIFIED_DATAFRAME_DATAFRAME_NAME = (
    UUIDIFIED_DATAFRAME_PREFIX
    + UUID_COLUMN_NAME_SEPARATOR
    + "tables"
)
UUIDIFIED_COLUMN_DATAFRAME_NAME = (
    UUIDIFIED_DATAFRAME_PREFIX
    + UUID_COLUMN_NAME_SEPARATOR
    + "columns"
)
UUIDIFIED_CELL_DATAFRAME_NAME = (
    UUIDIFIED_DATAFRAME_PREFIX
    + UUID_COLUMN_NAME_SEPARATOR
    + "cells"
)

UUIDIFIED_OBJECT_NAME_COLUMN_NAME = (
    "names"
)
UUIDIFIED_COLUMN_PARENT_COLUMN_NAME = (
    "table_uuids"
)
UUIDIFIED_CELL_COLUMN_PARENT_COLUMN_NAME = (
    "column_uuids"
)
UUIDIFIED_CELL_ROW_PARENT_COLUMN_NAME = (
    "row_uuids"
)
UUIDIFIED_OBJECT_TYPE_COLUMN_NAME = (
    "type_uuids"
)
LAST_USED_COLUMN_NAME = (
    "last_used_in_run"
)

TEMPORARY_UUIDS_COLUMN_NAME = (
    "temporary"
    + UUID_COLUMN_NAME_SEPARATOR
    + UUIDS_COLUMN_NAME
)
RUN_UUIDS_COLUMN_NAME = (
    "run"
    + UUID_COLUMN_NAME_SEPARATOR
    + UUIDS_COLUMN_NAME
)
TEMPORARY_RUN_UUIDS_COLUMN_NAME = (
    "temporary"
    + UUID_COLUMN_NAME_SEPARATOR
    + RUN_UUIDS_COLUMN_NAME
)
