# hash table for making original samplesheet terms user friendlier
COL_NAMES_HASH_EMO_BON_VRE = {
    "alkalinity": "alkalinity (mEq/l)",
    "alkalinity_method": "alkalinity method",
    "ammonium": "ammonium (umol/l)",
    "ammonium_method": "ammonium method",
    "bac_prod": "bacterial production (ug/m3/d)",
    "bac_prod_method": "bacterial production method",
    "biomass": "biomass (g/l)",
    "biomass_method": "biomass method",
    "chem_administration": "chemical administration",
    "chlorophyll": "chlorophyll (ug/l)",
    "chlorophyll_method": "chlorophyll method",
    "collection_date": "collection date",
    "conduc": "conductivity (mS/cm)",
    "conduc_method": "conductivity method",
    "density": "density (g/m3)",
    "density_method": "density method",
    "depth": "sampling depth (m)",
    "diss_carb_dioxide": "dissolved carbon dioxide (umol/l)",
    "diss_carb_dioxide_method": "dissolved carbon dioxide method",
    "diss_inorg_carb": "dissolved inorganic carbon (ug/l)",
    "diss_inorg_carb_method": "dissolved inorganic carbon method",
    "diss_org_carb": "dissolved organic carbon (umol/l)",
    "diss_org_carb_method": "dissolved organic carbon method",
    "diss_org_nitro": "dissolved organic nitrogen (ug/l)",
    "diss_org_nitro_method": "dissolved organic nitrogen method",
    "diss_oxygen": "dissolved oxygen (mmol/kg)",
    "diss_oxygen_method": "dissolved oxygen method",
    "down_par": "visible waveband radiance (uE/m2/s)",
    "down_par_method": "downward PAR method",
    "env_broad_biome": "environment (biome)",
    "env_local": "environment (feature)",
    "env_material": "environment (material)",
    "env_package": "environmental package",
    "geo_loc_name": "country",
    "investigation_type": "investigation type",
    "latitude": "latitude",
    "loc_broad_ocean": "observatory location ocean or sea",
    "loc_loc": "observatory local location",
    "loc_regional": "observatory regional location",
    "longitude": "longitude",
    "n_alkanes": "n-alkanes",
    "n_alkanes_method": "n-alkanes method",
    "nitrate": "nitrate (umol/l)",
    "nitrate_method": "nitrate method",
    "nitrite": "nitrite (umol/l)",
    "nitrite_method": "nitrite method",
    "obs_id": "observatory ID",
    "organism_count": "organism count",
    "organism_count_method": "organism count method",
    "organization": "organization",
    "organization_country": "organization country",
    "part_org_carb": "particulate organic carbon (ug/l)",
    "part_org_carb_method": "particulate organic carbon method",
    "part_org_nitro": "particulate organic nitrogen (ug/l)",
    "part_org_nitro_method": "particulate organic nitrogen method",
    "petroleum_hydrocarb": "petroleum hydrocarbon (umol/l)",
    "petroleum_hydrocarb_method": "petroleum hydrocarbon method",
    "ph": "pH",
    "ph_method": "pH method",
    "phaeopigments": "phaeopigments (ug/l)",
    "phaeopigments_method": "phaeopigments method",
    "phosphate": "phosphate (umol/l)",
    "phosphate_method": "phosphate method",
    "pigments": "pigments (ug/l)",
    "pigments_method": "pigments method",
    "pressure": "pressure (atm)",
    "pressure_method": "pressure method",
    "primary_prod": "primary production (mg/m3/d)",
    "primary_prod_method": "primary production method",
    "project_name": "project name",
    "ref_code": "ref_code",
    "replicate": "replicate number",
    "samp_collect_device": "sample collection device or method",
    "sea_subsurf_salinity": "sea subsurface salinity (PSU)",
    "sea_subsurf_salinity_method": "sea subsurface salinity method",
    "sea_subsurf_temp": "sea subsurface temperature (C)",
    "sea_subsurf_temp_method": "sea subsurface temperature method",
    "sea_surf_salinity": "sea surface salinity (PSU)",
    "sea_surf_salinity_method": "sea surface salinity method",
    "sea_surf_temp": "sea surface temperature (C)",
    "sea_surf_temp_method": "sea surface temperature method",
    "silicate": "silicate (umol/l)",
    "silicate_method": "silicate method",
    "source_mat_id": "source material ID",
    "sulfate": "sulfate (umol/l)",
    "sulfate_method": "sulfate method",
    "sulfide": "sulfide (umol/l)",
    "sulfide_method": "sulfide method",
    "tidal_stage": "tidal stage",
    "tot_depth_water_col": "total depth (m)",
    "turbidity": "turbidity (FNU)",
    "turbidity_method": "turbidity method",
    "water_current": "water current (m3/s)",
    "water_current_method": "water current method",
}

TAXONOMY_RANKS = [
    "superkingdom",
    "kingdom",
    "phylum",
    "class",
    "order",
    "family",
    "genus",
    "species",
]
