"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from glean.api_client.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class AllowlistOptionsTypedDict(TypedDict):
    r"""Terms that are allow-listed during the scans. If any finding picked up by a rule exactly matches a term in the allow-list, it will not be counted as a violation."""

    terms: NotRequired[List[str]]
    r"""list of words and phrases to consider as whitelisted content"""


class AllowlistOptions(BaseModel):
    r"""Terms that are allow-listed during the scans. If any finding picked up by a rule exactly matches a term in the allow-list, it will not be counted as a violation."""

    terms: Optional[List[str]] = None
    r"""list of words and phrases to consider as whitelisted content"""
