# coding: utf-8

"""
    Asset Processor API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from aurigma.asset_processor.models.conflict_type import ConflictType
from aurigma.asset_processor.models.identification_conflict_dto import IdentificationConflictDto
from aurigma.asset_processor.models.missing_fonts_conflict_dto import MissingFontsConflictDto
from aurigma.asset_processor.models.missing_images_conflict_dto import MissingImagesConflictDto
from aurigma.asset_processor.models.missing_palettes_conflict_dto import MissingPalettesConflictDto
from typing import Optional, Set
from typing_extensions import Self

class DesignUpdateConflictDto(BaseModel):
    """
    DesignUpdateConflictDto
    """ # noqa: E501
    missing_fonts_conflict: Optional[MissingFontsConflictDto] = Field(default=None, alias="missingFontsConflict")
    missing_images_conflict: Optional[MissingImagesConflictDto] = Field(default=None, alias="missingImagesConflict")
    missing_palettes_conflict: Optional[MissingPalettesConflictDto] = Field(default=None, alias="missingPalettesConflict")
    identification_conflict: Optional[IdentificationConflictDto] = Field(default=None, description="Information about identification conflict.", alias="identificationConflict")
    description: Optional[StrictStr] = Field(default=None, description="Problem description.")
    type: Optional[ConflictType] = Field(default=None, description="Coflict type.")
    __properties: ClassVar[List[str]] = ["missingFontsConflict", "missingImagesConflict", "missingPalettesConflict", "identificationConflict", "description", "type"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DesignUpdateConflictDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of missing_fonts_conflict
        if self.missing_fonts_conflict:
            _dict['missingFontsConflict'] = self.missing_fonts_conflict.to_dict()
        # override the default output from pydantic by calling `to_dict()` of missing_images_conflict
        if self.missing_images_conflict:
            _dict['missingImagesConflict'] = self.missing_images_conflict.to_dict()
        # override the default output from pydantic by calling `to_dict()` of missing_palettes_conflict
        if self.missing_palettes_conflict:
            _dict['missingPalettesConflict'] = self.missing_palettes_conflict.to_dict()
        # override the default output from pydantic by calling `to_dict()` of identification_conflict
        if self.identification_conflict:
            _dict['identificationConflict'] = self.identification_conflict.to_dict()
        # set to None if missing_fonts_conflict (nullable) is None
        # and model_fields_set contains the field
        if self.missing_fonts_conflict is None and "missing_fonts_conflict" in self.model_fields_set:
            _dict['missingFontsConflict'] = None

        # set to None if missing_images_conflict (nullable) is None
        # and model_fields_set contains the field
        if self.missing_images_conflict is None and "missing_images_conflict" in self.model_fields_set:
            _dict['missingImagesConflict'] = None

        # set to None if missing_palettes_conflict (nullable) is None
        # and model_fields_set contains the field
        if self.missing_palettes_conflict is None and "missing_palettes_conflict" in self.model_fields_set:
            _dict['missingPalettesConflict'] = None

        # set to None if identification_conflict (nullable) is None
        # and model_fields_set contains the field
        if self.identification_conflict is None and "identification_conflict" in self.model_fields_set:
            _dict['identificationConflict'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DesignUpdateConflictDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "missingFontsConflict": MissingFontsConflictDto.from_dict(obj["missingFontsConflict"]) if obj.get("missingFontsConflict") is not None else None,
            "missingImagesConflict": MissingImagesConflictDto.from_dict(obj["missingImagesConflict"]) if obj.get("missingImagesConflict") is not None else None,
            "missingPalettesConflict": MissingPalettesConflictDto.from_dict(obj["missingPalettesConflict"]) if obj.get("missingPalettesConflict") is not None else None,
            "identificationConflict": IdentificationConflictDto.from_dict(obj["identificationConflict"]) if obj.get("identificationConflict") is not None else None,
            "description": obj.get("description"),
            "type": obj.get("type")
        })
        return _obj


