# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .update_date_definition_params_field_configuration import UpdateDateDefinitionParamsFieldConfiguration


class UpdateDateDefinitionParams(UniversalBaseModel):
    field_configuration: typing.Optional[UpdateDateDefinitionParamsFieldConfiguration] = None
    field_type: typing.Literal["date"] = "date"
    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Field definition name
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
