# coding: utf-8

"""
Notehub API

The OpenAPI definition for the Notehub.io API.

The version of the OpenAPI document: 1.2.0
Contact: engineering@blues.io
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    StrictBool,
    StrictBytes,
    StrictInt,
    StrictStr,
)
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self


class Note(BaseModel):
    """
    Note
    """  # noqa: E501

    body: Dict[str, Any] = Field(
        description="Arbitrary user-defined JSON for the note."
    )
    edge: Optional[StrictBool] = Field(
        default=None, description="True if originated from an edge source."
    )
    id: StrictStr = Field(
        description='Note name/identifier (e.g., "1:435", "my_note").'
    )
    payload: Optional[Union[StrictBytes, StrictStr]] = Field(
        default=None, description="Optional base64-encoded payload."
    )
    pending: Optional[StrictBool] = Field(
        default=None, description="True if the note is pending delivery or processing."
    )
    time: StrictInt = Field(description="Unix epoch seconds.")
    where: Optional[StrictStr] = Field(
        default=None, description="Optional location/metadata string."
    )
    __properties: ClassVar[List[str]] = [
        "body",
        "edge",
        "id",
        "payload",
        "pending",
        "time",
        "where",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Note from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Note from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "body": obj.get("body"),
                "edge": obj.get("edge"),
                "id": obj.get("id"),
                "payload": obj.get("payload"),
                "pending": obj.get("pending"),
                "time": obj.get("time"),
                "where": obj.get("where"),
            }
        )
        return _obj
