class SocketBase:
    def send(self, data: bytes): ...

    def recv(self, size=None) -> bytes: ...

    @classmethod
    def connect(cls, remote_addr): ...

    @classmethod
    def new(cls): ...

    def set_option(self, option, value): ...

    def set_timeout(self, timeout): ...

    def get_option(self, option): ...
