# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: envoy/extensions/grpc_service/call_credentials/google_refresh_token/v3/google_refresh_token_credentials.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("GoogleRefreshTokenCredentials",)

import typing

import betterproto2
import pydantic
from pydantic.dataclasses import dataclass

from .......message_pool import default_message_pool

_COMPILER_VERSION = "0.9.0"
betterproto2.check_compiler_version(_COMPILER_VERSION)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class GoogleRefreshTokenCredentials(betterproto2.Message):
    """
    [#protodoc-title: gRPC Google Refresh Token Credentials]

    [#not-implemented-hide:]
    """

    token: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )
    """
    JSON refresh token.
    """


default_message_pool.register_message(
    "envoy.extensions.grpc_service.call_credentials.google_refresh_token.v3",
    "GoogleRefreshTokenCredentials",
    GoogleRefreshTokenCredentials,
)
