from dataclasses import dataclass
from dataclasses_json import DataClassJsonMixin

@dataclass
class GeoLocation(DataClassJsonMixin):
    dataclass_json_config = ...
    latitude: float
    longitude: float
    @property
    def tuple(self) -> tuple[float, float]: ...
    @property
    def tuple2(self) -> tuple[float, float]: ...
    @staticmethod
    def error(l1: GeoLocation, l2: GeoLocation) -> float: ...
    def __hash__(self): ...
    def __eq__(self, other): ...
    def arc_latitude(self) -> float: ...
    def arc_longitude(self) -> float: ...
    @staticmethod
    def bearing(s: GeoLocation, f: GeoLocation) -> float: ...
    @classmethod
    def lower_left_of(cls, l1: GeoLocation, l2: GeoLocation) -> GeoLocation: ...
    @classmethod
    def upper_right_of(cls, l1: GeoLocation, l2: GeoLocation) -> GeoLocation: ...
