from ..styles.Colors import RgbType as RgbType, decode_html_color as decode_html_color
from dataclasses import dataclass

@dataclass
class LineStyle:
    show: bool = ...
    color: str = ...
    thickness: float = ...
    dashed: bool = ...
    dash: str | None = ...
    @staticmethod
    def FromRGB(r: int, g: int, b: int) -> LineStyle: ...
    def get_color(self, rgb_type: RgbType) -> str | tuple[float, float, float]: ...
